---
sidebar: sidebar 
permalink: concept-iam-rbac.html 
keywords: roles, permissions, role-based access control, rbac, iam, identity and access management, least privilege, access control, NetApp Console access, organization access, folder access, project access, resource access 
summary: '역할 기반 액세스 제어(RBAC)를 사용하여 NetApp Console 에 대한 사용자 액세스를 관리하고, 조직, 폴더 또는 프로젝트 수준에서 미리 정의된 역할을 할당할 수 있습니다. 각 역할은 사용자가 할당된 범위 내에서 수행할 수 있는 작업을 정의하는 특정 권한을 부여합니다.' 
---
= NetApp Console 역할 기반 액세스 제어(RBAC)에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
역할 기반 액세스 제어(RBAC)를 사용하여 NetApp Console 에 대한 사용자 액세스를 관리하고, 조직, 폴더 또는 프로젝트 수준에서 미리 정의된 역할을 할당할 수 있습니다. 각 역할은 사용자가 할당된 범위 내에서 수행할 수 있는 작업을 정의하는 특정 권한을 부여합니다.

NetApp 최소 권한 원칙에 따라 콘솔 역할을 설계하므로 각 역할에는 해당 작업에 필요한 권한만 포함됩니다. 이러한 접근 방식은 각 구성원에게 필요한 권한만 허용함으로써 보안을 강화합니다.

리소스를 폴더와 프로젝트로 정리한 후에는 조직 구성원에게 특정 폴더 또는 프로젝트에 대한 역할을 할당하여 각자가 자신의 책임만 수행할 수 있도록 하세요.

예를 들어, 특정 프로젝트 수준에 대해 구성원에게 랜섬웨어 복원력 관리자 역할을 할당하여 해당 프로젝트 내의 리소스에 대한 랜섬웨어 복원력 작업을 수행할 수 있도록 허용하되, 조직 전체에 대한 광범위한 액세스 권한은 부여하지 않을 수 있습니다. 이 사용자는 조직 내 여러 프로젝트에 대해 동일한 역할을 부여받을 수 있습니다.

사용자의 책임에 따라 동일한 범위 또는 서로 다른 범위에 대해 여러 역할을 할당할 수 있습니다. 예를 들어, 소규모 조직에서는 동일한 사용자가 조직 차원에서 랜섬웨어 복원력과 백업 및 복구 작업을 모두 관리할 수 있는 반면, 대규모 조직에서는 프로젝트 차원에서 각 역할에 서로 다른 사용자를 할당할 수 있습니다.



== 콘솔 조직 구성원의 유형

NetApp Console 조직에는 세 가지 유형의 구성원이 있습니다.

* _사용자 계정_: NetApp Console에 로그인하여 리소스를 관리하는 개별 사용자입니다. 사용자는 조직에 추가되기 전에 NetApp Console에 가입해야 합니다.
* _서비스 계정_: 애플리케이션 또는 서비스가 API를 통해 NetApp Console과 상호 작용하는 데 사용하는 비인간 계정입니다. 서비스 계정은 Console 조직에 직접 추가할 수 있습니다.
* _페더레이션 그룹_: ID 공급자(IdP)에서 동기화된 그룹으로, 여러 사용자의 액세스를 일괄적으로 관리할 수 있습니다. 페더레이션 그룹 내의 각 사용자는 NetApp Console에 가입하고 액세스 역할과 함께 조직에 추가되어야 그룹에 부여된 리소스에 액세스할 수 있습니다.


link:task-iam-manage-members-permissions.html#add-members["조직에 구성원을 추가하는 방법을 알아보세요."]



== NetApp Console 의 사전 정의된 역할

NetApp Console 조직 구성원에게 할당할 수 있는 사전 정의된 역할이 포함되어 있습니다. 각 역할에는 구성원이 할당된 범위(조직, 폴더 또는 프로젝트) 내에서 수행할 수 있는 작업을 지정하는 권한이 포함되어 있습니다.

NetApp Console 역할은 최소 권한 원칙을 사용하여 구성원이 작업에 필요한 권한만 갖도록 보장하며, 제공하는 액세스 유형에 따라 역할을 분류합니다.

* 플랫폼 역할: 콘솔 관리 권한 제공
* 데이터 서비스 역할: 랜섬웨어 복원력 및 백업/복구와 같은 특정 데이터 서비스를 관리하기 위한 권한을 제공합니다.
* 애플리케이션 역할: 스토리지 관리 및 콘솔 이벤트와 알림 감사에 대한 권한을 제공합니다.


구성원의 책임에 따라 여러 역할을 할당할 수 있습니다. 예를 들어 특정 프로젝트에 대해 멤버에게 랜섬웨어 복원력 관리자 역할과 백업 및 복구 관리자 역할을 모두 할당할 수 있습니다.

link:reference-iam-predefined-roles.html["NetApp Console 에서 사용 가능한 사전 정의된 역할에 대해 알아보세요."].
