---
settings:
  name: NetApp Console setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp Console 설정 및 관리
    url: "/index.html"
  - title: 릴리스 노트
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 알려진 제한 사항
      url: "/reference-limitations.html"
    - title: 지원되는 Linux 운영 체제 변경 사항
      url: "/reference-agent-operating-system-changes.html"
  - title: 시작하기
    entries:
    - title: 기본을 배우세요
      entries:
      - title: NetApp Console
        url: "/concept-overview.html"
      - title: 콘솔 에이전트
        url: "/concept-agents.html"
      - title: 배포 모드
        url: "/concept-modes.html"
    - title: NetApp Console 어시스턴트 시작하기
      entries:
      - title: NetApp Console 어시스턴트 사용
        url: "/task-console-assistant.html"
    - title: 표준 모드로 시작하세요
      entries:
      - title: 시작하기 워크플로
        url: "/task-quick-start-standard-mode.html"
      - title: NetApp Console 대한 네트워크 액세스 준비
        url: "/reference-networking-saas-console.html"
      - title: NetApp Console 에 가입하세요
        url: "/task-sign-up-saas.html"
      - title: 콘솔 에이전트 만들기
        entries:
        - title: AWS
          entries:
          - title: 콘솔 에이전트 설치 옵션
            url: "/concept-install-options-aws.html"
          - title: NetApp Console 에서 콘솔 에이전트 만들기
            url: "/task-install-agent-aws-console.html"
          - title: 마켓플레이스에서 콘솔 에이전트 만들기
            url: "/task-install-agent-aws-marketplace.html"
          - title: 콘솔 에이전트를 수동으로 설치합니다.
            url: "/task-install-agent-aws-manual.html"
        - title: 하늘빛
          entries:
          - title: 콘솔 에이전트 설치 옵션
            url: "/concept-install-options-azure.html"
          - title: NetApp Console 에서 콘솔 에이전트 만들기
            url: "/task-install-agent-azure-console.html"
          - title: 마켓플레이스에서 콘솔 에이전트 만들기
            url: "/task-install-agent-azure-marketplace.html"
          - title: 콘솔 에이전트를 수동으로 설치합니다.
            url: "/task-install-agent-azure-manual.html"
        - title: 구글 클라우드
          entries:
          - title: 콘솔 에이전트 설치 옵션
            url: "/concept-install-options-google.html"
          - title: NetApp Console 에서 콘솔 에이전트 만들기
            url: "/task-install-agent-google-console-gcloud.html"
          - title: Google Cloud에서 콘솔 에이전트 만들기
            url: "/task-install-agent-google-gcloud.html"
          - title: 콘솔 에이전트를 수동으로 설치합니다.
            url: "/task-install-agent-google-manual.html"
        - title: 온프레미스에 에이전트 설치
          entries:
          - title: 온프레미스에 에이전트를 수동으로 설치
            url: "/task-install-agent-on-prem.html"
          - title: VCenter에 온프레미스 에이전트 설치
            url: "/task-install-agent-on-prem-ova.html"
      - title: NetApp Intelligent Services 구독
        url: "/task-subscribe-standard-mode.html"
      - title: 다음에 할 수 있는 일
        url: "/reference-whats-next.html"
    - title: 제한 모드 시작하기
      entries:
      - title: 시작하기 워크플로
        url: "/task-quick-start-restricted-mode.html"
      - title: 배치 준비
        url: "/task-prepare-restricted-mode.html"
      - title: 콘솔 에이전트 배포
        url: "/task-install-restricted-mode.html"
      - title: NetApp Intelligent Services 구독
        url: "/task-subscribe-restricted-mode.html"
      - title: 다음에 할 수 있는 일
        url: "/reference-whats-next-restricted-mode.html"
    - title: BlueXP 레거시 인터페이스(개인 모드) 시작하기
      entries:
      - title: BlueXP 레거시 인터페이스(개인 모드) 시작하기
        url: "/task-quick-start-private-mode.html"
  - title: NetApp Console 사용
    entries:
    - title: NetApp Console 에 로그인하세요
      url: "/task-logging-in.html"
    - title: NetApp Console 홈페이지에서 메트릭 보기
      url: "/task-dashboard.html"
    - title: NetApp Console 사용자 설정 관리
      url: "/task-user-settings.html"
  - title: NetApp Console 관리
    entries:
    - title: ID 및 액세스 관리
      entries:
      - title: ID 및 액세스 관리에 대해 알아보세요
        url: "/concept-identity-and-access-management.html"
      - title: 신원 및 액세스 시작하기
        url: "/task-iam-get-started.html"
      - title: 폴더와 프로젝트로 리소스를 구성하세요
        url: "/task-iam-manage-folders-projects.html"
      - title: 회원 및 서비스 계정 관리
        url: "/task-iam-manage-members-permissions.html"
      - title: 역할을 사용하여 리소스에 대한 멤버 액세스를 제어합니다.
        url: "/task-iam-manage-roles.html"
      - title: 리소스 계층 관리
        url: "/task-iam-manage-resources.html"
      - title: 콘솔 에이전트를 다른 폴더 및 프로젝트와 연결합니다.
        url: "/task-iam-associate-agents.html"
      - title: 조직, 프로젝트 및 콘솔 에이전트 간 전환
        url: "/task-iam-switch-organizations-projects.html"
      - title: 조직 및 프로젝트 ID
        url: "/task-iam-rename-organization.html"
      - title: IAM 활동 모니터링 또는 감사
        url: "/task-iam-audit-actions-timeline.html"
      - title: NetApp Console 액세스 역할
        entries:
        - title: NetApp Console 액세스 역할에 대해 알아보세요
          url: "/reference-iam-predefined-roles.html"
        - title: 플랫폼 역할
          url: "/reference-iam-platform-roles.html"
        - title: 애플리케이션 역할
          entries:
          - title: Google Cloud NetApp Volumes 역할
            url: "/reference-iam-gcnv-roles.html"
          - title: Keystone 역할
            url: "/reference-iam-keystone-roles.html"
          - title: 운영 지원 분석가
            url: "/reference-iam-analyst-roles.html"
          - title: 스토리지 역할
            url: "/reference-iam-storage-roles.html"
        - title: 데이터 서비스 역할
          entries:
          - title: 백업 및 복구 역할
            url: "/reference-iam-backup-rec-roles.html"
          - title: 재해 복구 역할
            url: "/reference-iam-disaster-rec-roles.html"
          - title: 랜섬웨어 복원력 역할
            url: "/reference-iam-ransomware-roles.html"
    - title: 파트너 기관
      entries:
      - title: 조직 파트너십에 대해 알아보세요
        url: "/concept-org-partnerships.html"
      - title: 조직 파트너십을 만드세요
        url: "/task-partnerships-create.html"
      - title: 파트너십 조직의 회원 관리
        url: "/task-partnerships-assign-users.html"
      - title: 파트너십 조직의 리소스 액세스 관리
        url: "/task-partnerships-resource-access.html"
      - title: 파트너 조직에서 일하다
        url: "/task-partnerships-work.html"
    - title: ID 페더레이션
      entries:
      - title: ID 페더레이션에 대해 알아보세요
        url: "/concept-federation.html"
      - title: 도메인 확인
        entries:
        - title: 도메인을 확인하세요
          url: "/task-federation-verify-domain.html"
      - title: 페더레이션 구성
        entries:
        - title: AD FS(Active Directory Federation Services) 공급자와 페더레이션
          url: "/task-federation-adfs.html"
        - title: Microsoft Entra ID 공급자와 페더레이션
          url: "/task-federation-entra-id.html"
        - title: PingFederate로 페더레이션
          url: "/task-federation-ping.html"
        - title: SAML ID 공급자와 페더레이션
          url: "/task-federation-saml.html"
      - title: 연합 관리
        url: "/task-federation-manage.html"
      - title: 기존 페더레이션 연결을 가져옵니다.
        url: "/task-federation-import.html"
    - title: 콘솔 에이전트
      entries:
      - title: VM 및 OS 유지 관리
        url: "/task-maintain-agents.html"
      - title: VCenter에 설치된 에이전트 유지 관리
        url: "/task-agent-vm-config.html"
      - title: 웹 콘솔 액세스를 위한 CA 서명 인증서 설치
        url: "/task-installing-https-cert.html"
      - title: 프록시 서버를 사용하도록 콘솔 에이전트 구성
        url: "/task-configuring-proxy.html"
      - title: EC2 인스턴스에서 IMDSv2 사용 요구
        url: "/task-require-imdsv2.html"
      - title: 에이전트 업그레이드 관리
        url: "/task-upgrade-agent.html"
      - title: 여러 콘솔 에이전트와 함께 작업
        url: "/task-manage-multiple-agents.html"
      - title: 콘솔 에이전트 문제 해결
        url: "/task-troubleshoot-agent.html"
      - title: 콘솔 에이전트를 제거하고 제거하세요
        url: "/task-uninstall-agent.html"
      - title: 기본 구성
        url: "/reference-agent-default-config.html"
      - title: NetApp Console 에서 ONTAP 권한 적용
        url: "/task-ontap-access-agent.html"
    - title: 자격 증명 및 구독
      entries:
      - title: AWS
        entries:
        - title: 자격 증명 및 권한에 대해 알아보세요
          url: "/concept-accounts-aws.html"
        - title: 자격 증명 및 구독 관리
          url: "/task-adding-aws-accounts.html"
      - title: 하늘빛
        entries:
        - title: 자격 증명 및 권한에 대해 알아보세요
          url: "/concept-accounts-azure.html"
        - title: 자격 증명 및 구독 관리
          url: "/task-adding-azure-accounts.html"
      - title: 구글 클라우드
        entries:
        - title: 프로젝트 및 권한에 대해 알아보세요
          url: "/concept-accounts-gcp.html"
        - title: 자격 증명 및 구독 관리
          url: "/task-adding-gcp-accounts.html"
      - title: NetApp Console 조직 또는 계정과 연결된 NSS 자격 증명 관리
        url: "/task-adding-nss-accounts.html"
      - title: NetApp Console 로그인과 관련된 자격 증명 관리
        url: "/task-manage-user-credentials.html"
    - title: NetApp Console 작업 모니터링
      url: "/task-monitor-cm-operations.html"
  - title: 참조
    entries:
    - title: 에이전트 유지 관리 콘솔
      entries:
      - title: 에이전트 유지 관리 콘솔
        url: "/reference-agent-maint-console.html"
    - title: 권한
      entries:
      - title: 권한 요약
        url: "/reference-permissions.html"
      - title: 콘솔 에이전트에 대한 AWS 권한
        url: "/reference-permissions-aws.html"
      - title: 콘솔 에이전트에 대한 Azure 권한
        url: "/reference-permissions-azure.html"
      - title: 콘솔 에이전트에 대한 Google Cloud 권한
        url: "/reference-permissions-gcp.html"
    - title: 포트
      entries:
      - title: AWS의 콘솔 에이전트 보안 그룹 규칙
        url: "/reference-ports-aws.html"
      - title: Azure의 콘솔 에이전트 보안 그룹 규칙
        url: "/reference-ports-azure.html"
      - title: Google Cloud의 콘솔 에이전트 방화벽 규칙
        url: "/reference-ports-gcp.html"
      - title: 온프레미스 콘솔 에이전트용 포트
        url: "/reference-ports-on-prem.html"
    - title: 콘솔 네트워크 액세스(레거시)
      url: "/reference-networking-saas-console-previous.html"
  - title: 지식과 지원
    entries:
    - title: 지원 등록
      url: "/task-support-registration.html"
    - title: 도움을 받으세요
      url: "/task-get-help.html"
  - title: 법적 고지 사항
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
