---
sidebar: sidebar 
permalink: reference-connector-operating-system-changes.html 
keywords: connector, operating systems, connector operating systems, os support, supported operating systems, rhel 8, rhel 9, red hat, docker, podman, agent 
summary: NetApp 때때로 특정 Linux 운영 체제에서 콘솔 에이전트에 대한 지원을 추가하거나 제거합니다. 이 지원이 기존 콘솔 에이전트에 어떤 영향을 미치는지 알아보세요. 
---
= 지원되는 Linux 운영 체제 변경 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 때때로 특정 Linux 운영 체제에서 콘솔 에이전트에 대한 지원을 추가하거나 제거합니다. 이 지원이 기존 콘솔 에이전트에 어떤 영향을 미치는지 알아보세요.



== 지원되는 운영 체제

NetApp 다음 Linux 운영 체제에서 에이전트를 지원합니다.

[role="tabbed-block"]
====
.표준 모드
--
수동 설치::
+
--
* 우분투 24.04 LTS
* 우분투 22.04 LTS
* 레드햇 엔터프라이즈 리눅스
+
** 8.6에서 8.10까지
** 9.1에서 9.4까지




--
NetApp 콘솔에서 배포:: 우분투 22.04 LTS
AWS Marketplace에서 배포:: 우분투 22.04 LTS
Azure Marketplace에서 배포:: 우분투 22.04 LTS


--
.제한 모드
--
수동 설치::
+
--
* 우분투 24.04 LTS
* 우분투 22.04 LTS
* 레드햇 엔터프라이즈 리눅스
+
** 8.6에서 8.10까지
** 9.1에서 9.4까지




--
AWS Marketplace에서 배포:: 우분투 22.04 LTS
Azure Marketplace에서 배포:: 우분투 22.04 LTS


--
.개인 모드
--
수동 설치::
+
--
* 우분투 22.04 LTS
* 레드햇 엔터프라이즈 리눅스
+
** 8.6에서 8.10까지
** 9.1에서 9.4까지




--


--
====


== RHEL 8 및 9 지원

RHEL 8 및 9 지원에 대한 다음 사항을 참고하세요.

제한 사항:: 온프레미스에 있는 RHEL 8 또는 9 호스트에 에이전트를 설치하는 경우 NetApp 데이터 분류가 지원됩니다.  RHEL 8 또는 9 호스트가 AWS, Azure 또는 Google Cloud에 있는 경우 지원되지 않습니다.
컨테이너 오케스트레이션 도구:: RHEL 8 또는 9 호스트에 콘솔 에이전트를 설치하는 경우 컨테이너 오케스트레이션 도구로 Podman 도구를 사용해야 합니다.  Docker Engine은 RHEL 8 및 9에서 지원되지 않습니다.
배포 모드:: RHEL 8과 9는 표준 모드와 제한 모드에서 콘솔을 사용할 때 지원됩니다.
지원되는 콘솔 에이전트 버전:: NetApp 다음 버전의 콘솔 에이전트부터 RHEL 8 및 9를 지원합니다.
+
--
* 3.9.40 표준 모드 또는 제한 모드에서 콘솔을 사용할 때


--
새로운 수동 설치만 가능:: RHEL 8 및 9는 사내 또는 클라우드에서 실행되는 호스트에 에이전트를 수동으로 설치할 때 _새로운_ 에이전트 설치가 지원됩니다.
RHEL 업그레이드:: RHEL 7 호스트에서 기존 에이전트를 실행 중인 경우 NetApp RHEL 7 운영 체제를 RHEL 8 또는 9로 업그레이드하는 것을 지원하지 않습니다. <<rhel-7-agent,RHEL 7 또는 CentOS 7의 기존 콘솔 에이전트에 대해 자세히 알아보세요.>> .




== RHEL 7 및 CentOS 7 지원 종료

2024년 6월 30일, RHEL 7은 유지 관리 종료(EOM)에 도달했고, CentOS 7은 지원 종료(EOL)에 도달했습니다.  NetApp 2024년 6월 30일에 이러한 Linux 배포판의 에이전트에 대한 지원을 중단했습니다.

https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance["Red Hat: Red Hat Enterprise Linux 7 유지 관리 종료에 대해 알아야 할 사항"^]



=== RHEL 7 또는 CentOS 7의 기존 콘솔 에이전트

RHEL 7 또는 CentOS 7에서 기존 에이전트를 실행 중인 경우 NetApp 운영 체제를 RHEL 8 또는 9로 업그레이드하거나 변환하는 것을 지원하지 않습니다.  지원되는 운영 체제에서 새 에이전트를 만들어야 합니다.

. RHEL 8 또는 9 호스트를 설정합니다.
. Podman을 설치하세요.
. _새로운_ 에이전트를 설치합니다.
. 이전 에이전트가 관리하던 시스템을 검색하도록 에이전트를 구성합니다.




== 관련 정보



=== RHEL 8 및 9를 시작하는 방법

호스트 요구 사항, Podman 요구 사항, Podman 및 Cagent 설치 단계에 대한 자세한 내용은 다음 페이지를 참조하세요.

[role="tabbed-block"]
====
.표준 모드
--
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["온프레미스에 콘솔 에이전트 설치 및 설정"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-manual.html["AWS에 콘솔 에이전트를 수동으로 설치합니다."]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-manual.html["Azure에 콘솔 에이전트를 수동으로 설치합니다."]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-google-manual.html["Google Cloud에 콘솔 에이전트를 수동으로 설치합니다."]


--
.제한 모드
--
https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-restricted-mode.html["제한 모드에서 배포 준비"]

--
====


=== 시스템을 재발견하는 방법

새 콘솔 에이전트를 배포한 후 시스템을 다시 검색하려면 다음 페이지를 참조하세요.

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["기존 Cloud Volumes ONTAP 시스템 추가"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["온프레미스 ONTAP 클러스터를 찾아보세요"^]
* https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html["ONTAP 시스템용 FSx 생성 또는 검색"^]
* https://docs.netapp.com/us-en/storage-management-azure-netapp-files/task-create-system.html["Azure NetApp Files 시스템 만들기"^]
* https://docs.netapp.com/us-en/bluexp-e-series/task-discover-e-series.html["E-시리즈 시스템을 알아보세요"^]
* https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID 시스템을 알아보세요"^]

