---
sidebar: sidebar 
permalink: reference-agent-maint-console-proxy.html 
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy, agent proxy 
summary: 콘솔 에이전트 유지 관리 콘솔을 사용하여 콘솔 에이전트가 투명 프록시 서버를 사용하도록 구성할 수 있습니다. 
---
= NetApp Console에서 Console 에이전트용 투명 프록시 명령
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
콘솔 에이전트 유지 관리 콘솔을 사용하여 콘솔 에이전트가 투명 프록시 서버를 사용하도록 구성할 수 있습니다.



[[access-the-agent-maintenance-console]]
== 에이전트 유지 관리 콘솔에 액세스하세요

Console 에이전트 호스트에서 유지 관리 콘솔에 액세스할 수 있습니다. 다음 디렉터리로 이동하십시오.

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


[[view-help-for-any-command]]
=== 모든 명령에 대한 도움말 보기

모든 명령에 대한 도움말을 보려면 다음을 추가하세요. `--help` 명령에.  예를 들어, 도움말을 보려면 `proxy add` 명령을 사용하려면 다음 명령을 사용하세요.

[source, cli]
----
./agent-maint-console proxy add --help
----


[[proxy-get]]
== 프록시 가져오기

그만큼 `proxy get` 이 명령은 현재 투명 프록시 서버 구성에 대한 정보를 표시합니다.  현재 투명 프록시 서버 구성을 보려면 다음 명령을 사용하십시오.



[[proxy-get-example]]
=== 프록시 가져오기 예시

[source, cli]
----
./agent-maint-console proxy get
----


[[proxy-add]]
== 프록시 추가

그만큼 `proxy add` 이 명령은 에이전트가 투명 프록시 서버를 사용하도록 구성합니다.



[[parameters]]
=== 매개변수

`-c <certificate file>`

[role="quick-margin-para"]
프록시 서버의 인증서 파일 경로를 지정합니다.  인증서 파일은 PEM 형식이어야 합니다. 인증서 파일이 명령과 같은 디렉토리에 있는지 확인하거나 인증서 파일의 전체 경로를 지정하세요.



[[proxy-add-example]]
=== 프록시 추가 예시

투명 프록시 서버를 추가하려면 다음 명령을 사용하십시오. `/home/ubuntu/myCA1.pem` 프록시 서버의 인증서 파일 경로입니다.  인증서 파일은 PEM 형식이어야 합니다.

[source, cli]
----
./agent-maint-console proxy add -c /home/ubuntu/myCA1.pem
----


[[proxy-update]]
== 프록시 업데이트

그만큼 `proxy update` 이 명령어를 사용하면 투명 프록시의 인증서를 업데이트할 수 있습니다.



[[parameters]]
=== 매개변수

`-c <certificate file>`프록시 서버의 인증서 파일 경로를 지정합니다.  인증서 파일은 PEM 형식이어야 합니다.

인증서 파일이 명령과 같은 디렉토리에 있는지 확인하거나 인증서 파일의 전체 경로를 지정하세요.



[[proxy-update-example]]
=== 프록시 업데이트 예시

투명 프록시 서버의 인증서를 업데이트하려면 다음 명령을 사용하십시오. `/home/ubuntu/myCA1.pem` 프록시 서버의 새 인증서 파일 경로입니다.  인증서 파일은 PEM 형식이어야 합니다.

[source, cli]
----
./agent-maint-console proxy update -c /home/ubuntu/myCA1.pem
----


[[proxy-remove]]
== 프록시 제거

그만큼 `proxy remove` 이 명령은 에이전트에서 투명 프록시 서버 구성을 제거합니다.



[[proxy-remove-example]]
=== 프록시 제거 예시

투명 프록시 서버를 제거하려면 다음 명령을 사용하십시오.

[source, cli]
----
./agent-maint-console proxy remove
----