---
sidebar: sidebar 
permalink: reference-networking-saas-console-previous.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, netapp console 
summary: 콘솔과 설치한 모든 에이전트가 제대로 작동하려면 올바른 네트워크 액세스 권한이 있는지 확인해야 합니다. 
---
= 3.9.55 이하 버전에 필요한 네트워크 액세스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console, NetApp Console 에이전트 및 NetApp 데이터 서비스는 필요한 엔드포인트에 연결하기 위해 아웃바운드 인터넷 액세스가 필요합니다.


NOTE: 이 항목에서는 NetApp Console 표준 모드 3.9.55 이하 버전에 필요한 네트워크 액세스에 대해 설명합니다.  4.0.0 이상에 필요한 엔드포인트에 대해서는 다음을 검토하세요.link:reference-networking-saas-console.html["4.0.0 이상에 필요한 엔드포인트"] .

다음에 대한 네트워크 액세스를 설정해야 합니다.

* SaaS(Software as a Service)로 NetApp Console 액세스하는 컴퓨터
* 온프레미스 또는 클라우드에 설치하는 콘솔 에이전트입니다.




== 4.0.0 이상에 대한 개정된 목록으로 엔드포인트 목록을 업데이트하세요.

버전 4.0.0부터 콘솔 에이전트에 필요한 엔드포인트 수가 줄었습니다.  4.0.0 이전의 기존 배포는 계속 지원됩니다.  4.0.0 이상으로 업그레이드한 후, 편리한 시기에 허용 목록에서 이전 엔드포인트를 제거할 수 있습니다.

NetApp 더 작고, 더 안전하며, 관리하기 쉬운 개정된 엔드포인트 목록을 사용하도록 방화벽 규칙을 업데이트할 것을 권장합니다.  NetApp 와일드카드 입력이 필요 없으며, 에이전트 업그레이드를 위한 엔드포인트는 모든 데이터 서비스를 지원합니다.

[cols="3*"]
|===
| *이전 종료점* | *4.0.0 이상용 엔드포인트* | *목적* 


 a| 
* \ https://support.netapp.com
* \ https://mysupport.netapp.com

 a| 
* \ https://mysupport.netapp.com
* \ https://signin.b2c.netapp.com
* \ https://support.netapp.com

 a| 
NetApp 지원팀에 라이선스를 요청하고 문의하세요.



 a| 
* \https://*.api.bluexp.netapp.com
* \ https://api.bluexp.netapp.com
* \https://*.cloudmanager.cloud.netapp.com
* \ https://cloudmanager.cloud.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.bluexp.netapp.com
* \https://*.console.bluexp.netapp.com

 a| 
* \ https://api.bluexp.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.netapp.com
* \ https://components.console.bluexp.netapp.com
* \ https://cdn.auth0.com

 a| 
일상 업무에 사용.



 a| 
* \https://*.blob.core.windows.net
* \ https://cloudmanagerinfraprod.azurecr.io

 a| 
* \ https://bluexpinfraprod.eastus2.data.azurecr.io
* \ https://bluexpinfraprod.azurecr.io

| 콘솔 에이전트 업그레이드를 위한 이미지를 얻으려면. 
|===
.단계
. 에이전트 버전이 4.0.0 이상인지 확인하세요.link:task-troubleshoot-agent.html#view-the-console-agent-version["에이전트 버전 보기."]
. 엔드포인트를 허용 목록에 추가link:reference-networking-saas-console.html["4.0.0 이상에서 지원되는 엔드포인트"] .
. 다음 명령을 실행하여 각 에이전트에서 서비스 관리자 2 서비스를 다시 시작합니다.
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. 다음 명령을 실행하고 에이전트 상태가 _active(running)_로 표시되는지 확인하세요.
+
[source, cli]
----
systemctl status netapp-service-manager.service
----
. 방화벽 허용 목록에서 이전 엔드포인트를 제거합니다.




== 3.9.55 이하 NetApp Console 및 콘솔 에이전트의 엔드포인트

이러한 엔드포인트는 콘솔 에이전트 3.9.55 이하에 사용됩니다.

[cols="2*"]
|===
| 엔드포인트 | 목적 


 a| 
\ https://support.netapp.com \ https://mysupport.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보냅니다.



 a| 
\https://\*.api.bluexp.netapp.com \ https://api.bluexp.netapp.com \https://*.cloudmanager.cloud.netapp.com \ https://cloudmanager.cloud.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com
| NetApp Console 내에서 기능과 서비스를 제공합니다. 


 a| 
두 가지 엔드포인트 세트 중에서 선택하세요.

* 옵션 1(권장)
+
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io

* 옵션 2
+
\https://*.blob.core.windows.net \ https://cloudmanagerinfraprod.azurecr.io


 a| 
콘솔 에이전트 업그레이드를 위한 이미지를 얻으려면.

NetApp 랜섬웨어 복원력이나 백업 및 복구를 사용하지 않는 한, 보안이 더 뛰어난 옵션 1 엔드포인트를 방화벽에서 허용하고 옵션 2 엔드포인트는 허용하지 않을 것을 권장합니다.  이러한 종료점에 대해 다음 사항을 참고하세요.

* 옵션 1 엔드포인트는 3.9.47 이상에서 지원됩니다.  3.9.47 이전 릴리스에서는 이전 버전과의 호환성이 지원되지 않습니다.
* 콘솔 에이전트는 먼저 옵션 2의 엔드포인트와 접촉을 시작합니다.  해당 엔드포인트에 접근할 수 없는 경우 옵션 1의 엔드포인트에 자동으로 접속합니다.
* NetApp Backup and Recovery 또는 Ransomware Resilience와 함께 콘솔 에이전트를 사용하는 경우 시스템은 옵션 1 엔드포인트를 지원하지 않습니다.  옵션 2 엔드포인트를 허용하고 옵션 1을 허용하지 않습니다.


|===


== 콘솔 에이전트가 연락한 클라우드 공급자 엔드포인트

콘솔 에이전트가 클라우드 공급자에 배포된 경우 추가 엔드포인트에 액세스할 수 있어야 합니다.

콘솔 에이전트를 설치하기 전에 클라우드 공급자 엔드포인트에 대한 액세스를 활성화하세요.

* link:task-install-agent-aws-console.html#networking-aws-agent["콘솔 에이전트에 대한 AWS 네트워크 액세스 설정"]
* link:task-install-agent-azure-console.html#networking-azure-agent["콘솔 에이전트에 대한 Azure 네트워크 액세스 설정"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["콘솔 에이전트에 대한 Google Cloud 네트워크 액세스 설정"]


클라우드 공급자 엔드포인트는 모든 버전에서 동일합니다.



== 콘솔 에이전트가 접속한 데이터 서비스 엔드포인트

콘솔 에이전트는 일부 NetApp 데이터 서비스와 Cloud Volumes ONTAP 지원하기 위해 추가적인 아웃바운드 인터넷 액세스가 필요합니다.



=== Cloud Volumes ONTAP 의 엔드포인트

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["AWS의 Cloud Volumes ONTAP 엔드포인트"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Azure의 Cloud Volumes ONTAP 엔드포인트"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Google Cloud의 Cloud Volumes ONTAP 엔드포인트"]

