---
sidebar: sidebar 
permalink: reference-agent-maint-console-config-checker.html 
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy. agent proxy 
summary: 콘솔 에이전트 유지 관리 콘솔을 사용하여 콘솔 에이전트가 투명 프록시 서버를 사용하도록 구성할 수 있습니다. 
---
= NetApp Console의 유지 관리 콘솔을 사용한 콘솔 에이전트 유효성 검사
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
콘솔 에이전트 유지 관리 콘솔을 사용하여 콘솔 에이전트의 설치 및 구성을 검증할 수 있습니다.



== 에이전트 유지 관리 콘솔에 액세스하세요

콘솔 에이전트 호스트에서 유지 관리 콘솔에 액세스할 수 있습니다.  다음 디렉토리로 이동하세요:

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


== 설정 검사기 유효성 검사

그만큼 `config-checker validate` 이 명령어를 사용하면 콘솔 에이전트의 구성을 검증할 수 있습니다.



=== 매개변수

`--services <comma-separated list of services to validate>`--*필수의*--

[role="quick-margin-para"]
검증할 서비스를 하나 이상 선택하십시오. 유효한 서비스 이름은 다음과 같습니다.

*`PLATFORM`이는 필요한 NetApp Console 엔드포인트에 대한 네트워크 연결 상태와 NetApp Console 에이전트에 필요한 포트가 열려 있는지 여부를 검증합니다.

`--validationTypes <comma-separated list validation types to run>` --*REQUIRED*-- 실행할 유효성 검사 유형을 하나 이상 선택하세요. 유효한 유효성 검사 유형은 다음과 같습니다.

* `NETWORK` 필수 NetApp Console 엔드포인트에 대한 네트워크 연결을 검증합니다.
* `HARDWARE` 에이전트 호스트가 Console 에이전트의 최소 하드웨어 요구 사항을 충족하는지 확인합니다.
+

NOTE: 설치 과정에서 NetApp은 에이전트 호스트에 전체 디스크 공간의 최소 80%가 사용 가능한지 확인합니다. 여기에는 `/opt`에 48GB와 `/var`에 32GB(총 80GB)가 포함됩니다. 설치 후에는 전체 디스크 공간의 최소 20%가 사용 가능한 상태로 유지되어야 하며, 여기에는 `/opt`에 12GB와 `/var`에 8GB(총 20GB)가 포함됩니다.



`--proxy <url>`--*선택 과목*--

[role="quick-margin-para"]
유효성 검사에 사용할 프록시 서버 URL을 지정합니다.  에이전트가 프록시 서버를 사용하도록 구성된 경우 필수입니다.

`--certs <paths>`--*선택 과목*--

[role="quick-margin-para"]
유효성 검사에 사용할 하나 이상의 인증서 파일의 경로를 지정합니다.  인증서 파일은 PEM 형식이어야 합니다.  여러 경로를 쉼표로 구분하세요.  에이전트에서 사용자 지정 인증서를 사용하는 경우 이 매개변수가 필수입니다.



=== 설정 검사기 유효성 검사 예제

다음 예시에는 네트워크 연결, 필수 포트 및 하드웨어 요구 사항 검증은 물론 프록시 서버와 사용자 지정 인증서의 다양한 조합 사용 사례가 포함됩니다.

.네트워크 연결 및 하드웨어 요구 사항에 대한 검증:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----
.에이전트에 프록시 서버가 사용되는 경우의 유효성 검사:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----
.에이전트에 인증서가 사용되는 유효성 검사:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


=== 모든 명령에 대한 도움말 보기

모든 명령에 대한 도움말을 보려면 다음을 추가하세요. `--help` 명령에.  예를 들어, 도움말을 보려면 `proxy add` 명령을 사용하려면 다음 명령을 사용하세요.

[source, cli]
----
./agent-maint-console proxy add --help
----