---
sidebar: sidebar 
permalink: reference-iam-keystone-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: NetApp 콘솔 ID 및 액세스 관리에서는 조직 구성원에게 할당할 수 있는 두 가지 Keystone 역할을 제공합니다. 
---
= NetApp 콘솔의 Keystone 액세스 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone 역할은 Keystone 대시보드에 대한 액세스를 제공하고 사용자가 Keystone 구독을 보고 관리할 수 있도록 합니다.  Keystone 역할에는 Keystone 관리자와 Keystone 뷰어라는 두 가지가 있습니다.  두 역할의 주요 차이점은 Keystone 에서 수행할 수 있는 작업입니다.  Keystone 관리자 역할은 서비스 요청을 만들거나 구독을 수정할 수 있는 유일한 역할입니다.

.NetApp 콘솔의 Keystone 역할에 대한 예
XYZ Corporation에는 Keystone 구독 정보를 확인하는 여러 부서의 스토리지 엔지니어가 4명 있습니다.  이러한 모든 사용자는 Keystone 구독을 모니터링해야 하지만, 서비스 요청을 할 수 있는 사람은 팀 리더뿐입니다.  팀원 3명에게는 * Keystone 뷰어* 역할이 부여되고, 팀 리더에게는 * Keystone 관리자* 역할이 부여되어 회사의 서비스 요청에 대한 통제 지점이 마련됩니다.

다음 표는 각 Keystone 역할이 수행할 수 있는 작업을 나타냅니다.

[cols="40,20a,20a"]
|===
| 특징과 동작 | Keystone 관리자 | Keystone 뷰어 


| 다음 탭을 확인하세요: 구독, 자산, 모니터 및 관리  a| 
예
 a| 
예



3+| * Keystone 구독 페이지*: 


| 구독 보기  a| 
예
 a| 
예



| 구독 수정 또는 갱신  a| 
예
 a| 
아니요



3+| * Keystone 자산 페이지*: 


| 자산 보기  a| 
예
 a| 
예



| 자산 관리  a| 
예
 a| 
아니요



3+| * Keystone 알림 페이지*: 


| 알림 보기  a| 
예
 a| 
예



| 알림 관리  a| 
예
 a| 
아니요



| 나 자신에 대한 알림 만들기  a| 
예
 a| 
예



3+| *라이센스 및 구독*: 


| 라이센스 및 구독을 볼 수 있습니다  a| 
예
 a| 
예



3+| * Keystone 보고서 페이지*: 


| 보고서 다운로드  a| 
예
 a| 
예



| 보고서 관리  a| 
예
 a| 
예



| 자신을 위한 보고서 만들기  a| 
예
 a| 
예



3+| *서비스 요청*: 


| 서비스 요청 생성  a| 
예
 a| 
아니요



| 조직 내 모든 사용자가 생성한 서비스 요청 보기  a| 
예
 a| 
예

|===