---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, https tokens, agents should remain running, Console agent 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요. 
---
= NetApp 콘솔의 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요.

이러한 제한 사항은 NEtApp 콘솔 및 관리(에이전트, SaaS(Software as a Service) 플랫폼 등) 설정과 관련된 것입니다.



== 콘솔 에이전트 제한 사항



=== 172 범위의 IP 주소와 충돌이 발생할 수 있습니다.

NetApp 콘솔은 172.17.0.0/16 및 172.18.0.0/16 범위의 IP 주소를 갖는 두 개의 인터페이스가 있는 에이전트를 배포합니다.

네트워크에 이러한 범위 중 하나로 구성된 서브넷이 있는 경우 콘솔에서 연결 오류가 발생할 수 있습니다.  예를 들어, 콘솔에서 온프레미스 ONTAP 클러스터를 검색하는 데 실패할 수 있습니다.

지식 기반 문서 참조link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["에이전트 IP가 기존 네트워크와 충돌합니다."] 에이전트 인터페이스의 IP 주소를 변경하는 방법에 대한 지침입니다.



=== SSL 복호화가 지원되지 않습니다.

콘솔은 SSL 복호화가 활성화된 방화벽 구성을 지원하지 않습니다.  SSL 복호화가 활성화된 경우 콘솔에 오류 메시지가 나타나고 에이전트 인스턴스가 비활성으로 표시됩니다.

보안을 강화하려면 다음 옵션을 선택하세요.link:task-installing-https-cert.html["인증 기관(CA)이 서명한 HTTPS 인증서를 설치합니다."] .



=== 로컬 UI를 로드할 때 빈 페이지가 나타납니다.

에이전트에서 실행 중인 웹 기반 콘솔을 로드하면 인터페이스가 표시되지 않고 빈 페이지만 나타나는 경우가 있습니다.

이 문제는 캐싱 문제와 관련이 있습니다.  해결 방법은 시크릿 모드나 개인 웹 브라우저 세션을 사용하는 것입니다.



=== 공유 Linux 호스트는 지원되지 않습니다.

에이전트는 다른 애플리케이션과 공유되는 VM에서는 지원되지 않습니다.  VM은 에이전트 소프트웨어에 전용되어야 합니다.



=== 제3자 에이전트 및 확장 프로그램

에이전트 VM에서는 타사 에이전트나 VM 확장이 지원되지 않습니다.
