---
sidebar: sidebar 
permalink: reference-ports-gcp.html 
keywords: ports, firewall rules, http, https, inbound, outbound, connector, agent 
summary: 에이전트에 대한 Google Cloud 방화벽 규칙에는 인바운드 규칙과 아웃바운드 규칙이 모두 필요합니다.  NetApp Console 에서 콘솔 에이전트를 만들면 이 보안 그룹이 자동으로 생성됩니다. 다른 설치 옵션의 경우 이 보안 그룹을 수동으로 설정해야 합니다. 
---
= Google Cloud의 에이전트 방화벽 규칙
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
에이전트에 대한 Google Cloud 방화벽 규칙에는 인바운드 규칙과 아웃바운드 규칙이 모두 필요합니다.  NetApp Console 에서 콘솔 에이전트를 만들면 이 보안 그룹이 자동으로 생성됩니다. 다른 설치 옵션의 경우 이 보안 그룹을 수동으로 설정해야 합니다.



== 인바운드 규칙

[cols="10,10,80"]
|===
| 규약 | 포트 | 목적 


| SSH | 22 | 에이전트 호스트에 SSH 액세스를 제공합니다. 


| HTTP | 80  a| 
* 클라이언트 웹 브라우저에서 로컬 사용자 인터페이스로 HTTP 액세스를 제공합니다.
* Cloud Volumes ONTAP 업그레이드 프로세스 중에 사용됨




| HTTPS | 443 | 클라이언트 웹 브라우저에서 로컬 사용자 인터페이스로 HTTPS 액세스를 제공합니다. 


| TCP | 3128 | Cloud Volumes ONTAP 에 인터넷 접속을 제공합니다.  배포 후에는 수동으로 이 포트를 열어야 합니다. 
|===


== 아웃바운드 규칙

에이전트의 사전 정의된 방화벽 규칙은 모든 아웃바운드 트래픽을 개방합니다.  허용되는 경우 기본 아웃바운드 규칙을 따르고, 더 엄격한 요구 사항이 있는 경우 고급 아웃바운드 규칙을 사용하세요.



=== 기본 아웃바운드 규칙

에이전트에 대한 미리 정의된 방화벽 규칙에는 다음과 같은 아웃바운드 규칙이 포함됩니다.

[cols="20,20,60"]
|===
| 규약 | 포트 | 목적 


| 모든 TCP | 모두 | 모든 아웃바운드 트래픽 


| 모든 UDP | 모두 | 모든 아웃바운드 트래픽 
|===


=== 고급 아웃바운드 규칙

아웃바운드 트래픽에 대한 엄격한 규칙이 필요한 경우 다음 정보를 사용하여 에이전트의 아웃바운드 통신에 필요한 포트만 열 수 있습니다.


NOTE: 소스 IP 주소는 에이전트 호스트입니다.

[cols="5*"]
|===
| 서비스 | 규약 | 포트 | 목적지 | 목적 


| API 호출 및 AutoSupport | HTTPS | 443 | 아웃바운드 인터넷 및 ONTAP 클러스터 관리 LIF | Google Cloud, ONTAP, NetApp Data Classification 대한 API 호출 및 NetApp 에 ​​대한 AutoSupport 메시지 전송 


| API 호출 | TCP | 8080 | 데이터 분류 | 배포 중 데이터 분류 인스턴스에 대한 프로브 


| DNS | UDP | 53 | DNS | 데이터 분류에 의한 DNS 확인에 사용됨 
|===