---
sidebar: sidebar 
permalink: reference-iam-storage-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: NetApp Console 에서 스토리지 관리 기능에 액세스할 수 있도록 사용자에게 다음 역할을 할당할 수 있습니다.  사용자에게 저장소를 관리하는 관리자 역할이나 모니터링을 위한 뷰어 역할을 할당할 수 있습니다. 
---
= NetApp Console 의 스토리지 액세스 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 에서 스토리지 관리 기능에 액세스할 수 있도록 사용자에게 다음 역할을 할당할 수 있습니다.  사용자에게 저장소를 관리하는 관리자 역할이나 모니터링을 위한 뷰어 역할을 할당할 수 있습니다.


NOTE: 이러한 역할은 NetApp Console 파트너십 API에서 사용할 수 없습니다.

관리자는 다음과 같은 스토리지 리소스 및 기능에 대해 사용자에게 스토리지 역할을 할당할 수 있습니다.

저장 리소스:

* 온프레미스 ONTAP 클러스터
* StorageGRID
* E-시리즈


콘솔 서비스 및 기능:

* 디지털 어드바이저
* 소프트웨어 업데이트
* 수명주기 계획
* 지속 가능성


.NetApp Console 의 스토리지 역할에 대한 예
다국적 기업인 XYZ Corporation은 스토리지 엔지니어와 스토리지 관리자로 구성된 대규모 팀을 보유하고 있습니다.  이를 통해 팀은 사용자 관리, 에이전트 생성, 라이선스 관리와 같은 핵심 콘솔 작업에 대한 액세스를 제한하는 동시에 해당 지역의 스토리지 자산을 관리할 수 있습니다.

12명으로 구성된 팀 내에서 두 명의 사용자에게 *저장소 뷰어* 역할이 부여됩니다. 이 역할을 통해 이들은 할당된 콘솔 프로젝트와 연관된 저장 리소스를 모니터링할 수 있습니다.  나머지 9명에게는 소프트웨어 업데이트를 관리하고, 콘솔을 통해 ONTAP 시스템 관리자에 액세스하고, 스토리지 리소스를 검색(시스템 추가)하는 기능이 포함된 *스토리지 관리자* 역할이 부여됩니다.  팀 내 한 사람에게 *시스템 상태 전문가* 역할이 부여되어 해당 지역의 스토리지 리소스 상태를 관리할 수 있지만, 시스템을 수정하거나 삭제할 수는 없습니다.  이 사람은 자신에게 할당된 프로젝트의 스토리지 리소스에 대한 소프트웨어 업데이트도 수행할 수 있습니다.

조직에는 사용자 관리, 에이전트 생성, 라이선스 관리를 포함하여 콘솔의 모든 측면을 관리할 수 있는 *조직 관리자* 역할이 있는 두 명의 추가 사용자가 있으며, 할당된 폴더와 프로젝트에 대한 콘솔 관리 작업을 수행할 수 있는 *폴더 또는 프로젝트 관리자* 역할이 있는 여러 사용자가 있습니다.

다음 표는 각 저장소 역할이 수행하는 작업을 보여줍니다.

[cols="40,20a,20a,20a"]
|===
| 특징과 동작 | 스토리지 관리자 | 시스템 건강 전문가 | 스토리지 뷰어 


4+| *저장 관리*: 


| 새로운 리소스 발견(시스템 생성)  a| 
예
 a| 
예
 a| 
아니요



| 발견된 시스템 보기  a| 
예
 a| 
예
 a| 
아니요



| 콘솔에서 시스템 삭제  a| 
예
 a| 
아니요
 a| 
아니요



| 시스템 수정  a| 
예
 a| 
아니요
 a| 
아니요



| *에이전트 생성*  a| 
아니요
 a| 
아니요
 a| 
아니요



4+| *디지털 어드바이저* 


| 모든 페이지 및 기능 보기  a| 
예
 a| 
예
 a| 
예



4+| * Licenses and subscriptions* 


| 모든 페이지 및 기능 보기  a| 
아니요
 a| 
아니요
 a| 
아니요



4+| *소프트웨어 업데이트* 


| 랜딩 페이지와 추천 보기  a| 
예
 a| 
예
 a| 
예



| 잠재적인 버전 권장 사항과 주요 이점을 검토하세요  a| 
예
 a| 
예
 a| 
예



| 클러스터에 대한 업데이트 세부 정보 보기  a| 
예
 a| 
예
 a| 
예



| 업데이트 전 점검을 실행하고 업그레이드 계획을 다운로드하세요  a| 
예
 a| 
예
 a| 
예



| 소프트웨어 업데이트 설치  a| 
예
 a| 
예
 a| 
아니요



4+| *수명주기 계획* 


| 용량 계획 상태 검토  a| 
예
 a| 
예
 a| 
예



| 다음 작업(모범 사례, 계층)을 선택하세요  a| 
예
 a| 
아니요
 a| 
아니요



| 콜드 데이터를 클라우드 스토리지로 계층화하고 스토리지를 확보하세요  a| 
예
 a| 
예
 a| 
아니요



| 알림 설정  a| 
예
 a| 
예
 a| 
예



4+| *지속가능성* 


| 대시보드 및 권장 사항 보기  a| 
예
 a| 
예
 a| 
예



| 보고서 데이터 다운로드  a| 
예
 a| 
예
 a| 
예



| 탄소 감축 비율 편집  a| 
예
 a| 
예
 a| 
아니요



| 권장 사항 수정  a| 
예
 a| 
예
 a| 
아니요



| 권장 사항을 연기하다  a| 
예
 a| 
예
 a| 
아니요



4+| *시스템 관리자 접근* 


| 자격 증명을 입력할 수 있습니다  a| 
예
 a| 
예
 a| 
아니요



4+| *신임장* 


| 사용자 자격 증명  a| 
예
 a| 
예
 a| 
아니요

|===