---
sidebar: sidebar 
permalink: reference-iam-data-classification.html 
keywords: role-based access control, IAM roles, access delegation, data classification, cloud data sense, compliance admin, classification viewer 
summary: NetApp Data Classification은 자산에 대한 읽기 및 쓰기 액세스를 관리하기 위한 두 가지 역할을 지원합니다. 
---
= NetApp Console의 NetApp Data Classification 역할
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification는 ID 및 액세스 관리(IAM) 역할을 지원하므로 사용자가 수행해야 하는 작업에 따라 액세스 권한을 맞춤 설정할 수 있습니다. 역할 할당 방법은 비즈니스 및 스토리지 관리 관행에 따라 달라집니다.

NetApp Data Classification은 두 가지 역할을 지원합니다.

* 규정 준수 관리자
* 분류 뷰어




[[compliance-admin]]
== 규정 준수 관리자

규정 준수 관리자 역할은 조직 수준에서만 NetApp Data Classification 리소스에 대한 액세스를 관리하는 데 사용됩니다. 조직 관리자보다 낮은 권한을 가진 사용자는 NetApp Data Classification을 설치하려면 규정 준수 관리자 역할을 보유해야 합니다.


IMPORTANT: 규정 준수 관리자 역할은 독립적인 역할이 아닙니다. 규정 준수 관리자 역할을 가진 사용자는 최소한 하나 이상의 link:reference-iam-platform-roles.html["플랫폼 역할"]와 연결되어 있어야 합니다.


NOTE: 규정 준수 관리자는 NetApp Data Classification 버전 1.54에 추가되었습니다. 이 릴리스 이전에 NetApp Data Classification을 배포했고 조직 관리자보다 액세스 권한이 낮은 플랫폼 역할을 보유하고 있는 경우, 규정 준수 관리자 역할이 사용자 계정에 자동으로 연결되었습니다.



[[classification-viewer]]
== 분류 뷰어

분류 뷰어는 Data Classification의 스캔 결과에는 액세스해야 하지만 구성 리소스에는 액세스할 필요가 없는 사용자를 위해 설계되었습니다. 분류 뷰어 역할을 가진 사용자는 매핑 및 전체 스캔 결과를 확인하여 스토리지 절약 영역 또는 잠재적인 데이터 위험을 평가할 수 있습니다. 분류 뷰어 역할을 가진 사용자는 액세스 권한이 있는 리소스에 대한 보고서를 생성할 수도 있습니다. 이러한 사용자는 볼륨, 버킷 또는 데이터베이스 스키마의 스캔을 활성화하거나 비활성화할 수 없습니다.



[[more-information]]
== 추가 정보

* link:https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["NetApp Data Classification에 대해 알아보세요"^]

