---
sidebar: sidebar 
permalink: reference-agent-default-config.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux, connector configuration, connector installation folder, connector folder, connector log, ubuntu, agent, agent installation folder, agent configuration 
summary: 배포하기 전에 콘솔 에이전트에 대해 자세히 알아보세요. 
---
= 콘솔 에이전트의 기본 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
배포하기 전에 콘솔 에이전트의 구성에 대해 자세히 알아보세요.



== 인터넷 접속이 가능한 기본 구성

다음 구성 세부 정보는 NetApp Console, 클라우드 공급업체의 마켓플레이스에서 콘솔 에이전트를 배포한 경우 또는 인터넷 액세스가 가능한 온프레미스 Linux 호스트에 콘솔 에이전트를 수동으로 설치한 경우에 적용됩니다.



=== AWS 세부 정보

콘솔이나 클라우드 공급자의 마켓플레이스에서 콘솔 에이전트를 배포한 경우 다음 사항에 유의하세요.

* EC2 인스턴스 유형은 t3.2xlarge입니다.
* 이미지의 운영 체제는 Ubuntu 22.04 LTS입니다.
+
운영 체제에는 GUI가 포함되어 있지 않습니다.  시스템에 접근하려면 터미널을 사용해야 합니다.

* 설치에는 컨테이너 오케스트레이션 도구인 Docker Engine이 포함되어 있습니다.
* EC2 Linux 인스턴스의 사용자 이름은 ubuntu입니다(2023년 5월 이전에 생성된 에이전트의 경우 사용자 이름은 ec2-user입니다).
* 기본 시스템 디스크는 100GiB gp2 디스크입니다.




=== Azure 세부 정보

콘솔이나 클라우드 공급자의 마켓플레이스에서 콘솔 에이전트를 배포한 경우 다음 사항에 유의하세요.

* VM 유형은 Standard_D8s_v3입니다.
* 이미지의 운영 체제는 Ubuntu 22.04 LTS입니다.
+
운영 체제에는 GUI가 포함되어 있지 않습니다.  시스템에 접근하려면 터미널을 사용해야 합니다.

* 설치에는 컨테이너 오케스트레이션 도구인 Docker Engine이 포함되어 있습니다.
* 기본 시스템 디스크는 100GiB 프리미엄 SSD 디스크입니다.




=== Google Cloud 세부 정보

콘솔에서 콘솔 에이전트를 배포한 경우 다음 사항에 유의하세요.

* VM 인스턴스는 n2-standard-8입니다.
* 이미지의 운영 체제는 Ubuntu 22.04 LTS입니다.
+
운영 체제에는 GUI가 포함되어 있지 않습니다.  시스템에 접근하려면 터미널을 사용해야 합니다.

* 설치에는 컨테이너 오케스트레이션 도구인 Docker Engine이 포함되어 있습니다.
* 기본 시스템 디스크는 100GiB SSD 영구 디스크입니다.




=== 설치 폴더

에이전트 설치 폴더는 다음 위치에 있습니다.

/opt/application/netapp/클라우드매니저



=== 로그 파일

로그 파일은 다음 폴더에 있습니다.

* /opt/application/netapp/cloudmanager/log 또는
* /opt/application/netapp/service-manager-2/logs(새로운 3.9.23 설치부터)
+
이러한 폴더의 로그는 콘솔 에이전트에 대한 세부 정보를 제공합니다.

* /opt/application/netapp/cloudmanager/docker_occm/데이터/로그
+
이 폴더의 로그는 클라우드 서비스와 콘솔 에이전트에서 실행되는 콘솔 서비스에 대한 세부 정보를 제공합니다.





=== 콘솔 에이전트 서비스

* 콘솔 에이전트 서비스의 이름은 occm입니다.
* occm 서비스는 MySQL 서비스에 종속됩니다.
+
MySQL 서비스가 중단되면 occm 서비스도 중단됩니다.





=== 포트

에이전트는 Linux 호스트에서 다음 포트를 사용합니다.

* HTTP 접근을 위한 80
* HTTPS 액세스를 위한 443




== 인터넷 접속이 없는 기본 구성

인터넷 접속이 불가능한 온프레미스 Linux 호스트에 콘솔 에이전트를 수동으로 설치한 경우 다음 구성이 적용됩니다. link:task-quick-start-private-mode.html["이 설치 옵션에 대해 자세히 알아보세요"] .

* 에이전트 설치 폴더는 다음 위치에 있습니다.
+
/opt/application/netapp/ds

* 로그 파일은 다음 폴더에 있습니다.
+
/var/lib/docker/volumes/ds_occmdata/_data/log

+
이 폴더의 로그는 콘솔 에이전트와 Docker 이미지에 대한 세부 정보를 제공합니다.

* 모든 서비스는 Docker 컨테이너 내부에서 실행됩니다.
+
서비스는 실행 중인 Docker 런타임 서비스에 따라 달라집니다.

* 에이전트는 Linux 호스트에서 다음 포트를 사용합니다.
+
** HTTP 접근을 위한 80
** HTTPS 액세스를 위한 443



