---
sidebar: sidebar 
permalink: task-install-agent-google-console-gcloud.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, create connector, gcp installation, gcp connector 
summary: NetApp Console 또는 Google Cloud를 사용하여 Google Cloud에 Console 에이전트를 생성하려면 네트워킹을 설정하고, Google Cloud 권한을 준비하고, Google Cloud API를 활성화한 다음 Console 에이전트를 생성해야 합니다. 
---
= NetApp Console에서 Google Cloud에 Console 에이전트 배포
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Console에서 Google Cloud에 Console 에이전트를 배포할 수 있습니다. 네트워킹을 설정하고, Google Cloud 권한을 준비하고, Google Cloud API를 활성화한 다음 Console 에이전트를 배포해야 합니다.

Google Cloud에 에이전트를 배포하면 사용자가 선택한 VPC에서 Linux를 실행하는 VM 인스턴스와 Console 에이전트 소프트웨어가 시작됩니다.

.시작하기 전에
* link:concept-agent-install-options.html#agent-console-deploy["NetApp Console에서 배포해야 하는 시점을 알아보세요."].
* 검토해야 합니다link:reference-limitations.html["콘솔 에이전트 제한 사항"] .




[[step-1-set-up-networking]]
[[networking-gcp-agent]]
== 1단계: 네트워킹 설정

콘솔 에이전트가 대상 네트워크에 연결하고 아웃바운드 인터넷에 접속하여 리소스를 관리할 수 있도록 네트워킹을 설정합니다.

VPC 및 서브넷:: 콘솔 에이전트를 생성할 때는 에이전트가 상주해야 하는 VPC와 서브넷을 지정해야 합니다.


대상 네트워크에 대한 연결:: 콘솔 에이전트를 사용하려면 시스템을 만들고 관리하려는 위치에 대한 네트워크 연결이 필요합니다.  예를 들어, Cloud Volumes ONTAP 시스템이나 온프레미스 환경의 스토리지 시스템을 만들 계획인 네트워크입니다.


아웃바운드 인터넷 접속:: 콘솔 에이전트를 배포하는 네트워크 위치에는 특정 엔드포인트에 연결하기 위한 아웃바운드 인터넷 연결이 있어야 합니다.


콘솔 에이전트에서 연락한 엔드포인트:: 콘솔 에이전트는 일상 업무를 위해 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리하기 위해 다음 엔드포인트에 연결하기 위해 아웃바운드 인터넷 액세스가 필요합니다.
+
--
아래 나열된 엔드포인트는 모두 CNAME 항목입니다.

[cols="2a,1a"]
|===
| 엔드포인트 | 목적 


 a| 
https://www.googleapis.com/compute/v1/ https://compute.googleapis.com/compute/v1 https://cloudresourcemanager.googleapis.com/v1/projects https://www.googleapis.com/compute/beta https://storage.googleapis.com/storage/v1 https://www.googleapis.com/storage/v1 https://iam.googleapis.com/v1 https://cloudkms.googleapis.com/v1 https://config.googleapis.com/v1/projects
 a| 
Google Cloud에서 리소스를 관리합니다.



 a| 
\ https://mysupport.netapp.com
 a| 
라이선스 정보를 얻고 AutoSupport 메시지를 NetApp 지원팀에 보내려면 다음을 수행하십시오.



 a| 
\ https://signin.b2c.netapp.com
 a| 
NetApp 지원 사이트(NSS) 자격 증명을 업데이트하거나 NetApp Console 에 새로운 NSS 자격 증명을 추가합니다.



 a| 
\ https://support.netapp.com
 a| 
라이선스 정보를 얻고 AutoSupport 메시지를 NetApp Support로 전송하며 Cloud Volumes ONTAP의 소프트웨어 업데이트를 받기 위해서입니다.



 a| 
\https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com
 a| 
NetApp Console 내에서 기능과 서비스를 제공합니다.



 a| 
https://bluexpinfraprod.eastus2.data.azurecr.io https://bluexpinfraprod.azurecr.io https://occmclientinfragov.azurecr.us (제한된 모드 배포에 필요)
 a| 
콘솔 에이전트 업그레이드를 위한 이미지를 얻으려면.

|===
--


NetApp 콘솔에서 연결된 엔드포인트:: 웹 기반 NetApp Console SaaS 애플리케이션을 사용하면 데이터 관리 작업을 완료하기 위해 여러 엔드포인트에 연결합니다. 여기에는 Console에서 Console 에이전트를 배포하기 위해 연결하는 엔드포인트도 포함됩니다.
+
--
link:reference-networking-saas-console.html["NetApp Console에서 연결된 엔드포인트 목록을 확인하십시오"].

--


프록시 서버:: NetApp 명시적 프록시 구성과 투명 프록시 구성을 모두 지원합니다.  투명 프록시를 사용하는 경우 프록시 서버에 대한 인증서만 제공하면 됩니다.  명시적 프록시를 사용하는 경우 IP 주소와 자격 증명도 필요합니다.
+
--
* IP 주소
* 신임장
* HTTPS 인증서


--


포트:: Console 에이전트로 들어오는 트래픽은 사용자가 직접 시작하거나 Cloud Volumes ONTAP에서 NetApp Support로 AutoSupport 메시지를 보내기 위한 프록시로 사용되는 경우를 제외하고는 없습니다.
+
--
* HTTP(80) 및 HTTPS(443)는 로컬 UI에 대한 액세스를 제공하며 이는 드문 상황에서 사용됩니다.
* SSH(22)는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.
* 아웃바운드 인터넷 연결을 사용할 수 없는 서브넷에 Cloud Volumes ONTAP 시스템을 배포하는 경우 포트 3128을 통한 인바운드 연결이 필요합니다.
+
Cloud Volumes ONTAP 시스템에 AutoSupport 메시지를 보낼 아웃바운드 인터넷 연결이 없는 경우 콘솔은 콘솔 에이전트에 포함된 프록시 서버를 사용하도록 해당 시스템을 자동으로 구성합니다.  유일한 요구 사항은 콘솔 에이전트의 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는 것입니다.  콘솔 에이전트를 배포한 후 이 포트를 열어야 합니다.



--


NTP 활성화:: NetApp Data Classification을 사용하여 회사 데이터 소스를 스캔할 계획이라면 Console 에이전트와 NetApp Data Classification 시스템 모두에서 네트워크 시간 프로토콜(NTP) 서비스를 활성화하여 시스템 간 시간을 동기화해야 합니다 https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["NetApp Data Classification에 대해 자세히 알아보세요"^].
+
--
콘솔 에이전트를 만든 후 이 네트워킹 요구 사항을 구현합니다.

--




[[step-2-set-up-permissions-to-create-the-console-agent]]
[[agent-permissions-google]]
== 2단계: 콘솔 에이전트를 생성하기 위한 권한 설정

콘솔에서 콘솔 에이전트를 배포하려면 먼저 콘솔 에이전트 VM을 배포하는 Google 플랫폼 사용자의 권한을 설정해야 합니다.

.단계
. Google 플랫폼에서 사용자 지정 역할을 만듭니다.
+
.. 다음 권한을 포함하는 YAML 파일을 만듭니다.
+
[source, yaml]
----
title: Console agent deployment policy
description: Permissions for the user who deploys the Console agent
stage: GA
includedPermissions:

- cloudbuild.builds.get
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- config.deployments.create
- config.operations.get
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getState
- config.deployments.list
- config.deployments.update
- config.deployments.updateState
- config.previews.get
- config.previews.list
- config.revisions.get
- config.resources.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.buckets.create
- storage.buckets.get
- storage.objects.create
- storage.folders.create
- storage.objects.list

----
.. Google Cloud에서 Cloud Shell을 활성화합니다.
.. 필요한 권한이 포함된 YAML 파일을 업로드합니다.
.. 다음을 사용하여 사용자 정의 역할을 만듭니다. `gcloud iam roles create` 명령.
+
다음 예제는 프로젝트 수준에서 "agentDeployment"라는 이름의 역할을 생성합니다.

+
[source, shell]
----
gcloud iam roles create agentDeployment --project=myproject --file=agent-deployment.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud 문서: 사용자 지정 역할 만들기 및 관리"^]



. 콘솔이나 gcloud를 사용하여 콘솔 에이전트를 배포할 사용자에게 이 사용자 지정 역할을 할당합니다.
+
https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud 문서: 단일 역할 부여"^]





[[step-3-create-a-google-cloud-service-account-to-use-with-the-agent]]
[[console-permissions-google]]
== 3단계: 에이전트와 함께 사용할 Google Cloud 서비스 계정을 생성합니다.

Google Cloud 서비스 계정은 콘솔 에이전트에 Google Cloud의 리소스를 관리하는 데 필요한 권한을 제공하는 데 필요합니다.  콘솔 에이전트를 만들 때 이 서비스 계정을 콘솔 에이전트 VM과 연결해야 합니다.

이후 릴리스에서 새로운 권한이 추가되면 사용자 지정 역할을 업데이트하는 것은 사용자의 책임입니다.  새로운 권한이 필요한 경우 릴리스 노트에 나열됩니다.

.단계
. Google Cloud에서 사용자 지정 역할을 만듭니다.
+
.. 내용을 포함하는 YAML 파일을 만듭니다.link:reference-permissions-gcp.html["콘솔 에이전트에 대한 서비스 계정 권한"] .
.. Google Cloud에서 Cloud Shell을 활성화합니다.
.. 필요한 권한이 포함된 YAML 파일을 업로드합니다.
.. 다음을 사용하여 사용자 정의 역할을 만듭니다. `gcloud iam roles create` 명령.
+
다음 예제는 프로젝트 수준에서 "agent"라는 이름의 역할을 생성합니다.

+
[source, shell]
----
gcloud iam roles create agent --project=myproject --file=agent.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud 문서: 사용자 지정 역할 만들기 및 관리"^]



. Google Cloud에서 서비스 계정을 만들고 서비스 계정에 역할을 할당합니다.
+
.. IAM 및 관리 서비스에서 *서비스 계정 > 서비스 계정 만들기*를 선택합니다.
.. 서비스 계정 세부 정보를 입력하고 *만들기 및 계속*을 선택하세요.
.. 방금 만든 역할을 선택하세요.
.. 나머지 단계를 완료하여 서비스 계정을 생성합니다.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud 문서: 서비스 계정 만들기"^]



. Console 에이전트가 있는 프로젝트 이외의 다른 프로젝트에 Cloud Volumes ONTAP 시스템을 배포할 계획이라면 Console 에이전트의 서비스 계정에 해당 프로젝트에 대한 액세스 권한을 부여해야 합니다.
+
예를 들어, 콘솔 에이전트가 프로젝트 1에 있고 프로젝트 2에 Cloud Volumes ONTAP 시스템을 만들고 싶다고 가정해 보겠습니다.  프로젝트 2에서 서비스 계정에 대한 액세스 권한을 부여해야 합니다.

+
.. IAM 및 관리 서비스에서 Cloud Volumes ONTAP 시스템을 만들려는 Google Cloud 프로젝트를 선택합니다.
.. *IAM* 페이지에서 *액세스 권한 부여*를 선택하고 필요한 세부 정보를 제공합니다.
+
*** 콘솔 에이전트 서비스 계정의 이메일을 입력하세요.
*** 콘솔 에이전트의 사용자 지정 역할을 선택합니다.
*** *저장*을 선택하세요.




+
자세한 내용은 다음을 참조하세요. https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud 문서"^]





[[step-4-set-up-shared-vpc-permissions]]
== 4단계: 공유 VPC 권한 설정

공유 VPC를 사용하여 서비스 프로젝트에 리소스를 배포하는 경우 권한을 준비해야 합니다.

이 표는 참조용이며 IAM 구성이 완료되면 사용자 환경에 권한 표가 반영되어야 합니다.

.공유 VPC 권한 보기
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| 신원 | 창조자 | 호스팅됨 | 서비스 프로젝트 권한 | 호스트 프로젝트 권한 | 목적 


| 에이전트를 배포하기 위한 Google 계정 | 관습 | 봉사 프로젝트  a| 
link:task-install-agent-google-console-gcloud.html#agent-permissions-google["에이전트 배포 정책"]
 a| 
컴퓨팅.네트워크사용자
| 서비스 프로젝트에 에이전트 배포 


| 에이전트 서비스 계정 | 관습 | 봉사 프로젝트  a| 
link:reference-permissions-gcp.html["에이전트 서비스 계정 정책"]
| compute.networkUser 배포 관리자.편집기 | 서비스 프로젝트에서 Cloud Volumes ONTAP 및 서비스 배포 및 유지 관리 


| Cloud Volumes ONTAP 서비스 계정 | 관습 | 봉사 프로젝트 | storage.admin 멤버: NetApp Console 서비스 계정(serviceAccount.user) | 해당 없음 | (선택 사항) NetApp Cloud Tiering 및 NetApp Backup and Recovery 


| Google API 서비스 에이전트 | 구글 클라우드 | 봉사 프로젝트  a| 
(기본값) 편집기
 a| 
컴퓨팅.네트워크사용자
| 배포를 대신하여 Google Cloud API와 상호 작용합니다.  콘솔이 공유 네트워크를 사용할 수 있도록 합니다. 


| Google Compute Engine 기본 서비스 계정 | 구글 클라우드 | 봉사 프로젝트  a| 
(기본값) 편집기
 a| 
컴퓨팅.네트워크사용자
| 배포를 대신하여 Google Cloud 인스턴스와 컴퓨팅 인프라를 배포합니다.  콘솔이 공유 네트워크를 사용할 수 있도록 합니다. 
|===
참고사항:

. `deploymentmanager.editor`는 방화벽 규칙을 배포에 전달하지 않고 Console에서 직접 생성하도록 선택한 경우에만 호스트 프로젝트에서 필요합니다. 규칙이 지정되지 않은 경우 NetApp Console은 VPC0 방화벽 규칙이 포함된 배포를 호스트 프로젝트에 생성합니다.
. `firewall.create` 및  `firewall.delete`는 방화벽 규칙을 배포에 전달하지 않고 Console에서 직접 생성하도록 선택한 경우에만 필요합니다. 이러한 권한은 Console 계정 .yaml 파일에 있습니다. 공유 VPC를 사용하여 HA 쌍을 배포하는 경우 이러한 권한은 VPC1, 2 및 3에 대한 방화벽 규칙을 생성하는 데 사용됩니다. 다른 모든 배포의 경우 이러한 권한은 VPC0에 대한 규칙을 생성하는 데에도 사용됩니다.
. Cloud Tiering의 경우 티어링 서비스 계정에는 프로젝트 수준뿐만 아니라 서비스 계정에 대한 `serviceAccount.user` 역할이 있어야 합니다. 프로젝트 수준에서 `serviceAccount.user`를 할당하면 `getIAMPolicy`로 서비스 계정을 쿼리할 때 권한이 표시되지 않습니다.


====


[[step-5-enable-google-cloud-apis]]
== 5단계: Google Cloud API 활성화

콘솔 에이전트와 Cloud Volumes ONTAP 배포하기 전에 여러 Google Cloud API를 활성화해야 합니다.

.단계
. 프로젝트에서 다음 Google Cloud API를 활성화하세요.
+
** Cloud Build API(Infrastructure Manager를 사용하는 프라이빗 모드 Cloud Volumes ONTAP 배포에 필요)
** 클라우드 배포 관리자 V2 API
** 클라우드 인프라 관리자 API
** 클라우드 로깅 API
** 클라우드 리소스 관리자 API
** 컴퓨트 엔진 API
** ID 및 액세스 관리(IAM) API
** 클라우드 키 관리 서비스(KMS) API(NetApp Backup and Recovery를 고객 관리 암호화 키(CMEK)와 함께 사용하려는 경우에만 필요)
** Cloud Quotas API(Infrastructure Manager를 사용하는 Cloud Volumes ONTAP 배포에 필요)




https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloud 문서: API 활성화"^]



[[step-6-create-the-console-agent]]
== 6단계: 콘솔 에이전트 만들기

콘솔에서 직접 콘솔 에이전트를 만듭니다.

콘솔 에이전트를 생성하면 기본 구성을 사용하여 Google Cloud에 가상 머신 인스턴스가 배포됩니다.  콘솔 에이전트를 만든 후에는 CPU나 RAM이 적은 더 작은 VM 인스턴스로 전환하지 마세요. link:reference-agent-default-config.html["콘솔 에이전트의 기본 구성에 대해 알아보세요"] .


NOTE: Google Cloud에 에이전트를 배포하면 에이전트가 배포 파일을 저장할 버킷을 생성합니다.

.시작하기 전에
다음 사항이 있어야 합니다.

* 콘솔 에이전트와 콘솔 에이전트 VM에 대한 서비스 계정을 생성하는 데 필요한 Google Cloud 권한입니다.
* 네트워킹 요구 사항을 충족하는 VPC 및 서브넷.
* 콘솔 에이전트에서 인터넷에 접속하는 데 프록시가 필요한 경우 프록시 서버에 대한 세부 정보입니다.


.단계
. *관리 > 에이전트*를 선택하세요.
. *개요* 페이지에서 *에이전트 배포 > Google Cloud*를 선택합니다.
. *에이전트 배치* 페이지에서 필요한 사항에 대한 세부 정보를 검토하세요.  두 가지 옵션이 있습니다.
+
.. 제품 내 가이드를 사용하여 배포를 준비하려면 *계속*을 선택하세요.  제품 내 가이드의 각 단계에는 이 문서 페이지에 포함된 정보가 포함되어 있습니다.
.. 이 페이지의 단계에 따라 이미 준비가 되었다면 *배포로 건너뛰기*를 선택하세요.


. 마법사의 단계에 따라 콘솔 에이전트를 만듭니다.
+
** 메시지가 표시되면 가상 머신 인스턴스를 만드는 데 필요한 권한이 있는 Google 계정에 로그인하세요.
+
이 양식은 Google에서 소유하고 호스팅합니다.  귀하의 자격 증명은 NetApp 에 ​​제공되지 않습니다.

** *세부 정보*: 가상 머신 인스턴스의 이름을 입력하고, 태그를 지정하고, 프로젝트를 선택한 다음, 필요한 권한이 있는 서비스 계정을 선택합니다(자세한 내용은 위 섹션을 참조하세요).
** *위치*: 인스턴스에 대한 지역, 영역, VPC 및 서브넷을 지정합니다.
** *네트워크*: 공용 IP 주소를 사용할지 여부를 선택하고, 선택적으로 프록시 구성을 지정합니다.
** *네트워크 태그*: 투명 프록시를 사용하는 경우 Console 에이전트 인스턴스에 네트워크 태그를 추가합니다. 네트워크 태그는 소문자로 시작해야 하며 소문자, 숫자 및 하이픈을 포함할 수 있습니다. 태그는 소문자 또는 숫자로 끝나야 합니다. 예를 들어 `console-agent-proxy` 태그를 사용할 수 있습니다.
** *방화벽 정책*: 새 방화벽 정책을 생성할지, 아니면 필요한 인바운드 및 아웃바운드 규칙을 허용하는 기존 방화벽 정책을 선택할지 선택합니다.
+
link:reference-ports-gcp.html["Google Cloud의 방화벽 규칙"]



. 선택 사항을 검토하여 설정이 올바른지 확인하십시오.
+
.. *에이전트 구성 검증* 확인란은 배포 시 NetApp Console에서 네트워크 연결 요구 사항을 검증하도록 기본적으로 선택되어 있습니다. NetApp Console에서 에이전트 배포에 실패하면 문제 해결에 도움이 되는 보고서를 제공합니다. 배포가 성공하면 보고서는 제공되지 않습니다.


+
[NOTE]
====
** link:reference-networking-saas-console-previous.html["이전 종료점"]에이전트 업그레이드에 사용되는 방식을 계속 사용하는 경우 유효성 검사가 오류와 함께 실패합니다. 이를 방지하려면 확인란을 선택 해제하여 유효성 검사를 건너뜁니다.
** 설치 과정에서 NetApp은 에이전트 호스트에 전체 디스크 공간의 최소 80%가 사용 가능한지 확인합니다. 여기에는 `/opt`에 48GB와 `/var`에 32GB(총 80GB)가 포함됩니다. 설치 후에는 전체 디스크 공간의 최소 20%가 사용 가능한 상태로 유지되어야 하며, 여기에는 `/opt`에 12GB와 `/var`에 8GB(총 20GB)가 포함됩니다.


====
. *추가*를 선택하세요.
+
에이전트는 약 10분 안에 준비됩니다. 프로세스가 완료될 때까지 페이지에 머물러 주세요.



.결과
프로세스가 완료되면 콘솔 에이전트를 사용할 수 있습니다.


NOTE: 배포에 실패하면 콘솔에서 보고서와 로그를 다운로드하여 문제를 해결할 수 있습니다.link:task-troubleshoot-agent.html#troubleshoot-installation["설치 문제를 해결하는 방법을 알아보세요."]

Console 에이전트를 생성한 Google Cloud 계정에 Google Cloud Storage 버킷이 있는 경우 Google Cloud Storage 시스템이 *시스템* 페이지에 자동으로 나타납니다 https://docs.netapp.com/us-en/storage-management-google-cloud-storage/index.html["콘솔에서 Google Cloud Storage를 관리하는 방법을 알아보세요."^].
