---
sidebar: sidebar 
permalink: task-agent-vm-config.html 
keywords: agent VM, vcenter, esxi, increase cpu, increase ram, vm maintenance, agent maintenance, agent operating system, agent host 
summary: 콘솔 에이전트를 배포한 후 기존 VCenter 또는 ESXi 호스트를 변경할 수 있습니다.  예를 들어, 콘솔 에이전트를 호스팅하는 VM 인스턴스의 CPU나 RAM을 늘릴 수 있습니다. 
---
= 콘솔 에이전트에 대한 VCenter 또는 ESXi 호스트 유지 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
콘솔 에이전트를 배포한 후 기존 VCenter 또는 ESXi 호스트를 변경할 수 있습니다.  예를 들어, 콘솔 에이전트를 호스팅하는 VM 인스턴스의 CPU나 RAM을 늘릴 수 있습니다.

VM 웹 콘솔을 사용하여 다음 유지 관리 작업을 수행합니다.

* 디스크 크기 늘리기
* 에이전트를 다시 시작하세요
* 정적 경로 업데이트
* 검색 도메인 업데이트


.제한 사항
콘솔을 통해 에이전트를 업그레이드하는 기능은 아직 지원되지 않습니다.  또한 IP 주소, DNS, 게이트웨이에 대한 정보만 볼 수 있습니다.



== VM 유지 관리 콘솔에 액세스

VSphere 클라이언트에서 유지 관리 콘솔에 액세스할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. *웹 콘솔 실행*을 선택하세요.
. VM 인스턴스를 생성할 때 지정한 사용자 이름과 비밀번호를 사용하여 VM 인스턴스에 로그인합니다.  사용자 이름은 `maint` 비밀번호는 VM 인스턴스를 생성할 때 지정한 비밀번호입니다.




=== 메인트 사용자 비밀번호 변경

비밀번호를 변경할 수 있습니다. `maint` 사용자.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. *웹 콘솔 실행*을 선택하세요.
. VM 인스턴스를 생성할 때 지정한 사용자 이름과 비밀번호를 사용하여 VM 인스턴스에 로그인합니다.  사용자 이름은 `maint` 비밀번호는 VM 인스턴스를 생성할 때 지정한 비밀번호입니다.
. 입력하다 `1` 보려면 `System Configuration` 메뉴.
. 입력하다 `1` 유지 관리 사용자 비밀번호를 변경하고 화면의 지시를 따르세요.




=== VM 인스턴스의 CPU 또는 RAM을 늘리세요

콘솔 에이전트를 호스팅하는 VM 인스턴스의 CPU 또는 RAM을 늘릴 수 있습니다.

VCenter 또는 ESXi 호스트에서 VM 인스턴스 설정을 편집한 다음 유지 관리 콘솔을 사용하여 변경 사항을 적용합니다.

.VSphere 클라이언트의 단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. VM 인스턴스를 마우스 오른쪽 버튼으로 클릭하고 *설정 편집*을 선택합니다.
. /opt 또는 /var 파티션에 사용되는 하드 드라이브 공간을 늘립니다.
+
.. /opt에 사용되는 하드 드라이브 공간을 늘리려면 *하드 디스크 2*를 선택하세요.
.. /var에 사용되는 하드 드라이브 공간을 늘리려면 *하드 디스크 3*을 선택하세요.


. 변경 사항을 저장합니다.


.유지 관리 콘솔의 단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. *웹 콘솔 실행*을 선택하세요.
. VM 인스턴스를 생성할 때 지정한 사용자 이름과 비밀번호를 사용하여 VM 인스턴스에 로그인합니다.  사용자 이름은 `maint` 비밀번호는 VM 인스턴스를 생성할 때 지정한 비밀번호입니다.
. 입력하다 `1 to view the `System Configuration` 메뉴.
. 입력하다 `2` 화면의 지시를 따르세요.  콘솔은 새로운 설정을 스캔하고 파티션 크기를 늘립니다.




=== 에이전트 VM에 대한 네트워크 설정 보기

VSphere 클라이언트에서 에이전트 VM의 네트워크 설정을 보고 네트워크 문제를 확인하거나 해결합니다.  다음 네트워크 설정은 볼 수만 있고 업데이트할 수는 없습니다: IP 주소 및 DNS 세부 정보.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. *웹 콘솔 실행*을 선택하세요.
. VM 인스턴스를 생성할 때 지정한 사용자 이름과 비밀번호를 사용하여 VM 인스턴스에 로그인합니다.  사용자 이름은 `maint` 비밀번호는 VM 인스턴스를 생성할 때 지정한 비밀번호입니다.
. 입력하다 `2` 보려면 `Network Configuration` 메뉴.
. 1~6 사이의 숫자를 입력하면 해당 네트워크 설정을 볼 수 있습니다.




=== 에이전트 VM에 대한 정적 경로를 업데이트합니다.

필요에 따라 에이전트 VM에 대한 정적 경로를 추가, 업데이트 또는 제거합니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. *웹 콘솔 실행*을 선택하세요.
. VM 인스턴스를 생성할 때 지정한 사용자 이름과 비밀번호를 사용하여 VM 인스턴스에 로그인합니다.  사용자 이름은 `maint` 비밀번호는 VM 인스턴스를 생성할 때 지정한 비밀번호입니다.
. 입력하다 `2` 보려면 `Network Configuration` 메뉴.
. 입력하다 `7` 정적 경로를 업데이트하고 화면의 지시를 따르세요.
. Enter 키를 누르세요.
. 선택적으로 추가 변경을 할 수 있습니다.
. 입력하다 `9` 변경 사항을 커밋합니다.




=== 에이전트 VM에 대한 도메인 검색 설정 업데이트

에이전트 VM에 대한 검색 도메인 설정을 업데이트할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. *웹 콘솔 실행*을 선택하세요.
. VM 인스턴스를 생성할 때 지정한 사용자 이름과 비밀번호를 사용하여 VM 인스턴스에 로그인합니다.  사용자 이름은 `maint` 비밀번호는 VM 인스턴스를 생성할 때 지정한 비밀번호입니다.
. 입력하다 `2`` 보려면 `Network Configuration` 메뉴.
. 입력하다 `8` 도메인 검색 설정을 업데이트하고 화면의 지시를 따르세요.
. Enter 키를 누르세요.
. 선택적으로 추가 변경을 할 수 있습니다.
. 입력하다 `9` 변경 사항을 커밋합니다.




=== 에이전트 진단 도구에 액세스하세요

콘솔 에이전트의 문제를 해결하기 위해 진단 도구에 액세스합니다.  NetApp 지원팀에서 문제를 해결할 때 이를 요청할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. *웹 콘솔 실행*을 선택하세요.
. VM 인스턴스를 생성할 때 지정한 사용자 이름과 비밀번호를 사용하여 VM 인스턴스에 로그인합니다.  사용자 이름은 `maint` 비밀번호는 VM 인스턴스를 생성할 때 지정한 비밀번호입니다.
. 입력하다 `3` 지원 및 진단 메뉴를 보려면.
. 입력하다 `1` 진단 도구에 접근하고 화면의 지시를 따르세요.  + 예를 들어, 모든 에이전트 서비스가 실행 중인지 확인할 수 있습니다. link:task-troubleshoot-agent.html#check-agent-status["콘솔 에이전트 상태 확인"^] .




=== 원격으로 에이전트 진단 도구에 액세스하세요

Putty와 같은 도구를 사용하면 원격으로 진단 도구에 액세스할 수 있습니다.  일회용 비밀번호를 할당하여 에이전트 VM에 대한 SSH 액세스를 활성화합니다.

SSH 접속을 통해 복사 및 붙여넣기 같은 고급 터미널 기능을 사용할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 에이전트를 호스팅하는 VM 인스턴스를 선택합니다.
. *웹 콘솔 실행*을 선택하세요.
. VM 인스턴스를 생성할 때 지정한 사용자 이름과 비밀번호를 사용하여 VM 인스턴스에 로그인합니다.  사용자 이름은 `maint` 비밀번호는 VM 인스턴스를 생성할 때 지정한 비밀번호입니다.
. 입력하다 `3` 보려면 `Support and Diagnostics` 메뉴.
. 입력하다 `2` 진단 도구에 액세스하고 화면의 지시에 따라 24시간 후에 만료되는 일회용 비밀번호를 구성합니다.
. Putty와 같은 SSH 도구를 사용하여 사용자 이름을 사용하여 에이전트 VM에 연결합니다. `diag` 그리고 귀하가 구성한 일회용 비밀번호.

