---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: '콘솔에서 수행한 작업에 따라 ONTAP 자격 증명과 NetApp 지원 사이트(NSS) 자격 증명을 사용자 로그인과 연결했을 수 있습니다.  해당 자격 증명을 연결한 후에는 해당 자격 증명을 보고 관리할 수 있습니다.  예를 들어, 이러한 자격 증명의 비밀번호를 변경하는 경우 콘솔에서 비밀번호를 업데이트해야 합니다.' 
---
= NetApp 콘솔 로그인과 관련된 자격 증명 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
콘솔에서 수행한 작업에 따라 ONTAP 자격 증명과 NetApp 지원 사이트(NSS) 자격 증명을 사용자 로그인과 연결했을 수 있습니다.  해당 자격 증명을 연결한 후에는 해당 자격 증명을 보고 관리할 수 있습니다.  예를 들어, 이러한 자격 증명의 비밀번호를 변경하는 경우 콘솔에서 비밀번호를 업데이트해야 합니다.



== ONTAP 자격 증명

사용자는 콘솔에서 ONTAP 클러스터를 검색하려면 ONTAP 관리자 자격 증명이 필요합니다.  하지만 ONTAP 시스템 관리자 액세스는 콘솔 에이전트를 사용하는지 여부에 따라 달라집니다.

.콘솔 에이전트 없이
클러스터의 ONTAP 시스템 관리자에 액세스하려면 사용자에게 ONTAP 자격 증명을 입력하라는 메시지가 표시됩니다.  사용자는 이러한 자격 증명을 콘솔에 저장하도록 선택할 수 있으며, 그렇게 하면 매번 입력하라는 메시지가 표시되지 않습니다.  사용자 자격 증명은 해당 사용자에게만 표시되며 사용자 자격 증명 페이지에서 관리할 수 있습니다.

.콘솔 에이전트를 사용하여
기본적으로 사용자는 ONTAP 시스템 관리자에 액세스하기 위해 ONTAP 자격 증명을 입력하라는 메시지를 받지 않습니다.  하지만 콘솔 관리자(조직 관리자 역할 있음)는 사용자에게 ONTAP 자격 증명을 입력하라는 메시지를 표시하도록 콘솔을 구성할 수 있습니다.  이 설정을 활성화하면 사용자는 매번 ONTAP 자격 증명을 입력해야 합니다.

link:task-ontap-access-agent.html["자세히 알아보세요."^]



== NSS 자격 증명

NetApp 콘솔 로그인과 연결된 NSS 자격 증명을 통해 지원 등록, 사례 관리 및 Digital Advisor 에 액세스할 수 있습니다.

* *지원 > 리소스*에 액세스하여 지원에 등록하면 NSS 자격 증명을 로그인과 연결하라는 메시지가 표시됩니다.
+
이렇게 하면 귀하의 조직이나 계정이 지원을 위해 등록되고 지원 자격이 활성화됩니다.  귀하의 조직에서 단 한 명의 사용자만이 NetApp 지원 사이트 계정을 로그인과 연결하여 지원을 등록하고 지원 자격을 활성화해야 합니다.  이 작업이 완료되면 *리소스* 페이지에 귀하의 계정이 지원을 위해 등록되었다는 메시지가 표시됩니다.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["지원 등록 방법 알아보기"^]

* *관리 > 지원 > 사례 관리*에 액세스하면 NSS 자격 증명을 입력하라는 메시지가 표시됩니다(아직 입력하지 않은 경우).  이 페이지에서는 NSS 계정과 회사와 관련된 지원 사례를 만들고 관리할 수 있습니다.
* 콘솔에서 Digital Advisor 에 액세스하면 NSS 자격 증명을 입력하여 Digital Advisor 에 로그인하라는 메시지가 표시됩니다.


로그인과 관련된 NSS 계정에 대해 다음 사항을 참고하세요.

* 계정은 사용자 수준에서 관리되므로 로그인하는 다른 사용자는 계정을 볼 수 없습니다.
* 사용자당 Digital Advisor 및 지원 사례 관리와 연결된 NSS 계정은 하나만 있을 수 있습니다.
* NetApp 지원 사이트 계정을 Cloud Volumes ONTAP 시스템과 연결하려는 경우, 본인이 소속된 조직에 추가된 NSS 계정에서만 선택할 수 있습니다.
+
NSS 계정 수준 자격 증명은 로그인과 연결된 NSS 계정과 다릅니다.  NSS 계정 수준 자격 증명을 사용하면 BYOL로 Cloud Volumes ONTAP 배포하고, PAYGO 시스템을 등록하고, 소프트웨어를 업그레이드할 수 있습니다.

+
link:task-adding-nss-accounts.html["NetApp 콘솔 조직 또는 계정에서 NSS 자격 증명을 사용하는 방법에 대해 자세히 알아보세요."] .





== 사용자 자격 증명을 관리하세요

사용자 이름과 비밀번호를 업데이트하거나 자격 증명을 삭제하여 사용자 자격 증명을 관리하세요.

.단계
. *관리 > 자격 증명*을 선택합니다.
. *사용자 자격 증명*을 선택하세요.
. 아직 사용자 자격 증명이 없으면 *NSS 자격 증명 추가*를 선택하여 NetApp 지원 사이트 계정을 추가할 수 있습니다.
. 다음 옵션을 작업 메뉴에서 선택하여 기존 자격 증명을 관리하세요.
+
** *자격 증명 업데이트*: 계정의 사용자 이름과 비밀번호를 업데이트합니다.
** *자격 증명 삭제*: 콘솔 로그인과 연결된 NSS 계정을 제거합니다.



