---
sidebar: sidebar 
permalink: task-configuring-proxy.html 
keywords: proxy, proxy server, proxy, internet, HTTP, http, https, bluexp 
summary: 회사 정책에 따라 모든 인터넷 통신에 프록시 서버를 사용해야 하는 경우 해당 프록시 서버를 사용하도록 에이전트를 구성해야 합니다.  설치 중에 콘솔 에이전트가 프록시 서버를 사용하도록 구성하지 않은 경우 언제든지 콘솔 에이전트가 해당 프록시 서버를 사용하도록 구성할 수 있습니다. 
---
= 프록시 서버를 사용하도록 콘솔 에이전트 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
회사 정책에 따라 모든 인터넷 통신에 프록시 서버를 사용해야 하는 경우 해당 프록시 서버를 사용하도록 에이전트를 구성해야 합니다.  설치 중에 콘솔 에이전트가 프록시 서버를 사용하도록 구성하지 않은 경우 언제든지 콘솔 에이전트가 해당 프록시 서버를 사용하도록 구성할 수 있습니다.

에이전트의 프록시 서버는 공용 IP나 NAT 게이트웨이 없이도 아웃바운드 인터넷 액세스를 가능하게 합니다.  프록시 서버는 Cloud Volumes ONTAP 시스템이 아닌 콘솔 에이전트에 대한 아웃바운드 연결만 제공합니다.

Cloud Volumes ONTAP 시스템에 아웃바운드 인터넷 액세스가 불가능한 경우 콘솔은 콘솔 에이전트의 프록시 서버를 사용하도록 구성합니다.  콘솔 에이전트의 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는지 확인해야 합니다.  콘솔 에이전트를 배포한 후 이 포트를 엽니다.

콘솔 에이전트 자체에 아웃바운드 인터넷 연결이 없으면 Cloud Volumes ONTAP 시스템은 구성된 프록시 서버를 사용할 수 없습니다.



== 지원되는 구성

* Cloud Volumes ONTAP 시스템을 서비스하는 에이전트의 경우 투명 프록시 서버가 지원됩니다.  Cloud Volumes ONTAP 과 함께 NetApp 데이터 서비스를 사용하는 경우 투명 프록시 서버를 사용할 수 있는 Cloud Volumes ONTAP 용 전용 에이전트를 만듭니다.
* 명시적 프록시 서버는 Cloud Volumes ONTAP 시스템을 관리하는 에이전트와 NetApp 데이터 서비스를 관리하는 에이전트를 포함한 모든 에이전트에서 지원됩니다.
* HTTP와 HTTPS.
* 프록시 서버는 클라우드나 네트워크에 있을 수 있습니다.



IMPORTANT: 프록시를 구성한 후에는 프록시 유형을 변경할 수 없습니다.  프록시 유형을 변경해야 하는 경우 콘솔 에이전트를 제거하고 새 프록시 유형을 사용하여 새 에이전트를 추가합니다.



== 콘솔 에이전트에서 명시적 프록시 활성화

콘솔 에이전트가 프록시 서버를 사용하도록 구성하면 해당 에이전트와 해당 에이전트가 관리하는 Cloud Volumes ONTAP 시스템(HA 중재자 포함)은 모두 프록시 서버를 사용합니다.

이 작업을 수행하면 콘솔 에이전트가 다시 시작됩니다.  계속하기 전에 콘솔 에이전트가 유휴 상태인지 확인하세요.

.단계
. *관리 > 에이전트*를 선택하세요.
. *개요* 페이지에서 콘솔 에이전트의 작업 메뉴를 선택하고 *에이전트 편집*을 선택합니다.
+
편집하려면 콘솔 에이전트가 활성화되어 있어야 합니다.

. *HTTP 프록시 구성*을 선택하세요.
. 구성 유형 필드에서 *명시적 프록시*를 선택합니다.
. *프록시 사용*을 선택하세요.
. 구문을 사용하여 서버를 지정하세요 http://_address:port_[] 또는 https://_address:port_[]
. 서버에 기본 인증이 필요한 경우 사용자 이름과 비밀번호를 지정하세요.
+
다음 사항에 유의하세요.

+
** 사용자는 로컬 사용자 또는 도메인 사용자일 수 있습니다.
** 도메인 사용자의 경우 \에 대한 ASCII 코드를 다음과 같이 입력해야 합니다. domain-name%92user-name
+
예: netapp%92proxy

** 콘솔은 @ 문자가 포함된 비밀번호를 지원하지 않습니다.


. *저장*을 선택하세요.




== 콘솔 에이전트에 투명 프록시 활성화

Cloud Volumes ONTAP 만이 콘솔 에이전트에서 투명 프록시 사용을 지원합니다.  Cloud Volumes ONTAP 외에 NetApp 데이터 서비스를 사용하는 경우 데이터 서비스나 Cloud Volumes ONTAP 에 사용할 별도의 에이전트를 만들어야 합니다.

투명 프록시를 활성화하기 전에 다음 요구 사항을 충족하는지 확인하세요.

* 에이전트는 투명 프록시 서버와 동일한 네트워크에 설치됩니다.
* 프록시 서버에서 TLS 검사가 활성화되어 있습니다.
* 투명 프록시 서버에서 사용되는 인증서와 일치하는 PEM 형식의 인증서가 있습니다.
* Cloud Volumes ONTAP 이외의 NetApp 데이터 서비스에는 콘솔 에이전트를 사용하지 마세요.


기존 에이전트가 투명 프록시 서버를 사용하도록 구성하려면 콘솔 에이전트 호스트의 명령줄을 통해 사용할 수 있는 콘솔 에이전트 유지 관리 도구를 사용합니다.

프록시 서버를 구성하면 콘솔 에이전트가 다시 시작됩니다.  계속하기 전에 콘솔 에이전트가 유휴 상태인지 확인하세요.

.단계
프록시 서버에 대한 PEM 형식의 인증서 파일이 있는지 확인하세요.  인증서가 없으면 네트워크 관리자에게 문의하여 인증서를 받으세요.

. 콘솔 에이전트 호스트에서 명령줄 인터페이스를 엽니다.
. 콘솔 에이전트 유지 관리 도구 디렉토리로 이동합니다. `/opt/application/netapp/service-manager-2/agent-maint-console`
. 투명 프록시를 활성화하려면 다음 명령을 실행하세요. `/home/ubuntu/<certificate-file>.pem` 프록시 서버에 대한 디렉토리 및 이름 인증서 파일입니다.
+
[source, CLI]
----
./agent-maint-console proxy add -c /home/ubuntu/<certificate-file>.pem
----
+
인증서 파일이 PEM 형식이고 명령과 같은 디렉토리에 있는지 확인하거나 인증서 파일의 전체 경로를 지정하세요.

+
[source, CLI]
----
./agent-maint-console proxy add -c /home/ubuntu/<certificate-file>.pem
----




=== 콘솔 에이전트에 대한 투명 프록시 수정

다음을 사용하여 콘솔 에이전트의 기존 투명 프록시 서버를 업데이트할 수 있습니다. `proxy update` 투명 프록시 서버를 명령하거나 제거하려면 다음을 사용하십시오. `proxy remove` 명령. 자세한 내용은 다음 문서를 검토하세요.link:reference-agent-maint-console.html["에이전트 유지 관리 콘솔"] .


IMPORTANT: 프록시를 구성한 후에는 프록시 유형을 변경할 수 없습니다.  프록시 유형을 변경해야 하는 경우 콘솔 에이전트를 제거하고 새 프록시 유형을 사용하여 새 에이전트를 추가합니다.



== 인터넷에 액세스할 수 없게 되면 콘솔 에이전트 프록시를 업데이트합니다.

네트워크의 프록시 구성이 변경되면 에이전트가 인터넷에 액세스할 수 없게 될 수 있습니다.  예를 들어, 누군가가 프록시 서버의 비밀번호를 변경하거나 인증서를 업데이트하는 경우입니다.  이 경우 콘솔 에이전트 호스트에서 직접 UI에 액세스하여 설정을 업데이트해야 합니다.  콘솔 에이전트 호스트에 대한 네트워크 액세스가 가능하고 콘솔에 로그인할 수 있는지 확인하세요.



== 직접 API 트래픽 활성화

프록시 서버를 사용하도록 콘솔 에이전트를 구성한 경우 프록시를 거치지 않고 클라우드 공급자 서비스로 API 호출을 직접 보내기 위해 콘솔 에이전트에서 직접 API 트래픽을 활성화할 수 있습니다. AWS, Azure 또는 Google Cloud에서 실행되는 에이전트는 이 옵션을 지원합니다.

Cloud Volumes ONTAP 사용하여 Azure Private Links를 비활성화하고 서비스 엔드포인트를 사용하는 경우 직접 API 트래픽을 활성화합니다.  그렇지 않으면 트래픽이 제대로 라우팅되지 않습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Cloud Volumes ONTAP 에서 Azure Private Link 또는 서비스 엔드포인트를 사용하는 방법에 대해 자세히 알아보세요."^]

.단계
. *관리 > 에이전트*를 선택하세요.
. *개요* 페이지에서 콘솔 에이전트의 작업 메뉴를 선택하고 *에이전트 편집*을 선택합니다.
+
편집하려면 콘솔 에이전트가 활성화되어 있어야 합니다.

. *직접 API 트래픽 지원*을 선택하세요.
. 옵션을 활성화하려면 확인란을 선택한 다음 *저장*을 선택하세요.

