---
sidebar: sidebar 
permalink: task-federation-saml.html 
keywords: federation, SAML protocol, SAML, federation services,  federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: 'SAML 2.0 IdP 공급자와 연합하여 NetApp 콘솔에 대한 SSO(Single Sign-On)를 활성화합니다.  이를 통해 사용자는 회사 자격 증명을 사용하여 로그인할 수 있습니다.' 
---
= SAML ID 공급자와 페더레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SAML 2.0 IdP 공급자와 연합하여 NEtApp 콘솔에 대한 SSO(Single Sign-On)를 활성화합니다.  이를 통해 사용자는 회사 자격 증명을 사용하여 로그인할 수 있습니다.

.필수 역할
연합을 만들고 관리하려면 연합 관리자 역할이 필요합니다.  연방 뷰어는 연방 페이지를 볼 수 있습니다.link:reference-iam-predefined-roles.html["액세스 역할에 대해 자세히 알아보세요."]


NOTE: 회사 IdP 또는 NetApp 지원 사이트와 연합할 수 있습니다.  두 나라 모두와 연합할 수는 없습니다.

NetApp 서비스 공급자가 시작하는(SP 가 시작하는) SSO만 지원합니다.  먼저 NetApp 서비스 공급자로 신뢰하도록 ID 공급자를 구성해야 합니다.  그런 다음 콘솔에서 ID 공급자의 구성을 사용하는 연결을 만들 수 있습니다.

SAML 2.0 공급자와 페더레이션 연결을 설정하면 콘솔에 대한 SSO(Single Sign-On)를 사용할 수 있습니다.  이 프로세스에는 서비스 공급자로서 NetApp 신뢰하도록 공급자를 구성한 다음 콘솔에서 연결을 만드는 작업이 포함됩니다.

.시작하기 전에
* 관리자 권한이 있는 IdP 계정이 필요합니다.  IdP 관리자와 협력하여 단계를 완료하세요.
* 페더레이션에 사용할 도메인을 식별합니다.  귀하의 이메일 도메인이나 귀하가 소유한 다른 도메인을 사용할 수 있습니다.  이메일 도메인이 아닌 다른 도메인을 사용하려면 먼저 콘솔에서 도메인을 확인해야 합니다.  다음 단계에 따라 이 작업을 수행할 수 있습니다.link:task-federation-verify-domain.html["NetApp 콘솔에서 도메인을 확인하세요"] 주제.


.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *연합*을 선택하면 *연합* 페이지를 볼 수 있습니다.
. *새 페더레이션 구성*을 선택합니다.
. 도메인 세부 정보를 입력하세요:
+
.. 검증된 도메인을 사용할지, 이메일 도메인을 사용할지 선택하세요.  이메일 도메인은 로그인한 계정과 연결된 도메인입니다.
.. 구성 중인 페더레이션의 이름을 입력하세요.
.. 검증된 도메인을 선택한 경우 목록에서 도메인을 선택하세요.


. *다음*을 선택하세요.
. 연결 방법으로 *프로토콜*을 선택한 다음 *SAML ID 공급자*를 선택합니다.
. *다음*을 선택하세요.
. NetApp 서비스 공급자로 신뢰하도록 SAML ID 공급자를 구성합니다.  이 단계는 SAML 공급자 서버에서 수행해야 합니다.
+
.. IdP에 속성이 있는지 확인하세요. `email` 사용자의 이메일 주소로 설정됩니다.  콘솔이 사용자를 올바르게 식별하려면 다음이 필요합니다.
+
[source, xml]
----
<saml:AttributeStatement xmlns:x500="urn:oasis:names:tc:SAML:2.0:profiles:attribute:X500" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <saml:Attribute Name="email" NameFormat="urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName">
        <saml:AttributeValue xsi:type="xs:string">email@domain.com</saml:AttributeValue>
    </saml:Attribute>
</saml:AttributeStatement>
----
.. 콘솔에 SAML 애플리케이션을 등록할 때 다음 값을 사용하세요.
+
*** *답변 URL* 또는 *Assertion Consumer Service(ACS) URL*의 경우 다음을 사용하세요. `https://netapp-cloud-account.auth0.com/login/callback`
*** *로그아웃 URL*의 경우 다음을 사용하세요. `https://netapp-cloud-account.auth0.com/logout`
*** *대상/엔터티 ID*의 경우 다음을 사용하세요. `urn:auth0:netapp-cloud-account:<fed-domain-name-saml>` 여기서 <fed-domain-name-saml>은 페더레이션에 사용하려는 도메인 이름입니다.  예를 들어, 귀하의 도메인이 `example.com` , 대상/엔터티 ID는 다음과 같습니다. `urn:auth0:netapp-cloud-account:fed-example-com-samlp` .


.. 신뢰를 생성한 후 SAML 공급자 서버에서 다음 값을 복사합니다.
+
*** 로그인 URL
*** 로그아웃 URL(선택 사항)


.. SAML 공급자 서버에서 X.509 인증서를 다운로드합니다.  PEM, CER 또는 CRT 형식이어야 합니다.


. 콘솔로 돌아가서 *다음*을 선택하여 연결을 만듭니다.
. SAML로 연결을 생성합니다.
+
.. SAML 서버의 *로그인 URL*을 입력하세요.
.. SAML 공급자 서버에서 다운로드한 X.509 인증서를 업로드합니다.
.. 선택적으로 SAML 서버의 *로그아웃 URL*을 입력하세요.


. *연결 만들기*를 선택합니다.  시스템은 몇 초 안에 연결을 생성합니다.
. *다음*을 선택하세요.
. 연결을 테스트하려면 *연결 테스트*를 선택하세요.  IdP 서버의 로그인 페이지로 이동됩니다.  테스트를 완료하려면 IdP 자격 증명으로 로그인하고 콘솔로 돌아가서 연결을 활성화하세요.
. *다음*을 선택하세요.
. *페더레이션 활성화* 페이지에서 페더레이션 세부 정보를 검토한 다음 *페더레이션 활성화*를 선택합니다.
. *마침*을 선택하여 과정을 완료하세요.


페더레이션을 활성화하면 사용자는 회사 자격 증명을 사용하여 NetApp 콘솔에 로그인할 수 있습니다.
