---
sidebar: sidebar 
permalink: task-sign-up-saas.html 
keywords: sign up, signing up, sign in, signing in, login with netapp, log in with netapp, create account, account, log in with nss, nss, nss login 
summary: 콘솔 사용을 시작하려면 먼저 NetApp 지원 사이트 자격 증명을 사용하여 가입 또는 로그인하거나 NetApp Console 로그인을 생성해야 합니다. 회사에서 처음으로 가입하는 사용자라면 조직 관리자 권한으로 콘솔에서 새 조직을 생성해야 합니다. 회사에 이미 조직이 있는 경우, 가입하거나 로그인하여 해당 조직에 액세스할 수 있습니다. 
---
= NetApp Console 에 가입하거나 로그인하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
콘솔을 사용하려면 NetApp 지원 사이트 자격 증명으로 가입하거나 로그인하거나 NetApp Console 로그인을 생성하십시오. 회사에서 처음으로 가입하는 경우, 관리자 권한으로 새 조직을 생성하게 됩니다. 회사에 이미 조직이 있는 경우 기존 NetApp 지원 사이트 자격 증명 또는 회사 단일 로그인(SSO)을 사용하여 가입하거나 로그인하십시오.



[[sign-up-for-netapp-console-as-the-initial-organization-administrator]]
== NetApp Console 에 최초 조직 관리자로 등록하세요.

회사에 NetApp Console 조직이 없는 경우 가입하여 조직을 생성하세요. 첫 번째 사용자는 조직 관리자가 되어 사용자 계정 및 권한을 관리합니다. 역할은 나중에 업데이트하고 관리자를 추가할 수 있습니다.

.단계
. 웹 브라우저를 열고 https://console.netapp.com["NetApp Console"^]로 이동합니다.
. NetApp 지원 사이트 계정이 있는 경우, *로그인* 페이지에서 계정과 연결된 이메일 주소를 직접 입력하십시오.
+
콘솔은 초기 로그인 과정에서 NetApp 지원 사이트 자격 증명을 사용하여 사용자를 등록합니다.

. 콘솔 로그인을 만들어 가입하려면 *가입*을 선택하세요.
+
.. *가입* 페이지에서 필요한 정보를 입력하고 *다음*을 선택하세요.
+

NOTE: 회원가입 양식에는 영문자만 입력할 수 있습니다.

.. NetApp 에서 보낸 이메일이 받은 편지함에서 확인되었는지 확인하세요. 이메일 주소 확인 지침이 포함되어 있습니다.
+
가입을 완료하려면 이메일 주소를 인증하세요.



. 로그인 후 최종 사용자 라이선스 계약을 검토하고 동의하십시오.
. *환영* 페이지에서 조직을 생성하세요.
. *시작하기*를 선택하세요.


+ 처음 사용자이거나 조직 관리자인 경우, 안내에 따라 스토리지 리소스를 추가하고 콘솔 에이전트를 생성하는 등의 작업을 수행할 수 있습니다. link:task-console-assistant.html["콘솔 지원 사용법에 대해 알아보세요."^]

.다음 단계
관리자로서 콘솔 지원 도구에 포함된 단계를 완료한 후에는 ID 및 액세스 전략을 계획하고, 조직에 사용자를 추가하고, 역할을 할당해야 합니다. link:task-iam-get-started.html["NetApp Console 의 ID 및 액세스 관리에 대해 알아보세요."^]



[[sign-up-or-login-to-netapp-console-when-an-organization-already-exists]]
== 이미 조직이 있는 경우 NetApp Console 에 가입하거나 로그인하세요.

귀사에 이미 NetApp Console 조직이 있는 경우, 가입하거나 로그인하여 액세스하십시오. 가입 또는 로그인 방법은 회사에서 ID 페더레이션을 사용하는지 또는 NetApp 지원 사이트 자격 증명을 보유하고 있는지에 따라 다릅니다. 그렇지 않다면 NetApp Console 로그인 계정을 생성하십시오.

.단계
. 웹 브라우저를 열고 https://console.netapp.com["NetApp Console"^]로 이동합니다.
. NetApp 지원 사이트 계정이 있거나 회사에서 단일 로그인(SSO)을 설정한 경우 *로그인* 페이지에서 연결된 이메일 주소 또는 SSO 자격 증명을 입력하십시오. 안내에 따라 로그인을 완료하세요.
+
두 경우 모두, 초기 로그인의 일부로 콘솔에 가입하게 됩니다.

. 콘솔 로그인을 만들어 가입하려면 *가입*을 선택하세요.
+
.. *가입* 페이지에서 필요한 정보를 입력하고 *다음*을 선택하세요.
+

NOTE: 회원가입 양식에는 영문자만 입력할 수 있습니다.

.. NetApp 에서 보낸 이메일이 받은 편지함에서 확인되었는지 확인하세요. 이메일 주소 확인 지침이 포함되어 있습니다.
+
가입을 완료하려면 이메일 주소를 인증하세요.



. 로그인 후 최종 사용자 라이선스 계약을 검토하고 동의하십시오.
. 시스템에서 조직을 생성하라는 메시지가 표시되면 대화 상자를 닫고 콘솔 관리자에게 알려 콘솔 조직에 추가하고 액세스 권한을 부여받으십시오. link:task-user-settings.html#contact-admin["조직 관리자에게 연락하는 방법을 알아보세요."^]


.다음 단계
조직에 대한 액세스 권한이 부여되면 스토리지를 관리하고 할당된 데이터 서비스를 사용할 수 있습니다.
