---
sidebar: sidebar 
permalink: task-install-agent-aws-console.html 
keywords: install connector, aws connector installation, aws connector, install connector in aws, bluexp, create connector 
summary: NetApp Console 에서 직접 AWS에서 콘솔 에이전트를 만들 수 있습니다.  AWS 콘솔에서 콘솔 에이전트를 생성하기 전에 네트워킹을 설정하고 AWS 권한을 준비해야 합니다. 
---
= NetApp Console 에서 AWS에 콘솔 에이전트 만들기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 에서 직접 AWS에서 콘솔 에이전트를 만들 수 있습니다.  AWS 콘솔에서 콘솔 에이전트를 생성하기 전에 네트워킹을 설정하고 AWS 권한을 준비해야 합니다.

.시작하기 전에
* 당신은 ~을 가져야합니다link:concept-agents.html["콘솔 에이전트에 대한 이해"] .
* 검토해야 합니다link:reference-limitations.html["콘솔 에이전트 제한 사항"] .




== 1단계: AWS에 콘솔 에이전트를 배포하기 위한 네트워킹 설정

콘솔 에이전트를 설치하려는 네트워크 위치가 다음 요구 사항을 지원하는지 확인하세요.  이러한 요구 사항을 통해 콘솔 에이전트는 하이브리드 클라우드의 리소스와 프로세스를 관리할 수 있습니다.

VPC 및 서브넷:: 콘솔 에이전트를 생성할 때는 에이전트가 상주해야 하는 VPC와 서브넷을 지정해야 합니다.


대상 네트워크에 대한 연결:: 콘솔 에이전트를 사용하려면 시스템을 만들고 관리하려는 위치에 대한 네트워크 연결이 필요합니다.  예를 들어, Cloud Volumes ONTAP 시스템이나 온프레미스 환경의 스토리지 시스템을 만들 계획인 네트워크입니다.


아웃바운드 인터넷 접속:: 콘솔 에이전트를 배포하는 네트워크 위치에는 특정 엔드포인트에 연결하기 위한 아웃바운드 인터넷 연결이 있어야 합니다.


콘솔 에이전트에서 연락한 엔드포인트:: 콘솔 에이전트는 일상 업무를 위해 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리하기 위해 다음 엔드포인트에 연결하기 위해 아웃바운드 인터넷 액세스가 필요합니다.
+
--
아래 나열된 엔드포인트는 모두 CNAME 항목입니다.

[cols="2a,1a"]
|===
| 엔드포인트 | 목적 


 a| 
AWS 서비스(amazonaws.com):

* 클라우드포메이션
* 탄력적 컴퓨팅 클라우드(EC2)
* ID 및 액세스 관리(IAM)
* 키 관리 서비스(KMS)
* 보안 토큰 서비스(STS)
* 간편 보관 서비스(S3)

 a| 
AWS 리소스를 관리합니다.  엔드포인트는 AWS 지역에 따라 달라집니다. https://docs.aws.amazon.com/general/latest/gr/rande.html["자세한 내용은 AWS 설명서를 참조하세요."^]



 a| 
\ https://mysupport.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보냅니다.



 a| 
\ https://support.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보냅니다.



 a| 
\ https://signin.b2c.netapp.com
 a| 
NetApp 지원 사이트(NSS) 자격 증명을 업데이트하거나 NetApp Console 에 새로운 NSS 자격 증명을 추가합니다.



 a| 
\ https://support.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보내고 Cloud Volumes ONTAP 에 대한 소프트웨어 업데이트를 받습니다.



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
NetApp Console 내에서 기능과 서비스를 제공합니다.



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
콘솔 에이전트 업그레이드를 위한 이미지를 얻으려면.

* 새로운 에이전트를 배포할 때 유효성 검사를 통해 현재 엔드포인트에 대한 연결성을 테스트합니다.  당신이 사용하는 경우link:link:reference-networking-saas-console-previous.html["이전 종료점"] , 유효성 검사에 실패합니다.  이러한 실패를 방지하려면 유효성 검사를 건너뛰세요.
+
이전 엔드포인트는 계속 지원되지만 NetApp 가능한 한 빨리 현재 엔드포인트에 맞게 방화벽 규칙을 업데이트할 것을 권장합니다. link:reference-networking-saas-console-previous.html#update-endpoint-list["엔드포인트 목록을 업데이트하는 방법을 알아보세요"] .

* 방화벽의 현재 엔드포인트로 업데이트하면 기존 에이전트도 계속 작동합니다.


|===
--


NetApp 콘솔에서 연결된 엔드포인트:: SaaS 계층을 통해 제공되는 웹 기반 NetApp Console 사용하면 여러 엔드포인트에 연결하여 데이터 관리 작업을 완료할 수 있습니다.  여기에는 콘솔에서 콘솔 에이전트를 배포하기 위해 연결된 엔드포인트가 포함됩니다.
+
--
link:reference-networking-saas-console.html["NetApp 콘솔에서 연결된 엔드포인트 목록 보기"] .

--


프록시 서버:: NetApp 명시적 프록시 구성과 투명 프록시 구성을 모두 지원합니다.  투명 프록시를 사용하는 경우 프록시 서버에 대한 인증서만 제공하면 됩니다.  명시적 프록시를 사용하는 경우 IP 주소와 자격 증명도 필요합니다.
+
--
* IP 주소
* 신임장
* HTTPS 인증서


--


포트:: Cloud Volumes ONTAP 에서 NetApp 지원팀으로 AutoSupport 메시지를 보내기 위한 프록시로 사용되거나 사용자가 시작하지 않는 한 콘솔 에이전트로 들어오는 트래픽이 없습니다.
+
--
* HTTP(80) 및 HTTPS(443)는 로컬 UI에 대한 액세스를 제공하며 이는 드문 상황에서 사용됩니다.
* SSH(22)는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.
* 아웃바운드 인터넷 연결을 사용할 수 없는 서브넷에 Cloud Volumes ONTAP 시스템을 배포하는 경우 포트 3128을 통한 인바운드 연결이 필요합니다.
+
Cloud Volumes ONTAP 시스템에 AutoSupport 메시지를 보낼 아웃바운드 인터넷 연결이 없는 경우 콘솔은 콘솔 에이전트에 포함된 프록시 서버를 사용하도록 해당 시스템을 자동으로 구성합니다.  유일한 요구 사항은 콘솔 에이전트의 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는 것입니다.  콘솔 에이전트를 배포한 후 이 포트를 열어야 합니다.



--


NTP 활성화:: NetApp Data Classification 사용하여 회사 데이터 소스를 스캔하려는 경우 콘솔 에이전트와 NetApp Data Classification 시스템 모두에서 NTP(네트워크 시간 프로토콜) 서비스를 활성화하여 시스템 간의 시간을 동기화해야 합니다. https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["NetApp 데이터 분류에 대해 자세히 알아보세요"^]
+
--
콘솔 에이전트를 만든 후 이 네트워킹 요구 사항을 구현해야 합니다.

--




== 2단계: 콘솔 에이전트에 대한 AWS 권한 설정

콘솔은 VPC에 콘솔 에이전트 인스턴스를 배포하기 전에 AWS에서 인증을 받아야 합니다.  다음 인증 방법 중 하나를 선택할 수 있습니다.

* 콘솔이 필요한 권한이 있는 IAM 역할을 가정하도록 합니다.
* 필요한 권한이 있는 IAM 사용자에게 AWS 액세스 키와 비밀 키를 제공합니다.


두 옵션 모두 첫 번째 단계는 IAM 정책을 만드는 것입니다.  이 정책에는 AWS 콘솔에서 콘솔 에이전트 인스턴스를 시작하는 데 필요한 권한만 포함되어 있습니다.

필요한 경우 IAM을 사용하여 IAM 정책을 제한할 수 있습니다. `Condition` 요소. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html["AWS 설명서: 조건 요소"^]

.단계
. AWS IAM 콘솔로 이동합니다.
. *정책 > 정책 만들기*를 선택합니다.
. *JSON*을 선택하세요.
. 다음 정책을 복사하여 붙여넣으세요.
+
이 정책에는 AWS 콘솔에서 콘솔 에이전트 인스턴스를 시작하는 데 필요한 권한만 포함되어 있습니다.  콘솔이 콘솔 에이전트를 생성하면 콘솔 에이전트 인스턴스에 새로운 권한 집합이 적용되어 콘솔 에이전트가 AWS 리소스를 관리할 수 있게 됩니다. link:reference-permissions-aws.html["콘솔 에이전트 인스턴스 자체에 필요한 권한 보기"] .

+
[source, json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iam:CreateRole",
        "iam:DeleteRole",
        "iam:PutRolePolicy",
        "iam:CreateInstanceProfile",
        "iam:DeleteRolePolicy",
        "iam:AddRoleToInstanceProfile",
        "iam:RemoveRoleFromInstanceProfile",
        "iam:DeleteInstanceProfile",
        "iam:PassRole",
        "iam:ListRoles",
        "ec2:DescribeInstanceStatus",
        "ec2:RunInstances",
        "ec2:ModifyInstanceAttribute",
        "ec2:CreateSecurityGroup",
        "ec2:DeleteSecurityGroup",
        "ec2:DescribeSecurityGroups",
        "ec2:RevokeSecurityGroupEgress",
        "ec2:AuthorizeSecurityGroupEgress",
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:RevokeSecurityGroupIngress",
        "ec2:CreateNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DeleteNetworkInterface",
        "ec2:ModifyNetworkInterfaceAttribute",
        "ec2:DescribeSubnets",
        "ec2:DescribeVpcs",
        "ec2:DescribeDhcpOptions",
        "ec2:DescribeKeyPairs",
        "ec2:DescribeRegions",
        "ec2:DescribeInstances",
        "ec2:CreateTags",
        "ec2:DescribeImages",
        "ec2:DescribeAvailabilityZones",
        "ec2:DescribeLaunchTemplates",
        "ec2:CreateLaunchTemplate",
        "cloudformation:CreateStack",
        "cloudformation:DeleteStack",
        "cloudformation:DescribeStacks",
        "cloudformation:DescribeStackEvents",
        "cloudformation:ValidateTemplate",
        "ec2:AssociateIamInstanceProfile",
        "ec2:DescribeIamInstanceProfileAssociations",
        "ec2:DisassociateIamInstanceProfile",
        "iam:GetRole",
        "iam:TagRole",
        "kms:ListAliases",
        "cloudformation:ListStacks"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:TerminateInstances"
      ],
      "Condition": {
        "StringLike": {
          "ec2:ResourceTag/OCCMInstance": "*"
        }
      },
      "Resource": [
        "arn:aws:ec2:*:*:instance/*"
      ]
    }
  ]
}
----
. *다음*을 선택하고 필요한 경우 태그를 추가합니다.
. *다음*을 선택하고 이름과 설명을 입력합니다.
. *정책 만들기*를 선택하세요.
. 콘솔이 가정할 수 있는 IAM 역할이나 IAM 사용자에게 정책을 연결하여 콘솔에 액세스 키를 제공할 수 있습니다.
+
** (옵션 1) 콘솔이 맡을 수 있는 IAM 역할을 설정합니다.
+
... 대상 계정의 AWS IAM 콘솔로 이동합니다.
... 액세스 관리에서 *역할 > 역할 만들기*를 선택하고 단계에 따라 역할을 만듭니다.
... *신뢰할 수 있는 엔터티 유형*에서 *AWS 계정*을 선택합니다.
... *다른 AWS 계정*을 선택하고 콘솔 SaaS 계정의 ID를 입력하세요: 952013314444
... 이전 섹션에서 만든 정책을 선택하세요.
... 역할을 만든 후 역할 ARN을 복사하여 콘솔 에이전트를 만들 때 콘솔에 붙여넣을 수 있습니다.


** (옵션 2) 콘솔에 액세스 키를 제공할 수 있도록 IAM 사용자에 대한 권한을 설정합니다.
+
... AWS IAM 콘솔에서 *사용자*를 선택한 다음 사용자 이름을 선택합니다.
... *권한 추가 > 기존 정책을 직접 첨부*를 선택합니다.
... 생성한 정책을 선택하세요.
... *다음*을 선택한 다음 *권한 추가*를 선택합니다.
... IAM 사용자에 대한 액세스 키와 비밀 키가 있는지 확인하세요.






.결과
이제 필요한 권한이 있는 IAM 역할이나 필요한 권한이 있는 IAM 사용자가 생겼습니다.  콘솔에서 콘솔 에이전트를 만들 때 역할이나 액세스 키에 대한 정보를 제공할 수 있습니다.



== 3단계: 콘솔 에이전트 만들기

콘솔 웹 기반 콘솔에서 직접 콘솔 에이전트를 만듭니다.

.이 작업에 관하여
* 콘솔에서 콘솔 에이전트를 생성하면 기본 구성을 사용하여 AWS에 EC2 인스턴스가 배포됩니다.  콘솔 에이전트를 생성한 후에는 CPU나 RAM이 적은 더 작은 EC2 인스턴스로 전환하지 마세요. link:reference-agent-default-config.html["콘솔 에이전트의 기본 구성에 대해 알아보세요"] .
* 콘솔에서 콘솔 에이전트를 생성하면 인스턴스에 대한 IAM 역할과 인스턴스 프로필이 생성됩니다.  이 역할에는 콘솔 에이전트가 AWS 리소스를 관리할 수 있는 권한이 포함됩니다.  향후 릴리스에서 새로운 권한이 추가되면 역할이 업데이트되도록 하세요. link:reference-permissions-aws.html["콘솔 에이전트에 대한 IAM 정책에 대해 자세히 알아보세요."] .


.시작하기 전에
다음 사항이 있어야 합니다.

* AWS 인증 방법: 필요한 권한이 있는 IAM 사용자에 대한 IAM 역할 또는 액세스 키입니다.
* 네트워킹 요구 사항을 충족하는 VPC 및 서브넷.
* EC2 인스턴스에 대한 키 쌍입니다.
* 콘솔 에이전트에서 인터넷에 접속하는 데 프록시가 필요한 경우 프록시 서버에 대한 세부 정보입니다.
* 설정link:#networking-aws-agent["네트워킹 요구 사항"] .
* 설정link:#aws-permissions-agent["AWS 권한"] .


.단계
. *관리 > 에이전트*를 선택하세요.
. *개요* 페이지에서 *에이전트 배포 > AWS*를 선택합니다.
. 마법사의 단계에 따라 콘솔 에이전트를 만듭니다.
. *소개* 페이지에서 프로세스 개요를 제공합니다.
. *AWS 자격 증명* 페이지에서 AWS 지역을 지정한 다음 인증 방법을 선택합니다. 인증 방법은 콘솔에서 가정할 수 있는 IAM 역할이나 AWS 액세스 키 및 비밀 키입니다.
+

TIP: *역할 가정*을 선택하면 콘솔 에이전트 배포 마법사에서 첫 번째 자격 증명 세트를 만들 수 있습니다.  추가 자격 증명 세트는 자격 증명 페이지에서 만들어야 합니다.  그러면 마법사의 드롭다운 목록에서 해당 항목을 사용할 수 있습니다. link:task-adding-aws-accounts.html["추가 자격 증명을 추가하는 방법을 알아보세요"] .

. *세부정보* 페이지에서 콘솔 에이전트에 대한 세부정보를 제공합니다.
+
** 인스턴스의 이름을 입력하세요.
** 인스턴스에 사용자 정의 태그(메타데이터)를 추가합니다.
** 콘솔에서 필요한 권한이 있는 새 역할을 만들지 아니면 사용자가 설정한 기존 역할을 선택할지 선택합니다.link:reference-permissions-aws.html["필요한 권한"] .
** 콘솔 에이전트의 EBS 디스크를 암호화할지 여부를 선택합니다.  기본 암호화 키를 사용하거나 사용자 지정 키를 사용할 수 있습니다.


. *네트워크* 페이지에서 인스턴스에 대한 VPC, 서브넷 및 키 쌍을 지정하고, 공용 IP 주소를 활성화할지 여부를 선택하고, 선택적으로 프록시 구성을 지정합니다.
+
콘솔 에이전트 가상 머신에 액세스하려면 올바른 키 쌍이 있는지 확인하세요.  키 쌍이 없으면 액세스할 수 없습니다.

. *보안 그룹* 페이지에서 새 보안 그룹을 만들지, 아니면 필요한 인바운드 및 아웃바운드 규칙을 허용하는 기존 보안 그룹을 선택할지 선택합니다.
+
link:reference-ports-aws.html["AWS에 대한 보안 그룹 규칙 보기"] .

. 선택 사항을 검토하여 설정이 올바른지 확인하세요.
+
.. *에이전트 구성 검증* 확인란은 배포 시 콘솔에서 네트워크 연결 요구 사항을 검증하도록 기본적으로 선택되어 있습니다.  콘솔에서 에이전트를 배포하지 못하면 문제 해결에 도움이 되는 보고서가 제공됩니다.  배포가 성공하면 보고서는 제공되지 않습니다.


+
[]
====
아직도 사용 중이라면link:reference-networking-saas-console-previous.html["이전 종료점"] 에이전트 업그레이드에 사용되면 유효성 검사가 오류로 인해 실패합니다.  이를 방지하려면 유효성 검사를 건너뛰려면 확인란의 선택을 취소하세요.

====
. *추가*를 선택하세요.
+
콘솔은 약 10분 안에 인스턴스를 준비합니다.  프로세스가 완료될 때까지 페이지에 머물러주세요.



.결과
프로세스가 완료되면 콘솔 에이전트를 콘솔에서 사용할 수 있습니다.


NOTE: 배포에 실패하면 콘솔에서 보고서와 로그를 다운로드하여 문제를 해결할 수 있습니다.link:task-troubleshoot-agent.html#troubleshoot-installation["설치 문제를 해결하는 방법을 알아보세요."]

콘솔 에이전트를 생성한 동일한 AWS 계정에 Amazon S3 버킷이 있는 경우, *시스템* 페이지에 Amazon S3 작업 환경이 자동으로 표시됩니다. https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["NetApp Console 에서 S3 버킷을 관리하는 방법을 알아보세요."^]
