---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, service account, member, role, permissions, organization, project, folder, iam, identity and access management, federated groups, SSO, access roles, add members, grant permissions 
summary: 조직의 리소스 계층 구조의 다양한 수준에서 권한을 제공하기 위해 조직의 구성원을 관리합니다. 
---
= NetApp Console 조직에 구성원 추가
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Console 내에서 액세스 역할에 따라 사용자에게 프로젝트 또는 폴더에 대한 액세스 권한을 부여할 수 있습니다. _액세스 역할_은 리소스 계층 구조의 지정된 수준에서 구성원(사용자 또는 서비스 계정)이 특정 작업을 수행할 수 있도록 하는 권한 집합을 포함합니다.

.필수 접근 권한 역할
최고 관리자, 조직 관리자 또는 폴더/프로젝트 관리자(해당 폴더 및 프로젝트를 관리하는 경우에 한함). link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보세요"].



[[understand-how-access-is-granted-in-netapp-console]]
== NetApp Console 에서 액세스 권한이 부여되는 방식을 이해하십시오.

NetApp Console은 역할 기반 액세스 제어(RBAC)를 사용하여 권한을 관리합니다. 사용자에게 개별적으로 또는 연합 그룹을 통해 역할을 할당할 수 있습니다. 각 역할은 특정 리소스에 대해 허용되는 작업을 정의합니다.

NetApp Console 에서 액세스 권한을 부여할 때 다음 사항에 유의하십시오.

* 연합 그룹에 속해 있더라도 모든 사용자는 리소스에 액세스하기 전에 먼저 NetApp Console에 등록해야 합니다.
* 콘솔에서 각 사용자가 리소스에 액세스하려면 해당 사용자에게 명시적으로 역할을 할당해야 합니다. 이는 역할이 할당된 연합 그룹의 구성원인 경우에도 마찬가지입니다.
* 콘솔에서 직접 서비스 계정을 추가하고 역할을 할당할 수 있습니다.
* 사용자 또는 서비스 계정에 역할을 할당할 때 지원되는 역할 중에서 선택할 수 있습니다.




[[add-members-to-your-organization]]
[[add-members]]
== 조직에 구성원 추가

NetApp Console 사용자 계정, 서비스 계정 및 페더레이션 그룹의 세 가지 유형의 멤버를 지원합니다.

연합 그룹에 속해 있더라도 사용자를 추가하고 역할을 할당하려면 먼저 NetApp Console 에 가입해야 합니다. 콘솔에서 직접 서비스 계정을 생성하세요.

모든 구성원은 리소스에 접근하기 위해 최소한 하나의 역할이 명시적으로 할당되어 있어야 합니다.

멤버를 추가할 때는 리소스 수준(조직, 폴더 또는 프로젝트)을 선택하고 필요한 권한이 있는 역할을 할당하세요.



[[add-a-user]]
=== 사용자 추가

사용자는 NetApp Console 에 가입하지만, 조직 관리자, 폴더 관리자 또는 프로젝트 관리자가 해당 사용자를 조직, 폴더 또는 프로젝트에 추가해야 리소스에 액세스할 수 있습니다.

.시작하기 전에:
사용자는 이미 NetApp Console 에 가입되어 있어야 합니다. 아직 가입하지 않았다면, 가입 페이지로 안내해 주세요. link:task-sign-up-saas.html["NetApp Console 에 가입하세요."]


NOTE: 연합 그룹에 속한 사용자를 추가하는 경우, 해당 사용자가 NetApp Console에 이미 가입되어 있고 Console에서 명시적으로 역할을 할당받았는지 확인하십시오. NetApp은 조직 뷰어와 같은 최소 액세스 역할을 할당하는 것을 권장합니다.

.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *회원*을 선택하세요.
. *멤버 추가*를 선택하세요.
. *회원 유형*에서 *사용자*를 선택된 상태로 둡니다.
. *사용자 이메일*에는 사용자가 만든 로그인과 연결된 이메일 주소를 입력합니다.
. *조직, 폴더 또는 프로젝트 선택* 섹션을 사용하여 멤버에게 권한이 부여되어야 하는 리소스 계층 수준을 선택합니다.
+
다음 사항에 유의하세요.

+
** 권한이 있는 폴더와 프로젝트만 선택할 수 있습니다.
** 조직이나 폴더를 선택하면 해당 구성원에게 모든 콘텐츠에 대한 접근 권한이 부여됩니다.
** *조직 관리자* 역할은 조직 수준에서만 할당할 수 있습니다.


. *카테고리를 선택한 다음* 해당 조직, 폴더 또는 프로젝트에 연결된 리소스에 대한 권한을 멤버에게 제공하는 *역할*을 선택합니다.
+
드롭다운 목록에는 지원되는 역할만 표시됩니다. link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보세요"].

. 더 많은 폴더, 프로젝트 또는 역할에 대한 액세스 권한을 부여하려면 *역할 추가*를 선택하고 폴더, 프로젝트 또는 역할 범주를 선택한 다음 역할을 선택하세요.
. *추가*를 선택하세요.
+
콘솔은 사용자에게 이메일로 지침을 보냅니다.





[[add-a-service-account]]
[[service-account]]
=== 서비스 계정 추가

서비스 계정을 사용하면 작업을 자동화하고 콘솔 API에 안전하게 연결할 수 있습니다. 간단한 설정을 위해서는 클라이언트 ID와 암호를 선택하고, 자동화 환경이나 클라우드 네이티브 환경에서 보안을 강화하려면 JWT(JSON Web Token)를 선택하십시오. 보안 요구 사항에 맞는 방법을 선택하십시오.

.시작하기 전에:
JWT 인증을 위해서는 공개 키 또는 인증서를 준비하십시오.

.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *회원*을 선택하세요.
. *멤버 추가*를 선택하세요.
. *회원 유형*에서 *서비스 계정*을 선택하세요.
. 서비스 계정의 이름을 입력하세요.
. JWT 인증을 사용하려면 *개인 키 JWT 인증 사용*을 선택하고 공개 RSA 키 또는 인증서를 업로드하세요. 클라이언트 ID와 시크릿을 사용하는 경우 이 단계를 건너뛰세요.
+
X.509 인증서를 PEM, CRT 또는 CER 형식으로 업로드하십시오.

+
.. 인증서 만료 알림을 설정하세요.  7일 또는 30일 중에서 선택하세요.  만료 알림은 슈퍼 관리자 또는 조직 관리자 역할을 가진 사용자에게 이메일로 전송되고 콘솔에 표시됩니다.


. *조직, 폴더 또는 프로젝트 선택* 섹션을 사용하여 멤버에게 권한이 부여되어야 하는 리소스 계층 수준을 선택합니다.
+
다음 사항에 유의하세요.

+
** 권한이 있는 폴더와 프로젝트에서만 선택할 수 있습니다.
** 조직이나 폴더를 선택하면 구성원에게 해당 조직의 모든 내용에 대한 권한이 부여됩니다.
** *조직 관리자* 역할은 조직 수준에서만 할당할 수 있습니다.


. 범주를 선택한 다음, 선택한 조직, 폴더 또는 프로젝트의 리소스에 대한 권한을 구성원에게 부여할 역할(Role)을 선택하십시오.
+
link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보세요"] .

. 더 많은 폴더, 프로젝트 또는 역할에 대한 액세스 권한을 부여하려면 *역할 추가*를 선택하고 폴더, 프로젝트 또는 역할 범주를 선택한 다음 역할을 선택하세요.
. JWT 인증을 사용하지 않은 경우 클라이언트 ID와 클라이언트 시크릿을 다운로드하거나 복사하십시오.
+
콘솔에는 클라이언트 비밀 키가 한 번만 표시됩니다. 안전하게 복사해 두세요. 나중에 분실하더라도 다시 만들 수 있습니다.

. JWT 인증을 선택한 경우 클라이언트 ID와 JWT 대상 그룹을 다운로드하거나 복사하십시오. 콘솔에는 이 정보가 한 번만 표시되며, 이후에는 다시 불러올 수 없습니다.
. *닫기*를 선택하세요.




[[add-a-federated-group-to-your-organization]]
== 조직에 연합 그룹을 추가하세요

ID 공급자(IdP)에서 페더레이션 그룹을 조직에 추가하고 하나 이상의 역할을 할당할 수 있습니다. 연합 그룹의 구성원은 콘솔에서 그룹에 할당한 역할을 상속받습니다.


IMPORTANT: 콘솔에 페더레이션 그룹을 추가하고 역할을 할당하면, IdP(ID 공급자)의 해당 그룹 구성원이며 NetApp Console에 이미 가입하여 콘솔에서 명시적으로 역할을 할당받은 사용자만 리소스에 액세스할 수 있습니다. NetApp은 이러한 사용자에게 조직 뷰어와 같은 최소 액세스 권한을 가진 역할을 할당하는 것을 권장합니다.

연합 그룹에 역할을 할당하기 전에 다음 사항을 확인하십시오.

* IdP와 콘솔 간의 페더레이션을 설정하십시오. link:concept-federation.html["연합 설정 방법을 알아보세요."]
* 해당 그룹은 이미 IdP에 존재해야 하며 Console에 대한 앱 액세스 권한이 할당되어 있어야 합니다.


.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *회원*을 선택하세요.
. *멤버 추가*를 선택하세요.
. *회원 유형*에서 *연합 그룹*을 선택하십시오.
. 그룹이 구성원인 페더레이션을 선택합니다.
. *그룹 이름*에는 IdP에 등록된 그룹의 정확한 이름을 입력하세요.
. *조직, 폴더 또는 프로젝트 선택* 섹션을 사용하여 멤버에게 권한이 부여되어야 하는 리소스 계층 수준을 선택합니다.
+
다음 사항에 유의하세요.

+
** 권한이 있는 폴더와 프로젝트에서만 선택할 수 있습니다.
** 조직이나 폴더를 선택하면 구성원에게 해당 조직의 모든 내용에 대한 권한이 부여됩니다.
** *조직 관리자* 역할은 조직 수준에서만 할당할 수 있습니다.


. 범주를 선택한 다음, 선택한 조직, 폴더 또는 프로젝트의 리소스에 대한 권한을 구성원에게 부여할 역할(Role)을 선택하십시오.
+
드롭다운 목록에는 지원되는 역할만 표시됩니다. link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보세요"].

. 더 많은 폴더, 프로젝트 또는 역할에 대한 액세스 권한을 부여하려면 *역할 추가*를 선택하고 폴더, 프로젝트 또는 역할 범주를 선택한 다음 역할을 선택하세요.




[[related-information]]
== 관련 정보

* link:concept-identity-and-access-management.html["NetApp Console 에서 ID 및 액세스 관리에 대해 알아보세요"]
* link:task-iam-get-started.html["신원 및 액세스 시작하기"]
* link:reference-iam-predefined-roles.html["NetApp Console 액세스 역할"]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html["ID 및 액세스를 위한 API에 대해 알아보세요"^]

