---
sidebar: sidebar 
permalink: task-install-connector-google-bluexp-gcloud.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, create connector, gcp installation, gcp connector 
summary: NetApp 콘솔이나 Google Cloud를 사용하여 Google Cloud에서 콘솔 에이전트를 만들려면 네트워킹을 설정하고, Google Cloud 권한을 준비하고, Google Cloud API를 활성화한 다음 콘솔 에이전트를 만들어야 합니다. 
---
= NetApp 콘솔에서 Google Cloud에 콘솔 에이전트 만들기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud 콘솔에서 콘솔 에이전트를 만들 수 있습니다.  네트워킹을 설정하고, Google Cloud 권한을 준비하고, Google Cloud API를 활성화한 다음 콘솔 에이전트를 만들어야 합니다.

.시작하기 전에
* 당신은 ~을 가져야합니다link:concept-connectors.html["콘솔 에이전트에 대한 이해"] .
* 검토해야 합니다link:reference-limitations.html["콘솔 에이전트 제한 사항"] .




== 1단계: 네트워킹 설정

콘솔 에이전트가 대상 네트워크에 연결하고 아웃바운드 인터넷에 접속하여 리소스를 관리할 수 있도록 네트워킹을 설정합니다.

VPC 및 서브넷:: 콘솔 에이전트를 생성할 때는 에이전트가 상주해야 하는 VPC와 서브넷을 지정해야 합니다.


대상 네트워크에 대한 연결:: 콘솔 에이전트를 사용하려면 시스템을 만들고 관리하려는 위치에 대한 네트워크 연결이 필요합니다.  예를 들어, Cloud Volumes ONTAP 시스템이나 온프레미스 환경의 스토리지 시스템을 만들 계획인 네트워크입니다.


아웃바운드 인터넷 접속:: 콘솔 에이전트를 배포하는 네트워크 위치에는 특정 엔드포인트에 연결하기 위한 아웃바운드 인터넷 연결이 있어야 합니다.


콘솔 에이전트에서 연락한 엔드포인트:: 콘솔 에이전트는 일상 업무를 위해 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리하기 위해 다음 엔드포인트에 연결하기 위해 아웃바운드 인터넷 액세스가 필요합니다.
+
--
아래 나열된 엔드포인트는 모두 CNAME 항목입니다.

[cols="2a,1a"]
|===
| 엔드포인트 | 목적 


 a| 
\ https://www.googleapis.com/compute/v1/ \ https://compute.googleapis.com/compute/v1 \ https://cloudresourcemanager.googleapis.com/v1/projects \ https://www.googleapis.com/compute/beta \ https://storage.googleapis.com/storage/v1 \ https://www.googleapis.com/storage/v1 \ https://iam.googleapis.com/v1 \ https://cloudkms.googleapis.com/v1 \ https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Google Cloud에서 리소스를 관리합니다.



 a| 
\ https://mysupport.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보냅니다.



 a| 
\ https://signin.b2c.netapp.com
 a| 
NetApp 지원 사이트(NSS) 자격 증명을 업데이트하거나 NetApp 콘솔에 새로운 NSS 자격 증명을 추가합니다.



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
NetApp 콘솔 내에서 기능과 서비스를 제공합니다.



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
콘솔 에이전트 업그레이드를 위한 이미지를 얻으려면.

* 새로운 에이전트를 배포할 때 유효성 검사를 통해 현재 엔드포인트에 대한 연결성을 테스트합니다.  당신이 사용하는 경우link:link:reference-networking-saas-console-previous.html["이전 종료점"] , 유효성 검사에 실패합니다.  이러한 실패를 방지하려면 유효성 검사를 건너뛰세요.
+
이전 엔드포인트는 계속 지원되지만 NetApp 가능한 한 빨리 현재 엔드포인트에 맞게 방화벽 규칙을 업데이트할 것을 권장합니다. link:reference-networking-saas-console-previous.html#update-endpoint-list["엔드포인트 목록을 업데이트하는 방법을 알아보세요"] .

* 방화벽의 현재 엔드포인트로 업데이트하면 기존 에이전트도 계속 작동합니다.


|===
--


NetApp 콘솔에서 연결된 엔드포인트:: SaaS 계층을 통해 제공되는 웹 기반 NetApp 콘솔을 사용하면 여러 엔드포인트에 연결하여 데이터 관리 작업을 완료할 수 있습니다.  여기에는 콘솔에서 콘솔 에이전트를 배포하기 위해 연결된 엔드포인트가 포함됩니다.
+
--
link:reference-networking-saas-console.html["NetApp 콘솔에서 연결된 엔드포인트 목록 보기"] .

--


프록시 서버:: NetApp 명시적 프록시 구성과 투명 프록시 구성을 모두 지원합니다.  투명 프록시를 사용하는 경우 프록시 서버에 대한 인증서만 제공하면 됩니다.  명시적 프록시를 사용하는 경우 IP 주소와 자격 증명도 필요합니다.
+
--
* IP 주소
* 신임장
* HTTPS 인증서


--


포트:: Cloud Volumes ONTAP 에서 NetApp 지원팀으로 AutoSupport 메시지를 보내기 위한 프록시로 사용되거나 사용자가 시작하지 않는 한 콘솔 에이전트로 들어오는 트래픽이 없습니다.
+
--
* HTTP(80) 및 HTTPS(443)는 로컬 UI에 대한 액세스를 제공하며 이는 드문 상황에서 사용됩니다.
* SSH(22)는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.
* 아웃바운드 인터넷 연결을 사용할 수 없는 서브넷에 Cloud Volumes ONTAP 시스템을 배포하는 경우 포트 3128을 통한 인바운드 연결이 필요합니다.
+
Cloud Volumes ONTAP 시스템에 AutoSupport 메시지를 보낼 아웃바운드 인터넷 연결이 없는 경우 콘솔은 콘솔 에이전트에 포함된 프록시 서버를 사용하도록 해당 시스템을 자동으로 구성합니다.  유일한 요구 사항은 콘솔 에이전트의 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는 것입니다.  콘솔 에이전트를 배포한 후 이 포트를 열어야 합니다.



--


NTP 활성화:: NetApp 데이터 분류를 사용하여 회사 데이터 소스를 스캔하려는 경우 콘솔 에이전트와 NetApp 데이터 분류 시스템 모두에서 NTP(네트워크 시간 프로토콜) 서비스를 활성화하여 시스템 간의 시간을 동기화해야 합니다. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["NetApp 데이터 분류에 대해 자세히 알아보세요"^]
+
--
콘솔 에이전트를 만든 후 이 네트워킹 요구 사항을 구현합니다.

--




== 2단계: 콘솔 에이전트를 생성하기 위한 권한 설정

콘솔에서 콘솔 에이전트를 배포하려면 먼저 콘솔 에이전트 VM을 배포하는 Google 플랫폼 사용자의 권한을 설정해야 합니다.

.단계
. Google 플랫폼에서 사용자 지정 역할을 만듭니다.
+
.. 다음 권한을 포함하는 YAML 파일을 만듭니다.
+
[source, yaml]
----
title: Console agent deployment policy
description: Permissions for the user who deploys the Console agent
stage: GA
includedPermissions:
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.list
----
.. Google Cloud에서 Cloud Shell을 활성화합니다.
.. 필요한 권한이 포함된 YAML 파일을 업로드합니다.
.. 다음을 사용하여 사용자 정의 역할을 만듭니다. `gcloud iam roles create` 명령.
+
다음 예제에서는 프로젝트 수준에서 "connectorDeployment"라는 역할을 만듭니다.

+
gcloud iam 역할 커넥터 배포 생성 --project=myproject --file=connector-deployment.yaml

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud 문서: 사용자 지정 역할 만들기 및 관리"^]



. 콘솔이나 gcloud를 사용하여 콘솔 에이전트를 배포할 사용자에게 이 사용자 지정 역할을 할당합니다.
+
https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud 문서: 단일 역할 부여"^]





== 3단계: 콘솔 에이전트 작업에 대한 권한 설정

Google Cloud 서비스 계정은 콘솔 에이전트에 Google Cloud의 리소스를 관리하는 데 필요한 권한을 제공하는 데 필요합니다.  콘솔 에이전트를 만들 때 이 서비스 계정을 콘솔 에이전트 VM과 연결해야 합니다.

이후 릴리스에서 새로운 권한이 추가되면 사용자 지정 역할을 업데이트하는 것은 사용자의 책임입니다.  새로운 권한이 필요한 경우 릴리스 노트에 나열됩니다.

.단계
. Google Cloud에서 사용자 지정 역할을 만듭니다.
+
.. 내용을 포함하는 YAML 파일을 만듭니다.link:reference-permissions-gcp.html["콘솔 에이전트에 대한 서비스 계정 권한"] .
.. Google Cloud에서 Cloud Shell을 활성화합니다.
.. 필요한 권한이 포함된 YAML 파일을 업로드합니다.
.. 다음을 사용하여 사용자 정의 역할을 만듭니다. `gcloud iam roles create` 명령.
+
다음 예제에서는 프로젝트 수준에서 "connector"라는 이름의 역할을 만듭니다.

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud 문서: 사용자 지정 역할 만들기 및 관리"^]



. Google Cloud에서 서비스 계정을 만들고 서비스 계정에 역할을 할당합니다.
+
.. IAM 및 관리 서비스에서 *서비스 계정 > 서비스 계정 만들기*를 선택합니다.
.. 서비스 계정 세부 정보를 입력하고 *만들기 및 계속*을 선택하세요.
.. 방금 만든 역할을 선택하세요.
.. 나머지 단계를 완료하여 역할을 만듭니다.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud 문서: 서비스 계정 만들기"^]



. 콘솔 에이전트가 있는 프로젝트와 다른 프로젝트에 Cloud Volumes ONTAP 시스템을 배포하려는 경우 콘솔 에이전트의 서비스 계정에 해당 프로젝트에 대한 액세스 권한을 제공해야 합니다.
+
예를 들어, 콘솔 에이전트가 프로젝트 1에 있고 프로젝트 2에 Cloud Volumes ONTAP 시스템을 만들고 싶다고 가정해 보겠습니다.  프로젝트 2에서 서비스 계정에 대한 액세스 권한을 부여해야 합니다.

+
.. IAM 및 관리 서비스에서 Cloud Volumes ONTAP 시스템을 만들려는 Google Cloud 프로젝트를 선택합니다.
.. *IAM* 페이지에서 *액세스 권한 부여*를 선택하고 필요한 세부 정보를 제공합니다.
+
*** 콘솔 에이전트 서비스 계정의 이메일을 입력하세요.
*** 콘솔 에이전트의 사용자 지정 역할을 선택합니다.
*** *저장*을 선택하세요.




+
자세한 내용은 다음을 참조하세요. https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud 문서"^]





== 4단계: 공유 VPC 권한 설정

공유 VPC를 사용하여 서비스 프로젝트에 리소스를 배포하는 경우 권한을 준비해야 합니다.

이 표는 참조용이며 IAM 구성이 완료되면 사용자 환경에 권한 표가 반영되어야 합니다.

.공유 VPC 권한 보기
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| 신원 | 창조자 | 호스팅됨 | 서비스 프로젝트 권한 | 호스트 프로젝트 권한 | 목적 


| 에이전트를 배포하기 위한 Google 계정 | 관습 | 봉사 프로젝트  a| 
link:task-install-connector-google-bluexp-gcloud.html#agent-permissions-google["에이전트 배포 정책"]
 a| 
컴퓨팅.네트워크사용자
| 서비스 프로젝트에 에이전트 배포 


| 에이전트 서비스 계정 | 관습 | 봉사 프로젝트  a| 
link:reference-permissions-gcp.html["에이전트 서비스 계정 정책"]
| compute.networkUser 배포 관리자.편집기 | 서비스 프로젝트에서 Cloud Volumes ONTAP 및 서비스 배포 및 유지 관리 


| Cloud Volumes ONTAP 서비스 계정 | 관습 | 봉사 프로젝트 | storage.admin 멤버: NetApp 콘솔 서비스 계정(serviceAccount.user) | 해당 없음 | (선택 사항) NetApp 클라우드 계층화 및 NetApp 백업 및 복구용 


| Google API 서비스 에이전트 | 구글 클라우드 | 봉사 프로젝트  a| 
(기본값) 편집기
 a| 
컴퓨팅.네트워크사용자
| 배포를 대신하여 Google Cloud API와 상호 작용합니다.  콘솔이 공유 네트워크를 사용할 수 있도록 합니다. 


| Google Compute Engine 기본 서비스 계정 | 구글 클라우드 | 봉사 프로젝트  a| 
(기본값) 편집기
 a| 
컴퓨팅.네트워크사용자
| 배포를 대신하여 Google Cloud 인스턴스와 컴퓨팅 인프라를 배포합니다.  콘솔이 공유 네트워크를 사용할 수 있도록 합니다. 
|===
참고사항:

. deploymentmanager.editor는 배포에 방화벽 규칙을 전달하지 않고 콘솔에서 규칙을 생성하도록 선택한 경우에만 호스트 프로젝트에서 필요합니다.  규칙이 지정되지 않으면 NetApp 콘솔은 호스트 프로젝트에 VPC0 방화벽 규칙을 포함하는 배포를 생성합니다.
. firewall.create와 firewall.delete는 배포에 방화벽 규칙을 전달하지 않고 콘솔에서 해당 규칙을 생성하도록 선택한 경우에만 필요합니다.  이러한 권한은 콘솔 계정의 .yaml 파일에 있습니다.  공유 VPC를 사용하여 HA 쌍을 배포하는 경우 이러한 권한은 VPC1, 2, 3에 대한 방화벽 규칙을 만드는 데 사용됩니다.  다른 모든 배포의 경우 이러한 권한은 VPC0에 대한 규칙을 만드는 데에도 사용됩니다.
. 클라우드 계층화의 경우 계층화 서비스 계정에는 프로젝트 수준뿐만 아니라 서비스 계정에 대한 serviceAccount.user 역할이 있어야 합니다.  현재 프로젝트 수준에서 serviceAccount.user를 할당하는 경우 getIAMPolicy로 서비스 계정을 쿼리할 때 권한이 표시되지 않습니다.


====


== 5단계: Google Cloud API 활성화

콘솔 에이전트와 Cloud Volumes ONTAP 배포하기 전에 여러 Google Cloud API를 활성화해야 합니다.

.단계
. 프로젝트에서 다음 Google Cloud API를 활성화하세요.
+
** 클라우드 배포 관리자 V2 API
** 클라우드 로깅 API
** 클라우드 리소스 관리자 API
** 컴퓨트 엔진 API
** ID 및 액세스 관리(IAM) API
** 클라우드 키 관리 서비스(KMS) API
+
(고객 관리 암호화 키(CMEK)와 함께 NetApp Backup and Recovery를 사용하려는 경우에만 필요함)





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloud 문서: API 활성화"^]



== 6단계: 콘솔 에이전트 만들기

콘솔에서 직접 콘솔 에이전트를 만듭니다.

.이 작업에 관하여
콘솔 에이전트를 생성하면 기본 구성을 사용하여 Google Cloud에 가상 머신 인스턴스가 배포됩니다.  콘솔 에이전트를 만든 후에는 CPU나 RAM이 적은 더 작은 VM 인스턴스로 전환하지 마세요. link:reference-connector-default-config.html["콘솔 에이전트의 기본 구성에 대해 알아보세요"] .

.시작하기 전에
다음 사항이 있어야 합니다.

* 콘솔 에이전트와 콘솔 에이전트 VM에 대한 서비스 계정을 생성하는 데 필요한 Google Cloud 권한입니다.
* 네트워킹 요구 사항을 충족하는 VPC 및 서브넷.
* 콘솔 에이전트에서 인터넷에 접속하는 데 프록시가 필요한 경우 프록시 서버에 대한 세부 정보입니다.


.단계
. *관리 > 에이전트*를 선택하세요.
. *개요* 페이지에서 *에이전트 배포 > Google Cloud*를 선택합니다.
. *에이전트 배치* 페이지에서 필요한 사항에 대한 세부 정보를 검토하세요.  두 가지 옵션이 있습니다.
+
.. 제품 내 가이드를 사용하여 배포를 준비하려면 *계속*을 선택하세요.  제품 내 가이드의 각 단계에는 이 문서 페이지에 포함된 정보가 포함되어 있습니다.
.. 이 페이지의 단계에 따라 이미 준비가 되었다면 *배포로 건너뛰기*를 선택하세요.


. 마법사의 단계에 따라 콘솔 에이전트를 만듭니다.
+
** 메시지가 표시되면 가상 머신 인스턴스를 만드는 데 필요한 권한이 있는 Google 계정에 로그인하세요.
+
이 양식은 Google에서 소유하고 호스팅합니다.  귀하의 자격 증명은 NetApp 에 ​​제공되지 않습니다.

** *세부 정보*: 가상 머신 인스턴스의 이름을 입력하고, 태그를 지정하고, 프로젝트를 선택한 다음, 필요한 권한이 있는 서비스 계정을 선택합니다(자세한 내용은 위 섹션을 참조하세요).
** *위치*: 인스턴스에 대한 지역, 영역, VPC 및 서브넷을 지정합니다.
** *네트워크*: 공용 IP 주소를 사용할지 여부를 선택하고, 선택적으로 프록시 구성을 지정합니다.
** *네트워크 태그*: 투명 프록시를 사용하는 경우 콘솔 에이전트 인스턴스에 네트워크 태그를 추가합니다.  네트워크 태그는 소문자로 시작해야 하며 소문자, 숫자, 하이픈을 포함할 수 있습니다.  태그는 소문자나 숫자로 끝나야 합니다.  예를 들어, "console-agent-proxy" 태그를 사용할 수 있습니다.
** *방화벽 정책*: 새로운 방화벽 정책을 만들지, 아니면 필요한 인바운드 및 아웃바운드 규칙을 허용하는 기존 방화벽 정책을 선택할지 선택합니다.
+
link:reference-ports-gcp.html["Google Cloud의 방화벽 규칙"]



. 선택 사항을 검토하여 설정이 올바른지 확인하세요.
+
.. *에이전트 구성 검증* 확인란은 배포 시 콘솔에서 네트워크 연결 요구 사항을 검증하도록 기본적으로 선택되어 있습니다.  콘솔에서 에이전트를 배포하지 못하면 문제 해결에 도움이 되는 보고서가 제공됩니다.  배포가 성공하면 보고서는 제공되지 않습니다.


+
[]
====
아직도 사용 중이라면link:reference-networking-saas-console-previous.html["이전 종료점"] 에이전트 업그레이드에 사용되면 유효성 검사가 오류로 인해 실패합니다.  이를 방지하려면 유효성 검사를 건너뛰려면 확인란의 선택을 취소하세요.

====
. *추가*를 선택하세요.
+
인스턴스는 약 10분 안에 준비됩니다. 프로세스가 완료될 때까지 페이지에 머물러 주세요.



.결과
프로세스가 완료되면 콘솔 에이전트를 사용할 수 있습니다.


NOTE: 배포에 실패하면 콘솔에서 보고서와 로그를 다운로드하여 문제를 해결할 수 있습니다.link:task-troubleshoot-connector.html#troubleshoot-installation["설치 문제를 해결하는 방법을 알아보세요."]

콘솔 에이전트를 생성한 동일한 Google Cloud 계정에 Google Cloud Storage 버킷이 있는 경우, *시스템* 페이지에 Google Cloud Storage 시스템이 자동으로 표시됩니다. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["콘솔에서 Google Cloud Storage를 관리하는 방법을 알아보세요."]
