---
sidebar: sidebar 
permalink: task-federation-adfs.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: 'NetApp 콘솔에 대한 SSO(Single Sign-On)를 활성화하려면 Active Directory Federation Services(AD FS)와 페더레이션합니다.  이를 통해 사용자는 회사 자격 증명을 사용하여 로그인할 수 있습니다.' 
---
= NetApp 콘솔을 Active Directory Federation Services(AD FS)와 페더레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp NetApp 과 AD FS(Active Directory Federation Services)를 페더레이션합니다.  이를 통해 사용자는 회사 자격 증명을 사용하여 콘솔에 로그인할 수 있습니다.

.필수 역할
연합을 만들고 관리하려면 연합 관리자 역할이 필요합니다.  연방 뷰어는 연방 페이지를 볼 수 있습니다.link:reference-iam-predefined-roles.html["액세스 역할에 대해 자세히 알아보세요."]


NOTE: 회사 IdP 또는 NetApp 지원 사이트와 연합할 수 있습니다.  NetApp 둘 중 하나만 선택하는 것을 권장하지만, 둘 다 선택하는 것은 권장하지 않습니다.

NetApp 서비스 공급자가 시작하는(SP 가 시작하는) SSO만 지원합니다.  먼저, NetApp 콘솔을 서비스 공급자로 신뢰하도록 ID 공급자를 구성합니다.  그런 다음 ID 공급자의 구성을 사용하여 콘솔에서 연결을 만듭니다.

NetApp 콘솔에 대한 SSO(Single Sign-On)를 활성화하려면 AD FS 서버와 페더레이션을 설정할 수 있습니다.  이 프로세스에는 콘솔을 서비스 공급자로 신뢰하도록 AD FS를 구성한 다음 NetApp 콘솔에서 연결을 만드는 작업이 포함됩니다.

.시작하기 전에
* 관리자 권한이 있는 IdP 계정이 필요합니다.  IdP 관리자와 협력하여 단계를 완료하세요.
* 페더레이션에 사용할 도메인을 식별합니다.  귀하의 이메일 도메인이나 귀하가 소유한 다른 도메인을 사용할 수 있습니다.  이메일 도메인이 아닌 다른 도메인을 사용하려면 먼저 콘솔에서 도메인을 확인해야 합니다.  다음 단계에 따라 이 작업을 수행할 수 있습니다.link:task-federation-verify-domain.html["NetApp 콘솔에서 도메인을 확인하세요"] 주제.


.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *연합*을 선택하면 *연합* 페이지를 볼 수 있습니다.
. *새 페더레이션 구성*을 선택합니다.
. 도메인 세부 정보를 입력하세요:
+
.. 검증된 도메인을 사용할지, 이메일 도메인을 사용할지 선택하세요.  이메일 도메인은 로그인한 계정과 연결된 도메인입니다.
.. 구성 중인 페더레이션의 이름을 입력하세요.
.. 검증된 도메인을 선택한 경우 목록에서 도메인을 선택하세요.


. *다음*을 선택하세요.
. 연결 방법으로 *프로토콜*을 선택한 다음 *Active Directory Federation Services(AD FS)*를 선택합니다.
. *다음*을 선택하세요.
. AD FS 서버에서 신뢰 당사자 트러스트를 만듭니다.  PowerShell을 사용하거나 AD FS 서버에서 수동으로 구성할 수 있습니다.  신뢰 당사자 트러스트를 만드는 방법에 대한 자세한 내용은 AD FS 설명서를 참조하세요.
+
.. 다음 스크립트를 사용하여 PowerShell을 사용하여 신뢰를 만듭니다.
+
[source, powershell]
----
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"
----
.. 또는 AD FS 관리 콘솔에서 수동으로 신뢰를 만들 수 있습니다.  신뢰를 생성할 때 다음 NetApp 콘솔 값을 사용하세요.
+
*** Relying Trust Identifier를 생성할 때 **YOUR_TENANT** 값을 사용하세요. `netapp-cloud-account`
*** *WS-Federation 지원 활성화*를 선택하는 경우 **YOUR_AUTH0_DOMAIN** 값을 사용하세요. `netapp-cloud-account.auth0.com`


.. 신뢰를 생성한 후 AD FS 서버에서 메타데이터 URL을 복사하거나 페더레이션 메타데이터 파일을 다운로드합니다.  콘솔에서 연결을 완료하려면 이 URL이나 파일이 필요합니다.


+
NetApp NetApp 콘솔이 최신 AD FS 구성을 자동으로 검색하도록 메타데이터 URL을 사용할 것을 권장합니다.  페더레이션 메타데이터 파일을 다운로드한 경우 AD FS 구성이 변경될 때마다 NetApp 콘솔에서 수동으로 업데이트해야 합니다.

. 콘솔로 돌아가서 *다음*을 선택하여 연결을 만듭니다.
. AD FS로 연결을 만듭니다.
+
.. 이전 단계에서 AD FS 서버에서 복사한 *AD FS URL*을 입력하거나 AD FS 서버에서 다운로드한 페더레이션 메타데이터 파일을 업로드합니다.


. *연결 만들기*를 선택합니다.  연결을 만드는 데 몇 초가 걸릴 수 있습니다.
. *다음*을 선택하세요.
. 연결을 테스트하려면 *연결 테스트*를 선택하세요.  IdP 서버의 로그인 페이지로 이동됩니다.  테스트를 완료하려면 IdP 자격 증명으로 로그인하고 콘솔로 돌아가서 연결을 활성화하세요.
. *다음*을 선택하세요.
. *페더레이션 활성화* 페이지에서 페더레이션 세부 정보를 검토한 다음 *페더레이션 활성화*를 선택합니다.
. *마침*을 선택하여 과정을 완료하세요.


페더레이션을 활성화하면 사용자는 회사 자격 증명을 사용하여 NetApp 콘솔에 로그인할 수 있습니다.
