---
sidebar: sidebar 
permalink: task-update-agent-addressing.html 
keywords: agent ip address, agent uri, change ip address, edit uri, agent network, agent addressing 
summary: 네트워크 구성이 변경될 경우 클라우드 공급자에서 에이전트의 IP 주소를 업데이트하고 Console에 등록된 URI를 업데이트해야 할 수 있습니다. 
---
= NetApp Console 에이전트 주소 지정 및 URI 업데이트
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
네트워크 구성이 변경될 경우 클라우드 공급자에서 에이전트의 IP 주소를 업데이트하고 Console에 등록된 URI를 업데이트해야 할 수 있습니다.



[[change-the-ip-address-for-an-agent]]
== 에이전트의 IP 주소 변경

필요한 경우 클라우드 공급자가 할당한 에이전트 인스턴스의 내부 및 공용 IP 주소를 변경할 수 있습니다.

.단계
. 클라우드 제공업체의 지침에 따라 에이전트 인스턴스의 로컬 IP 주소나 공용 IP 주소(또는 둘 다)를 변경하세요.
. 콘솔에 새로운 공용 IP 주소를 등록하려면 에이전트 인스턴스를 다시 시작합니다.
. 개인 IP 주소를 변경한 경우 Cloud Volumes ONTAP 구성 파일의 백업 위치를 업데이트하여 백업이 에이전트의 새 개인 IP 주소로 전송되도록 합니다.
+
각 Cloud Volumes ONTAP 시스템의 백업 위치를 업데이트합니다.

+
.. Cloud Volumes ONTAP CLI에서 권한 수준을 고급으로 설정합니다.




[listing]
----
set -privilege advanced
----
. 다음 명령을 실행하여 현재 백업 대상을 표시합니다.


[listing]
----
system configuration backup settings show
----
. 다음 명령을 실행하여 백업 대상의 IP 주소를 업데이트합니다.


[listing]
----
system configuration backup settings modify -destination <target-location>
----


[[edit-an-agents-uris]]
== 에이전트의 URI 편집

네트워크 요구 사항이 변경되면 Console 에이전트의 URI를 업데이트하십시오. 이렇게 하면 스토리지 인프라를 중단 없이 안전하고 규정을 준수하여 관리할 수 있습니다.

.단계
. *관리 > 에이전트*를 선택하세요.
. *개요* 페이지에서 콘솔 에이전트의 작업 메뉴를 선택하고 *에이전트 편집*을 선택합니다.
+
편집하려면 콘솔 에이전트가 활성화되어 있어야 합니다.

. *에이전트 URI* 막대를 확장하여 에이전트 URI를 확인하세요.
. URI를 추가하고 제거한 다음 *적용*을 선택합니다.

