---
sidebar: sidebar 
permalink: task-install-connector-aws-marketplace.html 
keywords: install connector, aws connector installation, aws connector, install connector in aws, bluexp, aws marketplace, manual install, create connector 
summary: AWS Marketplace에서 콘솔 에이전트를 만들려면 네트워킹을 설정하고, AWS 권한을 준비하고, 인스턴스 요구 사항을 검토한 다음 콘솔 에이전트를 만들어야 합니다. 
---
= AWS Marketplace에서 콘솔 에이전트 만들기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS Marketplace에서 직접 AWS에서 콘솔 에이전트를 만들 수 있습니다.  AWS Marketplace에서 콘솔 에이전트를 만들려면 네트워킹을 설정하고, AWS 권한을 준비하고, 인스턴스 요구 사항을 검토한 다음 콘솔 에이전트를 만들어야 합니다.

.시작하기 전에
* 당신은 ~을 가져야합니다link:concept-connectors.html["콘솔 에이전트에 대한 이해"] .
* 검토해야 합니다link:reference-limitations.html["콘솔 에이전트 제한 사항"] .




== 1단계: 네트워킹 설정

하이브리드 클라우드 리소스를 관리하려면 콘솔 에이전트의 네트워크 위치가 다음 요구 사항을 충족하는지 확인하세요.

VPC 및 서브넷:: 콘솔 에이전트를 생성할 때는 에이전트가 상주해야 하는 VPC와 서브넷을 지정해야 합니다.


대상 네트워크에 대한 연결:: 콘솔 에이전트를 사용하려면 시스템을 만들고 관리하려는 위치에 대한 네트워크 연결이 필요합니다.  예를 들어, Cloud Volumes ONTAP 시스템이나 온프레미스 환경의 스토리지 시스템을 만들 계획인 네트워크입니다.


아웃바운드 인터넷 접속:: 콘솔 에이전트를 배포하는 네트워크 위치에는 특정 엔드포인트에 연결하기 위한 아웃바운드 인터넷 연결이 있어야 합니다.


콘솔 에이전트에서 연락한 엔드포인트:: 콘솔 에이전트는 일상 업무를 위해 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리하기 위해 다음 엔드포인트에 연결하기 위해 아웃바운드 인터넷 액세스가 필요합니다.
+
--
아래 나열된 엔드포인트는 모두 CNAME 항목입니다.

[cols="2a,1a"]
|===
| 엔드포인트 | 목적 


 a| 
AWS 서비스(amazonaws.com):

* 클라우드포메이션
* 탄력적 컴퓨팅 클라우드(EC2)
* ID 및 액세스 관리(IAM)
* 키 관리 서비스(KMS)
* 보안 토큰 서비스(STS)
* 간편 보관 서비스(S3)

 a| 
AWS 리소스를 관리합니다.  엔드포인트는 AWS 지역에 따라 달라집니다. https://docs.aws.amazon.com/general/latest/gr/rande.html["자세한 내용은 AWS 설명서를 참조하세요."^]



 a| 
\ https://mysupport.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보냅니다.



 a| 
\ https://support.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보냅니다.



 a| 
\ https://signin.b2c.netapp.com
 a| 
NetApp 지원 사이트(NSS) 자격 증명을 업데이트하거나 NetApp 콘솔에 새로운 NSS 자격 증명을 추가합니다.



 a| 
\https:\\support.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보내고 Cloud Volumes ONTAP 에 대한 소프트웨어 업데이트를 받습니다.



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
NetApp 콘솔 내에서 기능과 서비스를 제공합니다.



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
콘솔 에이전트 업그레이드를 위한 이미지를 얻으려면.

* 새로운 에이전트를 배포할 때 유효성 검사를 통해 현재 엔드포인트에 대한 연결성을 테스트합니다.  당신이 사용하는 경우link:link:reference-networking-saas-console-previous.html["이전 종료점"] , 유효성 검사에 실패합니다.  이러한 실패를 방지하려면 유효성 검사를 건너뛰세요.
+
이전 엔드포인트는 계속 지원되지만 NetApp 가능한 한 빨리 현재 엔드포인트에 맞게 방화벽 규칙을 업데이트할 것을 권장합니다. link:reference-networking-saas-console-previous.html#update-endpoint-list["엔드포인트 목록을 업데이트하는 방법을 알아보세요"] .

* 방화벽의 현재 엔드포인트로 업데이트하면 기존 에이전트도 계속 작동합니다.


|===
--


프록시 서버:: NetApp 명시적 프록시 구성과 투명 프록시 구성을 모두 지원합니다.  투명 프록시를 사용하는 경우 프록시 서버에 대한 인증서만 제공하면 됩니다.  명시적 프록시를 사용하는 경우 IP 주소와 자격 증명도 필요합니다.
+
--
* IP 주소
* 신임장
* HTTPS 인증서


--


포트:: Cloud Volumes ONTAP 에서 NetApp 지원팀으로 AutoSupport 메시지를 보내기 위한 프록시로 사용되거나 사용자가 시작하지 않는 한 콘솔 에이전트로 들어오는 트래픽이 없습니다.
+
--
* HTTP(80) 및 HTTPS(443)는 로컬 UI에 대한 액세스를 제공하며 이는 드문 상황에서 사용됩니다.
* SSH(22)는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.
* 아웃바운드 인터넷 연결을 사용할 수 없는 서브넷에 Cloud Volumes ONTAP 시스템을 배포하는 경우 포트 3128을 통한 인바운드 연결이 필요합니다.
+
Cloud Volumes ONTAP 시스템에 AutoSupport 메시지를 보낼 아웃바운드 인터넷 연결이 없는 경우 콘솔은 콘솔 에이전트에 포함된 프록시 서버를 사용하도록 해당 시스템을 자동으로 구성합니다.  유일한 요구 사항은 콘솔 에이전트의 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는 것입니다.  콘솔 에이전트를 배포한 후 이 포트를 열어야 합니다.



--


NTP 활성화:: NetApp 데이터 분류를 사용하여 회사 데이터 소스를 스캔하려는 경우 콘솔 에이전트와 NetApp 데이터 분류 시스템 모두에서 NTP(네트워크 시간 프로토콜) 서비스를 활성화하여 시스템 간의 시간을 동기화해야 합니다. https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["NetApp 데이터 분류에 대해 자세히 알아보세요"^]
+
--
콘솔 에이전트를 만든 후 이 네트워크 액세스를 구현합니다.

--




== 2단계: AWS 권한 설정

마켓플레이스 배포를 준비하려면 AWS에서 IAM 정책을 만들고 이를 IAM 역할에 연결합니다.  AWS Marketplace에서 콘솔 에이전트를 생성하면 해당 IAM 역할을 선택하라는 메시지가 표시됩니다.

.단계
. AWS 콘솔에 로그인하고 IAM 서비스로 이동합니다.
. 정책을 만듭니다.
+
.. *정책 > 정책 만들기*를 선택합니다.
.. *JSON*을 선택하고 내용을 복사하여 붙여넣습니다.link:reference-permissions-aws.html["콘솔 에이전트에 대한 IAM 정책"] .
.. 나머지 단계를 완료하여 정책을 만듭니다.
+
사용하려는 NetApp 데이터 서비스에 따라 두 번째 정책을 만들어야 할 수도 있습니다.  표준 지역의 경우 권한은 두 가지 정책에 걸쳐 분산됩니다.  AWS의 관리형 정책에는 최대 문자 크기 제한이 있으므로 두 개의 정책이 필요합니다. link:reference-permissions-aws.html["콘솔 에이전트에 대한 IAM 정책에 대해 자세히 알아보세요."] .



. IAM 역할을 만듭니다.
+
.. *역할 > 역할 만들기*를 선택합니다.
.. *AWS 서비스 > EC2*를 선택합니다.
.. 방금 만든 정책을 첨부하여 권한을 추가합니다.
.. 나머지 단계를 완료하여 역할을 만듭니다.




.결과
이제 AWS Marketplace에서 배포하는 동안 EC2 인스턴스와 연결할 수 있는 IAM 역할이 생겼습니다.



== 3단계: 인스턴스 요구 사항 검토

콘솔 에이전트를 생성할 때 다음 요구 사항을 충족하는 EC2 인스턴스 유형을 선택해야 합니다.

CPU:: 8개 코어 또는 8개 vCPU
숫양:: 32GB
AWS EC2 인스턴스 유형:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다.  t3.2xlarge를 추천합니다.




== 4단계: 콘솔 에이전트 만들기

AWS Marketplace에서 직접 콘솔 에이전트를 만듭니다.

.이 작업에 관하여
AWS Marketplace에서 콘솔 에이전트를 생성하면 기본 구성을 사용하여 AWS에 EC2 인스턴스가 배포됩니다. link:reference-connector-default-config.html["콘솔 에이전트의 기본 구성에 대해 알아보세요"] .

.시작하기 전에
다음 사항이 있어야 합니다.

* 네트워킹 요구 사항을 충족하는 VPC 및 서브넷.
* 콘솔 에이전트에 필요한 권한이 포함된 정책이 첨부된 IAM 역할입니다.
* IAM 사용자가 AWS Marketplace를 구독하고 구독을 취소할 수 있는 권한입니다.
* 인스턴스에 필요한 CPU 및 RAM 요구 사항을 이해합니다.
* EC2 인스턴스에 대한 키 쌍입니다.


.단계
. 로 가다 https://aws.amazon.com/marketplace/pp/prodview-jbay5iyfmu6ui["AWS Marketplace에 NetApp 콘솔 에이전트 목록이 추가되었습니다."^]
. 마켓플레이스 페이지에서 *구독 계속하기*를 선택하세요.
. 소프트웨어를 구독하려면 *약관 동의*를 선택하세요.
+
구독 절차는 몇 분 정도 걸릴 수 있습니다.

. 구독 프로세스가 완료되면 *구성 계속*을 선택하세요.
. *이 소프트웨어 구성* 페이지에서 올바른 지역을 선택했는지 확인한 다음 *계속 실행*을 선택합니다.
. *이 소프트웨어 실행* 페이지의 *작업 선택*에서 *EC2를 통해 실행*을 선택한 다음 *실행*을 선택합니다.
+
EC2 콘솔을 사용하여 인스턴스를 시작하고 IAM 역할을 연결합니다.  *웹사이트에서 실행* 작업에서는 이 작업이 불가능합니다.

. 프롬프트에 따라 인스턴스를 구성하고 배포하세요.
+
** *이름 및 태그*: 인스턴스의 이름과 태그를 입력합니다.
** *애플리케이션 및 OS 이미지*: 이 섹션을 건너뜁니다.  콘솔 에이전트 AMI가 이미 선택되었습니다.
** *인스턴스 유형*: 지역별 가용성에 따라 RAM 및 CPU 요구 사항을 충족하는 인스턴스 유형을 선택합니다(t3.2xlarge가 미리 선택되어 권장됨).
** *키 쌍(로그인)*: 인스턴스에 안전하게 연결하는 데 사용할 키 쌍을 선택하세요.
** *네트워크 설정*: 필요에 따라 네트워크 설정을 편집하세요.
+
*** 원하는 VPC와 서브넷을 선택하세요.
*** 인스턴스에 공용 IP 주소가 있어야 하는지 여부를 지정합니다.
*** 콘솔 에이전트 인스턴스에 필요한 연결 방법(SSH, HTTP, HTTPS)을 활성화하는 보안 그룹 설정을 지정합니다.
+
link:reference-ports-aws.html["AWS에 대한 보안 그룹 규칙 보기"] .



** *저장소 구성*: 루트 볼륨의 기본 크기와 디스크 유형을 유지합니다.
+
루트 볼륨에서 Amazon EBS 암호화를 활성화하려면 *고급*을 선택하고 *볼륨 1*을 확장한 다음 *암호화*를 선택하고 KMS 키를 선택합니다.

** *고급 세부 정보*: *IAM 인스턴스 프로필*에서 콘솔 에이전트에 필요한 권한이 포함된 IAM 역할을 선택합니다.
** *요약*: 요약을 검토하고 *인스턴스 시작*을 선택합니다.
+
AWS는 지정된 설정으로 콘솔 에이전트를 시작하고, 콘솔 에이전트는 약 10분 후에 실행됩니다.



+

NOTE: 설치에 실패하면 로그와 보고서를 보고 문제 해결에 도움을 받을 수 있습니다.link:task-troubleshoot-agent.html#troubleshoot-installation["설치 문제를 해결하는 방법을 알아보세요."]

. 콘솔 에이전트 가상 머신에 연결되어 있고 콘솔 에이전트의 URL이 있는 호스트에서 웹 브라우저를 엽니다.
. 로그인 후 콘솔 에이전트를 설정하세요.
+
.. 콘솔 에이전트와 연결할 콘솔 조직을 지정합니다.
.. 시스템 이름을 입력하세요.
.. *보안된 환경에서 실행하고 있습니까?*에서 제한 모드를 비활성화하세요.
+
표준 모드에서 콘솔을 사용하려면 제한 모드를 비활성화하세요.  보안 환경이 있고 콘솔 백엔드 서비스에서 이 계정의 연결을 끊으려는 경우에만 제한 모드를 활성화해야 합니다.  그렇다면,link:task-quick-start-restricted-mode.html["제한 모드에서 NetApp 콘솔을 시작하기 위한 단계를 따르세요."] .

.. *시작하기*를 선택하세요.




.결과
이제 콘솔 에이전트가 설치되고 콘솔 조직에 설정되었습니다.

웹 브라우저를 열고 이동하세요 https://console.netapp.com["NetApp 콘솔"^] 콘솔과 함께 콘솔 에이전트를 사용하려면 다음을 수행합니다.

콘솔 에이전트를 생성한 동일한 AWS 계정에 Amazon S3 버킷이 있는 경우, *시스템* 페이지에 Amazon S3 작업 환경이 자동으로 표시됩니다. https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["NetApp 콘솔에서 S3 버킷을 관리하는 방법을 알아보세요."^]
