---
sidebar: sidebar 
permalink: task-console-assistant.html 
keywords: bluexp,netapp console,console assistant,assistant,setup assistant,get started,quick start,first time user,first time setup,setup wizard 
summary: 'NetApp Console 처음 사용하는 경우 콘솔 어시스턴트가 초기 설정 과정을 안내합니다.  도우미를 사용하면 NetApp 지원 사이트(NSS) 계정을 추가하고, 콘솔 에이전트를 추가하고, 클러스터를 추가하고, 라이선스나 구독을 추가하는 작업을 쉽게 수행할 수 있어 데이터 관리를 쉽게 시작할 수 있습니다.' 
---
= NetApp Console 어시스턴트를 사용하여 시작하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
조직 관리자 역할로 NetApp Console 처음 사용하는 경우 콘솔 도우미를 사용하여 초기 설정 프로세스를 안내받을 수 있습니다.  도우미를 사용하면 NetApp 지원 사이트(NSS) 계정을 추가하고, 콘솔 에이전트를 추가하고, 클러스터를 추가하고, 라이선스나 구독을 추가하는 작업을 쉽게 수행할 수 있어 데이터 관리를 쉽게 시작할 수 있습니다.



== 콘솔 어시스턴트에 액세스하는 데 필요한 역할

콘솔 어시스턴트는 조직 관리자 역할이 있는 사용자만 사용할 수 있습니다.



== 콘솔 어시스턴트는 언제 나타나나요?

콘솔 어시스턴트는 필수 설정 작업이 완료될 때까지 NetApp Console 홈페이지에서 사용할 수 있습니다.

도우미를 사용하여 다음과 같은 작업을 완료하세요. 이 중 일부는 필수입니다.

* NetApp 지원 사이트(NSS) 계정을 추가합니다.
* 콘솔 에이전트를 배포하여 스토리지 공간에 연결합니다(필수 단계).
* 클러스터를 추가하거나 검색하여 시스템을 관리합니다(필수 단계).
* 마켓플레이스 구독이나 PAYGO 라이선스를 추가합니다.
* 오픈 데이터 서비스 링크.




== 콘솔 어시스턴트 활성화

기본적으로 NetApp Console 조직 관리자 역할이 있는 신규 사용자를 위해 홈페이지에 콘솔 도우미를 표시합니다.


TIP: 본인이나 다른 사람이 필수 항목을 완료한 후에만 도우미를 직접 해고할 수 있습니다.  필수 항목을 완료하면 조직의 모든 사용자에 대한 도우미가 해제되고 다시 나타나지 않습니다.



== 콘솔 어시스턴트를 사용하여 시작하세요

콘솔 어시스턴트는 다음 작업을 통해 NetApp Console 환경을 설정하는 과정을 안내합니다.

* NetApp 지원 사이트(NSS) 계정을 추가합니다.
* 온프레미스 또는 클라우드에서 콘솔 에이전트를 배포하여 스토리지 공간에 연결합니다.  수동으로 배포하거나 OVA를 다운로드하여 배포할 수 있습니다.  이 단계는 필수입니다.
* 클러스터를 추가하거나 검색하여 시스템을 관리합니다.  이 단계는 필수입니다.
* 마켓플레이스 구독이나 PAYGO 라이선스를 추가합니다.
* NetApp 데이터 서비스에 대해 자세히 알아보세요.

