---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: Linux 호스트에 콘솔 에이전트를 수동으로 설치하려면 호스트 요구 사항을 검토하고, 네트워킹을 설정하고, Google Cloud 권한을 준비하고, Google Cloud API를 활성화하고, 콘솔을 설치한 다음, 준비한 권한을 제공해야 합니다. 
---
= Google Cloud에 콘솔 에이전트를 수동으로 설치합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux 호스트에 콘솔 에이전트를 수동으로 설치하려면 호스트 요구 사항을 검토하고, 네트워킹을 설정하고, Google Cloud 권한을 준비하고, Google Cloud API를 활성화하고, 콘솔을 설치한 다음, 준비한 권한을 제공해야 합니다.

.시작하기 전에
* 당신은 ~을 가져야합니다link:concept-connectors.html["콘솔 에이전트에 대한 이해"] .
* 검토해야 합니다link:reference-limitations.html["콘솔 에이전트 제한 사항"] .




== 1단계: 호스트 요구 사항 검토

콘솔 에이전트 소프트웨어는 특정 운영 체제 요구 사항, RAM 요구 사항, 포트 요구 사항 등을 충족하는 호스트에서 실행되어야 합니다.


NOTE: 콘솔 에이전트는 UID와 GID 범위를 19000~19200으로 예약합니다.  이 범위는 고정되어 있으며 수정할 수 없습니다.  호스트의 타사 소프트웨어가 이 범위 내의 UID나 GID를 사용하는 경우 에이전트 설치가 실패합니다.  NetApp 충돌을 피하기 위해 타사 소프트웨어가 없는 호스트를 사용할 것을 권장합니다.

전담 호스트:: 콘솔 에이전트는 다른 애플리케이션과 공유되는 호스트에서는 지원되지 않습니다. 호스트는 전담 호스트여야 합니다.  호스트는 다음 크기 요구 사항을 충족하는 모든 아키텍처일 수 있습니다.
+
--
* CPU: 8개 코어 또는 8개 vCPU
* 램: 32GB
* 디스크 공간: 호스트에 권장되는 디스크 공간은 165GB이며, 다음 파티션 요구 사항이 적용됩니다.
+
** `/opt`: 120GiB의 공간이 사용 가능해야 합니다.
+
에이전트는 다음을 사용합니다. `/opt` 설치하려면 `/opt/application/netapp` 디렉토리와 그 내용.

** `/var`: 40GiB의 공간이 사용 가능해야 합니다.
+
콘솔 에이전트에는 이 공간이 필요합니다. `/var` Docker나 Podman은 이 디렉토리 내에서 컨테이너를 생성하도록 설계되었기 때문입니다.  특히, 그들은 컨테이너를 생성할 것입니다. `/var/lib/containers/storage` 예배 규칙서.  이 공간에서는 외부 마운트나 심볼릭 링크가 작동하지 않습니다.





--
하이퍼바이저:: 지원되는 운영 체제를 실행하도록 인증된 베어 메탈 또는 호스팅 하이퍼바이저가 필요합니다.
[[podman-versions]]운영 체제 및 컨테이너 요구 사항:: 콘솔 에이전트는 표준 모드 또는 제한 모드에서 콘솔을 사용할 때 다음 운영 체제에서 지원됩니다.  에이전트를 설치하기 전에 컨테이너 오케스트레이션 도구가 필요합니다.
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| 운영 체제 | 지원되는 OS 버전 | 지원되는 에이전트 버전 | 필수 컨테이너 도구 | SELinux a 


 a| 
레드햇 엔터프라이즈 리눅스
 a| 
9.1에서 9.4까지

8.6에서 8.10까지

* 영어 버전만 제공됩니다.
* 호스트는 Red Hat Subscription Management에 등록되어야 합니다.  등록되지 않은 경우 호스트는 에이전트 설치 중에 필요한 타사 소프트웨어를 업데이트하기 위해 저장소에 액세스할 수 없습니다.

 a| 
3.9.50 이상, 콘솔이 표준 모드 또는 제한 모드인 경우
 a| 
Podman 버전 4.6.1 또는 4.9.4

<<podman-configuration,Podman 구성 요구 사항 보기>> .
 a| 
강제 모드 또는 허용 모드에서 지원됨

* Cloud Volumes ONTAP 시스템 관리는 운영 체제에서 SELinux가 활성화된 에이전트에서는 지원되지 않습니다.




 a| 
우분투
 a| 
24.04 장기
 a| 
표준 모드 또는 제한 모드에서 NetApp 콘솔을 사용하는 3.9.45 이상
 a| 
Docker 엔진 23.06~28.0.0.
 a| 
지원되지 않음



 a| 
22.04 장기
 a| 
3.9.50 이상
 a| 
Docker 엔진 23.0.6~28.0.0.
 a| 
지원되지 않음

|===
--
Google Cloud 머신 유형:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다.  n2-standard-8을 추천합니다.
+
--
콘솔 에이전트는 OS가 있는 VM 인스턴스의 Google Cloud에서 지원됩니다. https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["보호된 VM 기능"^]

--
/opt의 디스크 공간:: 100GiB의 공간이 사용 가능해야 합니다.
+
--
에이전트는 다음을 사용합니다. `/opt` 설치하려면 `/opt/application/netapp` 디렉토리와 그 내용.

--
/var의 디스크 공간:: 20GiB의 공간이 사용 가능해야 합니다.
+
--
콘솔 에이전트에는 이 공간이 필요합니다. `/var` Docker나 Podman은 이 디렉토리 내에서 컨테이너를 생성하도록 설계되었기 때문입니다.  특히, 그들은 컨테이너를 생성할 것입니다. `/var/lib/containers/storage` 예배 규칙서.  이 공간에서는 외부 마운트나 심볼릭 링크가 작동하지 않습니다.

--




== 2단계: Podman 또는 Docker Engine 설치

운영 체제에 따라 에이전트를 설치하기 전에 Podman 또는 Docker Engine이 필요합니다.

* Red Hat Enterprise Linux 8 및 9에는 Podman이 필요합니다.
+
<<podman-versions,지원되는 Podman 버전 보기>> .

* Ubuntu에는 Docker Engine이 필요합니다.
+
<<podman-versions,지원되는 Docker Engine 버전 보기>> .



.단계
[role="tabbed-block"]
====
.포드만
--
Podman을 설치하고 구성하려면 다음 단계를 따르세요.

* podman.socket 서비스를 활성화하고 시작합니다.
* python3 설치
* podman-compose 패키지 버전 1.0.6을 설치하세요
* PATH 환경 변수에 podman-compose를 추가합니다.
* Red Hat Enterprise Linux 8을 사용하는 경우 Podman 버전이 CNI 대신 Aardvark DNS를 사용하는지 확인하세요.



NOTE: DNS 포트 충돌을 피하기 위해 에이전트를 설치한 후 aardvark-dns 포트(기본값: 53)를 조정하세요.  지침에 따라 포트를 구성하세요.

.단계
. 호스트에 podman-docker 패키지가 설치되어 있다면 제거합니다.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Podman을 설치하세요.
+
공식 Red Hat Enterprise Linux 저장소에서 Podman을 다운로드할 수 있습니다.

+
Red Hat Enterprise Linux 9의 경우:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
여기서 <버전>은 설치하려는 Podman의 지원되는 버전입니다. <<podman-versions,지원되는 Podman 버전 보기>> .

+
Red Hat Enterprise Linux 8의 경우:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
여기서 <버전>은 설치하려는 Podman의 지원되는 버전입니다. <<podman-versions,지원되는 Podman 버전 보기>> .

. podman.socket 서비스를 활성화하고 시작합니다.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. python3를 설치합니다.
+
[source, cli]
----
sudo dnf install python3
----
. 시스템에 EPEL 저장소 패키지가 아직 없으면 설치하세요.
. Red Hat Enterprise를 사용하는 경우:
+
이 단계는 podman-compose가 EPEL(Enterprise Linux용 추가 패키지) 저장소에서 사용 가능하기 때문에 필요합니다.

+
Red Hat Enterprise Linux 9의 경우:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Red Hat Enterprise Linux 8의 경우:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. podman-compose 패키지 1.0.6을 설치합니다.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: 를 사용하여 `dnf install` 명령은 PATH 환경 변수에 podman-compose를 추가하는 요구 사항을 충족합니다.  설치 명령은 이미 포함되어 있는 /usr/bin에 podman-compose를 추가합니다. `secure_path` 호스트의 옵션.

. Red Hat Enterprise Linux 8을 사용하는 경우 Podman 버전이 CNI 대신 Aardvark DNS와 함께 NetAvark를 사용하는지 확인하세요.
+
.. 다음 명령을 실행하여 networkBackend가 CNI로 설정되어 있는지 확인하세요.
+
[source, cli]
----
podman info | grep networkBackend
----
.. networkBackend가 설정된 경우 `CNI` , 당신은 그것을 변경해야 합니다 `netavark` .
.. 설치하다 `netavark` 그리고 `aardvark-dns` 다음 명령을 사용합니다.
+
[source, cli]
----
dnf install aardvark-dns netavark
----
.. 열기 `/etc/containers/containers.conf` 파일을 열고 network_backend 옵션을 "cni" 대신 "netavark"를 사용하도록 수정합니다.


+
만약에 `/etc/containers/containers.conf` 존재하지 않습니다. 구성을 변경하세요. `/usr/share/containers/containers.conf` .

. Podman을 다시 시작하세요.
+
[source, cli]
----
systemctl restart podman
----
. 다음 명령을 사용하여 networkBackend가 이제 "netavark"로 변경되었는지 확인하세요.
+
[source, cli]
----
podman info | grep networkBackend
----


--
.도커 엔진
--
Docker Engine을 설치하려면 Docker 설명서를 따르세요.

.단계
. https://docs.docker.com/engine/install/["Docker에서 설치 지침 보기"^]
+
지원되는 Docker Engine 버전을 설치하려면 다음 단계를 따르세요.  콘솔에서 지원되지 않으므로 최신 버전을 설치하지 마세요.

. Docker가 활성화되어 실행 중인지 확인하세요.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== 3단계: 네트워킹 설정

하이브리드 클라우드 환경 내에서 콘솔 에이전트가 리소스와 프로세스를 관리할 수 있도록 네트워킹을 설정합니다.  예를 들어, 대상 네트워크에 연결이 가능한지, 아웃바운드 인터넷 접속이 가능한지 확인해야 합니다.

대상 네트워크에 대한 연결:: 콘솔 에이전트를 사용하려면 시스템을 만들고 관리하려는 위치에 대한 네트워크 연결이 필요합니다.  예를 들어, Cloud Volumes ONTAP 시스템이나 온프레미스 환경의 스토리지 시스템을 만들 계획인 네트워크입니다.


아웃바운드 인터넷 접속:: 콘솔 에이전트를 배포하는 네트워크 위치에는 특정 엔드포인트에 연결하기 위한 아웃바운드 인터넷 연결이 있어야 합니다.


웹 기반 NetApp 콘솔을 사용할 때 컴퓨터에서 연결된 엔드포인트::
+
--
웹 브라우저에서 콘솔에 액세스하는 컴퓨터는 여러 엔드포인트에 접속할 수 있어야 합니다.  콘솔 에이전트를 설정하고 콘솔을 일상적으로 사용하려면 콘솔을 사용해야 합니다.

link:reference-networking-saas-console.html["NetApp 콘솔을 위한 네트워킹 준비"] .

--


콘솔 에이전트에서 연락한 엔드포인트:: 콘솔 에이전트는 일상 업무를 위해 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리하기 위해 다음 엔드포인트에 연결하기 위해 아웃바운드 인터넷 액세스가 필요합니다.
+
--
아래 나열된 엔드포인트는 모두 CNAME 항목입니다.

[cols="2a,1a"]
|===
| 엔드포인트 | 목적 


 a| 
\ https://www.googleapis.com/compute/v1/ \ https://compute.googleapis.com/compute/v1 \ https://cloudresourcemanager.googleapis.com/v1/projects \ https://www.googleapis.com/compute/beta \ https://storage.googleapis.com/storage/v1 \ https://www.googleapis.com/storage/v1 \ https://iam.googleapis.com/v1 \ https://cloudkms.googleapis.com/v1 \ https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Google Cloud에서 리소스를 관리합니다.



 a| 
\ https://mysupport.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보냅니다.



 a| 
\ https://support.netapp.com
 a| 
라이선스 정보를 얻고 NetApp 지원팀에 AutoSupport 메시지를 보냅니다.



 a| 
\ https://signin.b2c.netapp.com
 a| 
NetApp 지원 사이트(NSS) 자격 증명을 업데이트하거나 NetApp 콘솔에 새로운 NSS 자격 증명을 추가합니다.



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
NetApp 콘솔 내에서 기능과 서비스를 제공합니다.



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
콘솔 에이전트 업그레이드를 위한 이미지를 얻으려면.

* 새로운 에이전트를 배포할 때 유효성 검사를 통해 현재 엔드포인트에 대한 연결성을 테스트합니다.  당신이 사용하는 경우link:link:reference-networking-saas-console-previous.html["이전 종료점"] , 유효성 검사에 실패합니다.  이러한 실패를 방지하려면 유효성 검사를 건너뛰세요.
+
이전 엔드포인트는 계속 지원되지만 NetApp 가능한 한 빨리 현재 엔드포인트에 맞게 방화벽 규칙을 업데이트할 것을 권장합니다. link:reference-networking-saas-console-previous.html#update-endpoint-list["엔드포인트 목록을 업데이트하는 방법을 알아보세요"] .

* 방화벽의 현재 엔드포인트로 업데이트하면 기존 에이전트도 계속 작동합니다.


|===
--


프록시 서버:: NetApp 명시적 프록시 구성과 투명 프록시 구성을 모두 지원합니다.  투명 프록시를 사용하는 경우 프록시 서버에 대한 인증서만 제공하면 됩니다.  명시적 프록시를 사용하는 경우 IP 주소와 자격 증명도 필요합니다.
+
--
* IP 주소
* 신임장
* HTTPS 인증서


--


포트:: Cloud Volumes ONTAP 에서 NetApp 지원팀으로 AutoSupport 메시지를 보내기 위한 프록시로 사용되거나 사용자가 시작하지 않는 한 콘솔 에이전트로 들어오는 트래픽이 없습니다.
+
--
* HTTP(80) 및 HTTPS(443)는 로컬 UI에 대한 액세스를 제공하며 이는 드문 상황에서 사용됩니다.
* SSH(22)는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.
* 아웃바운드 인터넷 연결을 사용할 수 없는 서브넷에 Cloud Volumes ONTAP 시스템을 배포하는 경우 포트 3128을 통한 인바운드 연결이 필요합니다.
+
Cloud Volumes ONTAP 시스템에 AutoSupport 메시지를 보낼 아웃바운드 인터넷 연결이 없는 경우 콘솔은 콘솔 에이전트에 포함된 프록시 서버를 사용하도록 해당 시스템을 자동으로 구성합니다.  유일한 요구 사항은 콘솔 에이전트의 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는 것입니다.  콘솔 에이전트를 배포한 후 이 포트를 열어야 합니다.



--


NTP 활성화:: NetApp 데이터 분류를 사용하여 회사 데이터 소스를 스캔하려는 경우 콘솔 에이전트와 NetApp 데이터 분류 시스템 모두에서 NTP(네트워크 시간 프로토콜) 서비스를 활성화하여 시스템 간의 시간을 동기화해야 합니다. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["NetApp 데이터 분류에 대해 자세히 알아보세요"^]




== 4단계: 콘솔 에이전트에 대한 권한 설정

Google Cloud 서비스 계정은 콘솔 에이전트에 Google Cloud의 리소스를 관리하는 데 필요한 권한을 제공하는 데 필요합니다.  콘솔 에이전트를 만들 때 이 서비스 계정을 콘솔 에이전트 VM과 연결해야 합니다.

이후 릴리스에서 새로운 권한이 추가되면 사용자 지정 역할을 업데이트하는 것은 사용자의 책임입니다.  새로운 권한이 필요한 경우 릴리스 노트에 나열됩니다.

.단계
. Google Cloud에서 사용자 지정 역할을 만듭니다.
+
.. 내용을 포함하는 YAML 파일을 만듭니다.link:reference-permissions-gcp.html["콘솔 에이전트에 대한 서비스 계정 권한"] .
.. Google Cloud에서 Cloud Shell을 활성화합니다.
.. 필요한 권한이 포함된 YAML 파일을 업로드합니다.
.. 다음을 사용하여 사용자 정의 역할을 만듭니다. `gcloud iam roles create` 명령.
+
다음 예제에서는 프로젝트 수준에서 "connector"라는 이름의 역할을 만듭니다.

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud 문서: 사용자 지정 역할 만들기 및 관리"^]



. Google Cloud에서 서비스 계정을 만들고 서비스 계정에 역할을 할당합니다.
+
.. IAM 및 관리 서비스에서 *서비스 계정 > 서비스 계정 만들기*를 선택합니다.
.. 서비스 계정 세부 정보를 입력하고 *만들기 및 계속*을 선택하세요.
.. 방금 만든 역할을 선택하세요.
.. 나머지 단계를 완료하여 역할을 만듭니다.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud 문서: 서비스 계정 만들기"^]



. 콘솔 에이전트가 있는 프로젝트와 다른 프로젝트에 Cloud Volumes ONTAP 시스템을 배포하려는 경우 콘솔 에이전트의 서비스 계정에 해당 프로젝트에 대한 액세스 권한을 제공해야 합니다.
+
예를 들어, 콘솔 에이전트가 프로젝트 1에 있고 프로젝트 2에 Cloud Volumes ONTAP 시스템을 만들고 싶다고 가정해 보겠습니다.  프로젝트 2에서 서비스 계정에 대한 액세스 권한을 부여해야 합니다.

+
.. IAM 및 관리 서비스에서 Cloud Volumes ONTAP 시스템을 만들려는 Google Cloud 프로젝트를 선택합니다.
.. *IAM* 페이지에서 *액세스 권한 부여*를 선택하고 필요한 세부 정보를 제공합니다.
+
*** 콘솔 에이전트 서비스 계정의 이메일을 입력하세요.
*** 콘솔 에이전트의 사용자 지정 역할을 선택합니다.
*** *저장*을 선택하세요.




+
자세한 내용은 다음을 참조하세요. https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud 문서"^]





== 5단계: 공유 VPC 권한 설정

공유 VPC를 사용하여 서비스 프로젝트에 리소스를 배포하는 경우 권한을 준비해야 합니다.

이 표는 참조용이며 IAM 구성이 완료되면 사용자 환경에 권한 표가 반영되어야 합니다.

.공유 VPC 권한 보기
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| 신원 | 창조자 | 호스팅됨 | 서비스 프로젝트 권한 | 호스트 프로젝트 권한 | 목적 


| 에이전트를 배포하기 위한 Google 계정 | 관습 | 봉사 프로젝트  a| 
link:task-install-connector-google-bluexp-gcloud.html#agent-permissions-google["에이전트 배포 정책"]
 a| 
컴퓨팅.네트워크사용자
| 서비스 프로젝트에 에이전트 배포 


| 에이전트 서비스 계정 | 관습 | 봉사 프로젝트  a| 
link:reference-permissions-gcp.html["에이전트 서비스 계정 정책"]
| compute.networkUser 배포 관리자.편집기 | 서비스 프로젝트에서 Cloud Volumes ONTAP 및 서비스 배포 및 유지 관리 


| Cloud Volumes ONTAP 서비스 계정 | 관습 | 봉사 프로젝트 | storage.admin 멤버: NetApp 콘솔 서비스 계정(serviceAccount.user) | 해당 없음 | (선택 사항) NetApp 클라우드 계층화 및 NetApp 백업 및 복구용 


| Google API 서비스 에이전트 | 구글 클라우드 | 봉사 프로젝트  a| 
(기본값) 편집기
 a| 
컴퓨팅.네트워크사용자
| 배포를 대신하여 Google Cloud API와 상호 작용합니다.  콘솔이 공유 네트워크를 사용할 수 있도록 합니다. 


| Google Compute Engine 기본 서비스 계정 | 구글 클라우드 | 봉사 프로젝트  a| 
(기본값) 편집기
 a| 
컴퓨팅.네트워크사용자
| 배포를 대신하여 Google Cloud 인스턴스와 컴퓨팅 인프라를 배포합니다.  콘솔이 공유 네트워크를 사용할 수 있도록 합니다. 
|===
참고사항:

. deploymentmanager.editor는 배포에 방화벽 규칙을 전달하지 않고 콘솔에서 규칙을 생성하도록 선택한 경우에만 호스트 프로젝트에서 필요합니다.  규칙이 지정되지 않으면 NetApp 콘솔은 호스트 프로젝트에 VPC0 방화벽 규칙을 포함하는 배포를 생성합니다.
. firewall.create와 firewall.delete는 배포에 방화벽 규칙을 전달하지 않고 콘솔에서 해당 규칙을 생성하도록 선택한 경우에만 필요합니다.  이러한 권한은 콘솔 계정의 .yaml 파일에 있습니다.  공유 VPC를 사용하여 HA 쌍을 배포하는 경우 이러한 권한은 VPC1, 2, 3에 대한 방화벽 규칙을 만드는 데 사용됩니다.  다른 모든 배포의 경우 이러한 권한은 VPC0에 대한 규칙을 만드는 데에도 사용됩니다.
. 클라우드 계층화의 경우 계층화 서비스 계정에는 프로젝트 수준뿐만 아니라 서비스 계정에 대한 serviceAccount.user 역할이 있어야 합니다.  현재 프로젝트 수준에서 serviceAccount.user를 할당하는 경우 getIAMPolicy로 서비스 계정을 쿼리할 때 권한이 표시되지 않습니다.


====


== 6단계: Google Cloud API 활성화

Google Cloud에서 Cloud Volumes ONTAP 시스템을 배포하려면 먼저 여러 Google Cloud API를 활성화해야 합니다.

.단계
. 프로젝트에서 다음 Google Cloud API를 활성화하세요.
+
** 클라우드 배포 관리자 V2 API
** 클라우드 로깅 API
** 클라우드 리소스 관리자 API
** 컴퓨트 엔진 API
** ID 및 액세스 관리(IAM) API
** 클라우드 키 관리 서비스(KMS) API
+
(고객 관리 암호화 키(CMEK)와 함께 NetApp Backup and Recovery를 사용하려는 경우에만 필요함)





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloud 문서: API 활성화"^]



== 7단계: 콘솔 에이전트 설치

필수 구성 요소를 모두 완료한 후에는 Linux 호스트에 소프트웨어를 수동으로 설치할 수 있습니다.

.시작하기 전에
다음 사항이 있어야 합니다.

* 콘솔 에이전트를 설치하려면 루트 권한이 필요합니다.
* 콘솔 에이전트에서 인터넷에 접속하는 데 프록시가 필요한 경우 프록시 서버에 대한 세부 정보입니다.
+
설치 후 프록시 서버를 구성할 수 있지만, 그렇게 하려면 콘솔 에이전트를 다시 시작해야 합니다.

* 프록시 서버가 HTTPS를 사용하거나 프록시가 가로채기 프록시인 경우 CA 서명 인증서가 필요합니다.



NOTE: 콘솔 에이전트를 수동으로 설치하는 경우 투명 프록시 서버에 대한 인증서를 설정할 수 없습니다.  투명 프록시 서버에 대한 인증서를 설정해야 하는 경우 설치 후 유지 관리 콘솔을 사용해야 합니다. 자세히 알아보세요link:reference-connector-maint-console.html["에이전트 유지 관리 콘솔"] .

.이 작업에 관하여
NetApp 지원 사이트에서 제공되는 설치 프로그램은 이전 버전일 수 있습니다.  설치 후, 새로운 버전이 나오면 콘솔 에이전트가 자동으로 업데이트됩니다.

.단계
. 호스트에 _http_proxy_ 또는 _https_proxy_ 시스템 변수가 설정되어 있으면 제거합니다.
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
이러한 시스템 변수를 제거하지 않으면 설치가 실패합니다.

. 콘솔 에이전트 소프트웨어를 다운로드하세요. https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp 지원 사이트"^] 그런 다음 Linux 호스트에 복사합니다.
+
네트워크나 클라우드에서 사용할 수 있는 "온라인" 에이전트 설치 프로그램을 다운로드해야 합니다.

. 스크립트를 실행할 수 있는 권한을 할당합니다.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
여기서 <버전>은 다운로드한 콘솔 에이전트의 버전입니다.

. 정부 클라우드 환경에 설치하는 경우 구성 검사를 비활성화하세요.link:task-troubleshoot-connector.html#disable-config-check["수동 설치에 대한 구성 검사를 비활성화하는 방법을 알아보세요."]
. 설치 스크립트를 실행합니다.
+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
네트워크에 인터넷 접속을 위한 프록시가 필요한 경우 프록시 정보를 추가해야 합니다.  투명 프록시나 명시적 프록시를 추가할 수 있습니다.  --proxy 및 --cacert 매개변수는 선택 사항이므로 추가하라는 메시지가 표시되지 않습니다.  프록시 서버가 있는 경우 표시된 대로 매개변수를 입력해야 합니다.

+
다음은 CA 서명 인증서로 명시적 프록시 서버를 구성하는 예입니다.

+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy`다음 형식 중 하나를 사용하여 HTTP 또는 HTTPS 프록시 서버를 사용하도록 콘솔 에이전트를 구성합니다.

+
** \http://주소:포트
** \http://사용자 이름:비밀번호@주소:포트
** \http://도메인 이름%92사용자 이름:비밀번호@주소:포트
** \https://주소:포트
** \https://사용자 이름:비밀번호@주소:포트
** \https://도메인 이름%92사용자 이름:비밀번호@주소:포트
+
다음 사항에 유의하세요.

+
*** 사용자는 로컬 사용자 또는 도메인 사용자일 수 있습니다.
*** 도메인 사용자의 경우 위에 표시된 대로 \에 대한 ASCII 코드를 사용해야 합니다.
*** 콘솔 에이전트는 @ 문자가 포함된 사용자 이름이나 비밀번호를 지원하지 않습니다.
*** 비밀번호에 다음과 같은 특수 문자가 포함되어 있는 경우, 백슬래시를 앞에 붙여 해당 특수 문자를 이스케이프해야 합니다: & 또는 !
+
예를 들어:

+
\http://bxpproxyuser:netapp1\!@주소:3128







`--cacert`콘솔 에이전트와 프록시 서버 간 HTTPS 액세스에 사용할 CA 서명 인증서를 지정합니다.  이 매개변수는 HTTPS 프록시 서버, 인터셉트 프록시 서버, 투명 프록시 서버에 필요합니다.

+ 투명 프록시 서버를 구성하는 예는 다음과 같습니다.  투명 프록시를 구성할 때 프록시 서버를 정의할 필요가 없습니다.  콘솔 에이전트 호스트에 CA 서명 인증서만 추가합니다.

+

[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0 --cacert /tmp/cacert/certificate.cer
----
. Podman을 사용한 경우 aardvark-dns 포트를 조정해야 합니다.
+
.. 콘솔 에이전트 가상 머신에 SSH를 실행합니다.
.. podman _/usr/share/containers/containers.conf_ 파일을 열고 Aardvark DNS 서비스에 대해 선택한 포트를 수정합니다.  예를 들어, 54로 변경합니다.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. 콘솔 에이전트 가상 머신을 재부팅합니다.


. 설치가 완료될 때까지 기다리세요.
+
설치가 끝나면 프록시 서버를 지정한 경우 콘솔 에이전트 서비스(occm)가 두 번 다시 시작됩니다.




NOTE: 설치에 실패하면 설치 보고서와 로그를 보고 문제를 해결하는 데 도움이 됩니다.link:task-troubleshoot-connector.html#troubleshoot-installation["설치 문제를 해결하는 방법을 알아보세요."]

. 콘솔 에이전트 가상 머신에 연결된 호스트에서 웹 브라우저를 열고 다음 URL을 입력합니다.
+
https://_ipaddress_[]

. 로그인 후 콘솔 에이전트를 설정하세요.
+
.. 콘솔 에이전트와 연결할 조직을 지정합니다.
.. 시스템 이름을 입력하세요.
.. *보안된 환경에서 실행하고 있습니까?*에서 제한 모드를 비활성화하세요.
+
이 단계에서는 표준 모드에서 콘솔을 사용하는 방법을 설명하므로 제한 모드를 비활성화해야 합니다.  보안 환경이 있고 백엔드 서비스에서 이 계정의 연결을 끊으려는 경우에만 제한 모드를 활성화해야 합니다.  그렇다면,link:task-quick-start-restricted-mode.html["제한 모드에서 NetApp 콘솔을 시작하기 위한 단계를 따르세요."] .

.. *시작하기*를 선택하세요.


+

NOTE: 설치에 실패하면 로그와 보고서를 보고 문제 해결에 도움을 받을 수 있습니다.link:task-troubleshoot-connector.html#troubleshoot-installation["설치 문제를 해결하는 방법을 알아보세요."]



콘솔 에이전트를 생성한 동일한 Google Cloud 계정에 Google Cloud Storage 버킷이 있는 경우, *시스템* 페이지에 Google Cloud Storage 시스템이 자동으로 표시됩니다. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["NetApp 콘솔에서 Google Cloud Storage를 관리하는 방법을 알아보세요."^]



== 8단계: 콘솔 에이전트에 권한 제공

이전에 설정한 Google Cloud 권한을 콘솔 에이전트에 제공해야 합니다.  권한을 제공하면 콘솔 에이전트가 Google Cloud에서 데이터 및 스토리지 인프라를 관리할 수 있습니다.

.단계
. Google Cloud 포털로 이동하여 콘솔 에이전트 VM 인스턴스에 서비스 계정을 할당합니다.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Google Cloud 문서: 인스턴스의 서비스 계정 및 액세스 범위 변경"^]

. 다른 Google Cloud 프로젝트의 리소스를 관리하려면 해당 프로젝트에 콘솔 에이전트 역할이 있는 서비스 계정을 추가하여 액세스 권한을 부여하세요. 각 프로젝트마다 이 단계를 반복해야 합니다.

