---
sidebar: sidebar 
permalink: task-federation-entra-id.html 
keywords: Microsoft Entra ID, BlueXP, federation, single sign-on, SSO, identity provider, IdP, service provider-initiated SSO, domain verification, client secret, redirect URL, organization admin, 
summary: 'NetApp Console 에 대한 SSO(Single Sign-On)를 활성화하려면 Microsoft Entra ID IdP 공급자와 페더레이션하세요.  이를 통해 사용자는 회사 자격 증명을 사용하여 로그인할 수 있습니다.' 
---
= Microsoft Entra ID를 사용하여 NetApp Console 페더레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 에 대한 SSO(Single Sign-On)를 활성화하려면 Microsoft Entra ID IdP 공급자와 페더레이션하세요.  이를 통해 사용자는 회사 자격 증명을 사용하여 로그인할 수 있습니다.

.필수 역할
Federation 관리자 역할은 Federation을 생성하고 관리하는 데 필요합니다. Federation 뷰어는 Federation 페이지를 볼 수 있습니다. link:reference-iam-predefined-roles.html["액세스 역할에 대해 자세히 알아보세요."]


NOTE: 회사 IdP 또는 NetApp 지원 사이트와 연합할 수 있습니다.  NetApp 둘 중 하나만 선택하는 것을 권장하지만, 둘 다 선택하는 것은 권장하지 않습니다.

NetApp 서비스 공급자가 시작하는(SP 가 시작하는) SSO만 지원합니다.  먼저 NetApp 서비스 공급자로 신뢰하도록 ID 공급자를 구성해야 합니다.  그런 다음 콘솔에서 ID 공급자의 구성을 사용하는 연결을 만들 수 있습니다.

Microsoft Entra ID를 사용하여 페더레이션 연결을 설정하면 Console에서 Single Sign-On(SSO)을 사용할 수 있습니다. 이 과정은 Microsoft Entra ID가 Console을 서비스 공급자로 신뢰하도록 구성한 다음 Console에서 연결을 생성하는 것으로 시작됩니다.

.시작하기 전에
* 관리자 권한이 있는 IdP 계정이 필요합니다.  IdP 관리자와 협력하여 단계를 완료하세요.
* 페더레이션에 사용할 도메인을 식별합니다. 이메일 도메인 또는 소유한 다른 도메인을 사용할 수 있습니다. 이메일 도메인 이외의 도메인을 사용하려면 먼저 NetApp Console에서 도메인을 확인해야 합니다. 지침은 link:task-federation-verify-domain.html["NetApp Console 에서 도메인을 확인하세요"]을 참조하십시오.


.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *연합*을 선택하면 *연합* 페이지를 볼 수 있습니다.
. *새 페더레이션 구성*을 선택합니다.


[discrete]
====== 도메인 세부 정보

. 도메인 세부 정보를 입력하세요:
+
.. 검증된 도메인을 사용할지, 이메일 도메인을 사용할지 선택하세요.  이메일 도메인은 로그인한 계정과 연결된 도메인입니다.
.. 구성 중인 페더레이션의 이름을 입력하세요.
.. 검증된 도메인을 선택한 경우 목록에서 도메인을 선택하세요.


. *다음*을 선택하세요.


[discrete]
====== 연결 방법

. 연결 방법으로 *공급자*를 선택한 다음 *Microsoft Entra ID*를 선택하세요.
. *다음*을 선택하세요.


[discrete]
====== 구성 지침

. NetApp 서비스 공급자로 신뢰하도록 Microsoft Entra ID를 구성하세요.  이 단계는 Microsoft Entra ID 서버에서 수행해야 합니다.
+
.. 콘솔을 신뢰하려면 Microsoft Entra ID 앱을 등록할 때 다음 값을 사용하세요.
+
*** *Redirect URL*의 경우 다음을 사용하세요. `https://services.cloud.netapp.com`
*** *답변 URL*의 경우 다음을 사용하세요. `https://netapp-cloud-account.auth0.com/login/callback`


.. Microsoft Entra ID 앱에 대한 클라이언트 비밀번호를 만듭니다.  페더레이션을 완료하려면 클라이언트 ID, 클라이언트 비밀번호, Entra ID 도메인 이름을 제공해야 합니다.


. 콘솔로 돌아가서 *다음*을 선택하여 연결을 만듭니다.


[discrete]
====== 연결 생성

. Microsoft Entra ID와의 연결을 생성합니다.
+
.. 이전 단계에서 생성한 클라이언트 ID와 클라이언트 암호를 입력하십시오.
.. Microsoft Entra ID 도메인 이름을 입력하세요.


. *연결 만들기*를 선택하세요.  시스템은 몇 초 안에 연결을 생성합니다.


[discrete]
====== 연결을 테스트하고 활성화합니다.

. *다음*을 선택하세요.
. 연결을 테스트하려면 *연결 테스트*를 선택하세요. IdP 서버의 로그인 페이지로 이동됩니다. IdP 자격 증명으로 로그인하세요. 로그인 후 콘솔로 돌아가서 연결을 활성화하세요.
+

NOTE: 제한 모드에서 콘솔을 사용하는 경우, URL을 시크릿 브라우저 창이나 별도의 브라우저에 복사하여 IdP에 로그인하십시오.

. 콘솔에서 *다음*을 선택하여 요약 페이지를 검토하십시오.
. 알림을 설정하세요.
+
7일 또는 30일 중에서 선택하세요. 시스템은 만료 알림을 이메일로 발송하고 NetApp Console에 표시하며, 슈퍼 관리자, 조직 관리자, 페더레이션 관리자 및 페더레이션 뷰어 역할을 가진 모든 사용자에게 알림을 보냅니다.

. 연동 세부 정보를 검토한 다음 *연동 활성화*를 선택하십시오.
. *마침*을 선택하여 과정을 완료하세요.


페더레이션을 활성화하면 사용자는 회사 자격 증명을 사용하여 NetApp Console 에 로그인합니다.
