---
sidebar: sidebar 
permalink: task-sign-up-saas.html 
keywords: sign up, signing up, sign in, signing in, login with netapp, log in with netapp, create account, account, log in with nss, nss, nss login 
summary: NetApp Console 웹 기반 콘솔에서 접근할 수 있습니다.  콘솔을 시작하려면 첫 번째 단계로 NetApp 지원 사이트 자격 증명을 사용하여 가입하거나 로그인하거나 NetApp Console 로그인을 만들어야 합니다. 
---
= NetApp Console 에 가입하거나 로그인하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 웹 기반 콘솔에서 접근할 수 있습니다.  콘솔을 시작하려면 첫 번째 단계로 NetApp 지원 사이트 자격 증명을 사용하여 가입하거나 로그인하거나 NetApp Console 로그인을 만들어야 합니다.

.이 작업에 관하여
처음으로 콘솔에 접속하면 다음 옵션 중 하나를 사용하여 가입하거나 로그인할 수 있습니다.

NetApp Console 로그인:: 로그인을 생성하여 가입할 수 있습니다.  이 인증 방법을 사용하려면 이메일 주소와 비밀번호를 지정해야 합니다.  이메일 주소를 확인한 후 로그인하여 아직 조직에 속해 있지 않으면 조직을 만들 수 있습니다.
NetApp 지원 사이트(NSS) 자격 증명:: 기존 NetApp 지원 사이트 자격 증명이 있는 경우 콘솔에 가입할 필요가 없습니다.  NSS 자격 증명을 사용하여 로그인하면 콘솔에서 조직이 없는 경우 조직을 만들라는 메시지가 표시됩니다.
+
--
등록된 이메일 주소로 일회용 비밀번호(OTP)가 전송됩니다.  로그인을 시도할 때마다 새로운 OTP가 생성됩니다.

--
연합 연결:: 회사에 이미 NetApp Console 인스턴스가 있는 경우 콘솔 관리자가 회사 디렉토리의 자격 증명(페더레이션 ID)을 사용하여 로그인하기 위한 단일 로그인을 설정했을 수 있습니다.
+
--
link:concept-federation.html["NetApp Console 사용하여 ID 페더레이션을 사용하는 방법을 알아보세요."] .

--


.단계
. 웹 브라우저를 열고 이동하세요 https://console.netapp.com["NetApp Console"^]
. NetApp 지원 사이트 계정이 있거나 이미 ID 페더레이션을 설정한 경우, *로그인* 페이지에 계정과 연결된 이메일 주소를 직접 입력하세요.
+
두 경우 모두, 초기 로그인의 일부로 콘솔에 가입하게 됩니다.

. 콘솔 로그인을 만들어 가입하려면 *가입*을 선택하세요.
+
.. *가입* 페이지에서 필요한 정보를 입력하고 *다음*을 선택하세요.
+
가입 양식에는 영어 문자만 허용됩니다.

.. NetApp 에서 보낸 이메일이 받은 편지함에서 확인되었는지 확인하세요. 이메일 주소 확인 지침이 포함되어 있습니다.
+
콘솔에 로그인하려면 이 단계를 거쳐야 합니다.



. 로그인 후 최종 사용자 라이선스 계약을 검토하고 약관에 동의하세요.
+
사용자 계정이 아직 콘솔 조직에 속하지 않은 경우 조직을 만들라는 메시지가 표시됩니다.

. *환영* 페이지에서 콘솔 조직의 이름을 입력합니다.
+
콘솔은 조직을 정의하며 콘솔 ID 및 액세스 관리(IAM)의 최상위 요소입니다. link:concept-identity-and-access-management.html["IAM에 대해 알아보세요"] .

+
귀하의 회사에 이미 조직이 있고 귀하가 해당 조직에 가입하고 싶다면 콘솔을 닫고 조직 관리자에게 귀하를 해당 조직에 연결해 달라고 요청하세요.  추가된 후 로그인하면 콘솔 조직에 액세스할 수 있습니다. link:task-iam-manage-members-permissions#add-members["기존 조직에 구성원을 추가하는 방법을 알아보세요"] .

. *시작하기*를 선택하세요.

