---
sidebar: sidebar 
permalink: task-install-private-mode.html 
keywords: install dark site, deploy dark site, install private mode, deploy private mode, install agent dark site, agent dark site, dark site, private mode, no internet 
summary: NetApp Console을 프라이빗 모드로 배포하여 아웃바운드 연결 없이 사용할 수 있습니다. 시작하려면 Console 에이전트를 설치하고, Console 에이전트에서 실행되는 사용자 인터페이스에 액세스하여 NetApp Console을 설정한 다음, 이전에 설정한 클라우드 권한을 제공하십시오. 
---
= Console 에이전트를 비공개 모드로 배포합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console을 프라이빗 모드로 배포하여 아웃바운드 연결 없이 사용할 수 있습니다. 시작하려면 Console 에이전트를 설치하고, Console 에이전트에서 실행되는 사용자 인터페이스에 액세스하여 NetApp Console을 설정한 다음, 이전에 설정한 클라우드 권한을 제공하십시오.



== 1단계: 콘솔 에이전트 설치

NetApp Support Site에서 제품 설치 프로그램을 다운로드한 다음 Linux 호스트에 Console을 수동으로 설치하십시오.

 https://aws.amazon.com/federal/secret-cloud/["AWS Secret Cloud"^] 또는  https://aws.amazon.com/federal/top-secret-cloud/["AWS Top Secret Cloud"^]에서 NetApp Console을 사용하려면 해당 환경에서 시작하기 위한 별도의 지침을 따라야 합니다. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-getting-started-aws-c2s.html["AWS Secret Cloud 또는 Top Secret Cloud에서 Cloud Volumes ONTAP을 시작하는 방법을 알아보세요"^]

.시작하기 전에
* Console 에이전트를 설치하려면 루트 권한이 필요합니다.
* 콘솔 에이전트를 설치하기 전에 운영 체제에 따라 Podman 또는 Docker Engine이 필요합니다.


.단계
. Console 에이전트 소프트웨어는 다음에서 다운로드하십시오. https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp 지원 사이트"^]
+
인터넷 액세스가 없는 프라이빗 네트워크의 경우 오프라인 설치 프로그램을 다운로드하십시오.

. 설치 프로그램을 Linux 호스트에 복사합니다.
. 스크립트를 실행할 수 있는 권한을 할당합니다.
+
[source, cli]
----
chmod +x /path/NetApp-Console-Private-Mode-<version>
----
+
여기서 <버전>은 다운로드한 콘솔 에이전트의 버전입니다.

. 설치 스크립트를 실행합니다.
+
[source, cli]
----
sudo /path/NetApp-Console-Private-Mode-<version>
----
+
여기서 <버전>은 다운로드한 콘솔 에이전트의 버전입니다.



.결과
콘솔 에이전트가 설치되었습니다. 이제 NetApp Console을 설정할 수 있습니다.



== 2단계: NetApp Console 설정

NetApp Console에 처음 액세스하면 NetApp Console을 설정하라는 메시지가 표시됩니다.

.단계
. 웹 브라우저를 열고 Console 에이전트를 설치한 Linux 호스트의 IP 주소를 입력하십시오.
. *새 Console 에이전트 설정*을 선택하고 안내에 따라 시스템을 설정하십시오.
+
** *시스템 세부 정보*: Console 에이전트 이름과 회사 이름을 입력하십시오.
** *관리자 사용자 생성*: 시스템의 관리자 사용자를 생성합니다.
** *검토*: 세부 정보를 검토하고 사용권 계약에 동의한 다음 *설정*을 선택하십시오.


. 방금 생성한 관리자 사용자를 사용하여 NetApp Console에 로그인하십시오.


.결과
콘솔 에이전트가 설치되었습니다. 웹 브라우저에서 해당 IP 주소로 접속하여 개인 모드로 NetApp Console에 액세스하십시오.

콘솔 소프트웨어의 새 버전이 출시되면 NetApp 지원 사이트에 게시됩니다. link:task-upgrade-agent.html["Console 에이전트를 업그레이드하는 방법을 알아보세요."].

.다음은 무엇인가요?
NetApp Console 에이전트에 이전에 설정한 클라우드 공급자 권한을 제공하십시오.



== 3단계: Console 에이전트에 권한 부여

Cloud Volumes ONTAP 작업 환경을 생성하려면 이전에 설정한 클라우드 공급자 권한을 Console 에이전트에 제공해야 합니다.

link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["클라우드 권한을 준비하는 방법을 알아보세요"].

[role="tabbed-block"]
====
.AWS IAM 역할
--
이전에 생성한 IAM 역할을 Console 에이전트 EC2 인스턴스에 연결합니다.

.단계
. Amazon EC2 콘솔로 이동합니다.
. *인스턴스*를 선택하세요.
. 콘솔 에이전트 인스턴스를 선택합니다.
. *작업 > 보안 > IAM 역할 수정*을 선택합니다.
. IAM 역할을 선택하고 *IAM 역할 업데이트*를 선택합니다.


--
.AWS 액세스 키
--
Console 에이전트에 필요한 권한을 가진 IAM 사용자의 AWS 액세스 키를 제공하십시오.

.단계
. *관리 > 자격 증명*을 선택합니다.
. *조직 자격 증명*을 선택하세요.
. *자격 증명 추가*를 선택하고 마법사의 단계를 따르세요.
+
.. *자격 증명 위치*: *Amazon Web Services > 에이전트를 선택하세요.
.. *자격 증명 정의*: AWS 액세스 키와 비밀 키를 입력합니다.
.. *마켓플레이스 구독*: 지금 구독하거나 기존 구독을 선택하여 마켓플레이스 구독을 이러한 자격 증명과 연결합니다.
.. *검토*: 새로운 자격 증명에 대한 세부 정보를 확인하고 *추가*를 선택합니다.




--
.Azure 역할
--
Azure Portal로 이동하여 하나 이상의 구독에 대한 콘솔 에이전트 가상 머신에 Azure 사용자 지정 역할을 할당합니다.

.단계
. Azure Portal에서 *구독* 서비스를 열고 구독을 선택합니다.
+
*구독* 서비스에서 역할을 할당하는 것이 중요한 이유는 이를 통해 구독 수준에서 역할 할당의 범위가 지정되기 때문입니다.  _scope_는 액세스가 적용되는 리소스 집합을 정의합니다.  다른 수준(예: 가상 머신 수준)에서 범위를 지정하는 경우 NetApp Console 내에서 작업을 완료하는 기능에 영향을 미칩니다.

+
https://learn.microsoft.com/en-us/azure/role-based-access-control/scope-overview["Microsoft Azure 설명서: Azure RBAC 범위 이해"^]

. *액세스 제어(IAM)* > *추가* > *역할 할당 추가*를 선택합니다.
. *역할* 탭에서 *콘솔 운영자* 역할을 선택하고 *다음*을 선택합니다.
+

NOTE: 콘솔 운영자는 정책에 제공된 기본 이름입니다.  역할에 다른 이름을 선택한 경우 해당 이름을 대신 선택하세요.

. *멤버* 탭에서 다음 단계를 완료하세요.
+
.. *관리되는 ID*에 대한 액세스 권한을 할당합니다.
.. *멤버 선택*을 선택하고, 콘솔 에이전트 가상 머신이 생성된 구독을 선택하고, *관리 ID*에서 *가상 머신*을 선택한 다음, 콘솔 에이전트 가상 머신을 선택합니다.
.. *선택*을 선택하세요.
.. *다음*을 선택하세요.
.. *검토 + 할당*을 선택하세요.
.. 추가 Azure 구독의 리소스를 관리하려면 해당 구독으로 전환한 다음 이러한 단계를 반복합니다.




--
.Azure 서비스 주체
--
NetApp Console 에이전트에 이전에 설정한 Azure 서비스 주체에 대한 자격 증명을 제공하십시오.

.단계
. *관리 > 자격 증명*을 선택합니다.
. *자격 증명 추가*를 선택하고 마법사의 단계를 따르세요.
+
.. *자격 증명 위치*: *Microsoft Azure > 에이전트*를 선택합니다.
.. *자격 증명 정의*: 필요한 권한을 부여하는 Microsoft Entra 서비스 주체에 대한 정보를 입력합니다.
+
*** 애플리케이션(클라이언트) ID
*** 디렉토리(테넌트) ID
*** 클라이언트 비밀번호


.. *마켓플레이스 구독*: 지금 구독하거나 기존 구독을 선택하여 마켓플레이스 구독을 이러한 자격 증명과 연결합니다.
.. *검토*: 새로운 자격 증명에 대한 세부 정보를 확인하고 *추가*를 선택합니다.




--
.Google Cloud 서비스 계정
--
서비스 계정을 콘솔 에이전트 VM과 연결합니다.

.단계
. Google Cloud 포털로 이동하여 콘솔 에이전트 VM 인스턴스에 서비스 계정을 할당합니다.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Google Cloud 문서: 인스턴스의 서비스 계정 및 액세스 범위 변경"^]

. 다른 프로젝트의 리소스를 관리하려면 해당 프로젝트에 콘솔 에이전트 역할이 있는 서비스 계정을 추가하여 액세스 권한을 부여하세요.  각 프로젝트마다 이 단계를 반복해야 합니다.


--
====