---
sidebar: sidebar 
permalink: task-maintain-connectors.html 
keywords: agent operating system, agent maintenance, vm maintenance, os updates, operating system updates, stop agent, restart agent, notifications, agent health, agent disk space, agent cpu usage, agent ram usage, agent vm, agent ip address, agent uri, connector, connector health 
summary: 에이전트 호스트에서 운영 체제를 유지 관리하는 것은 사용자의 책임입니다.  예를 들어, 회사의 운영 체제 배포 표준 절차에 따라 콘솔 에이전트 호스트의 운영 체제에 보안 업데이트를 적용해야 합니다. 
---
= 콘솔 에이전트 VM 및 운영 체제 유지 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
콘솔 에이전트 호스트에서 운영 체제를 유지 관리하는 것은 귀하(고객)의 책임입니다.  예를 들어, 귀하(고객)는 회사의 운영 체제 배포에 대한 표준 절차에 따라 에이전트 호스트의 운영 체제에 보안 업데이트를 적용해야 합니다.


TIP: 기존 에이전트가 있는 경우 다음 사항을 알아야 합니다.link:reference-connector-operating-system-changes.html["지원되는 Linux 운영 체제 변경 사항"] .



== 운영 체제 패치 및 에이전트

에이전트 호스트 서비스를 중단하지 않고 OS 보안 패치를 적용합니다.



== VM 또는 인스턴스 유형

콘솔에서 콘솔 에이전트를 생성하면 기본 구성으로 클라우드 공급자에 VM 인스턴스가 배포됩니다.  에이전트를 만든 후에는 CPU나 RAM이 적은 더 작은 VM 인스턴스로 전환하지 마세요.

다음 표는 CPU 및 RAM 요구 사항을 나열합니다.

CPU:: 8개 코어 또는 8개 vCPU
숫양:: 32GB


link:reference-connector-default-config.html["에이전트의 기본 구성에 대해 알아보세요"] .



== 에이전트를 모니터링하세요

콘솔은 디스크 공간, RAM, CPU 문제 등 에이전트 VM에 문제가 있을 때 알려줍니다.  콘솔 내 알림 센터에서 이러한 알림을 모니터링하거나 이메일 알림을 구성하세요.  디스크 공간, 메모리 또는 CPU 사용량이 가끔씩 증가하는 것은 정상적인 현상이지만, 자주 발생하는 경우 해결을 위한 조치를 취해야 합니다.

예를 들어, 콘솔은 에이전트 리소스(CPU, RAM 또는 디스크 공간)가 30분 연속으로 전체 용량의 90%를 초과하면 알려줍니다.  이후 리소스 사용량이 임계값 아래로 떨어지면 알림 센터에 알림이 해결됨(녹색)으로 표시됩니다.


NOTE: 에이전트 VM 수정에 관한 질문이 있으면 NetApp 지원팀에 문의하세요.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#notification-center["자세히 알아보세요."^]

[cols="47,47"]
|===
| 공고 | 필요한 조치 


| 디스크 공간이 너무 많습니다 | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["NetApp 기술 자료 문서를 검토하세요"^] . 


| CPU 사용량이 너무 높습니다 | 설치한 위치에 따라 클라우드 공급자나 온프레미스에서 에이전트 VM의 CPU 크기를 늘리세요.  또는 추가 에이전트를 만들고 작업 부하를 여러 에이전트에 분산합니다.  RAM 사용률은 환경, ONTAP 작업 부하, Cloud Volumes ONTAP 시스템 수, 사용 중인 데이터 서비스에 따라 달라질 수 있습니다. 


| RAM 사용량이 너무 높습니다 | 설치한 위치에 따라 클라우드 공급자나 온프레미스에서 에이전트 VM의 RAM을 늘리세요.  또는 추가 에이전트를 만들고 작업 부하를 여러 에이전트에 분산합니다.  RAM 사용률은 환경, ONTAP 작업 부하, Cloud Volumes ONTAP 시스템 수, 사용 중인 데이터 서비스에 따라 달라질 수 있습니다. 
|===


== 에이전트 VM 중지 및 시작

필요한 경우 클라우드 공급자의 콘솔이나 표준 온프레미스 절차를 사용하여 에이전트 VM을 중지하고 시작합니다.

link:concept-connectors.html#connectors-must-be-operational-at-all-times["콘솔 에이전트는 항상 작동 중이어야 한다는 점을 알아두십시오."] .



== Linux VM에 연결

에이전트가 실행되는 Linux VM에 연결해야 하는 경우 클라우드 공급자의 연결 옵션을 사용하세요.

AWS:: AWS에서 에이전트 인스턴스를 생성할 때 AWS 액세스 키와 비밀 키를 제공하세요.  이 키 쌍을 사용하여 인스턴스에 SSH를 실행할 수 있습니다.  EC2 Linux 인스턴스에는 사용자 이름 'ubuntu'를 사용합니다.  2023년 5월 이전에 생성된 에이전트의 경우 사용자 이름 'ec2-user'를 사용하세요.
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS Docs: Linux 인스턴스에 연결"^]

--
하늘빛:: Azure에서 에이전트 VM을 만들 때 사용자 이름을 지정하고 암호 또는 SSH 공개 키로 인증하도록 선택합니다.  VM에 연결하기 위해 선택한 인증 방법을 사용하세요.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure Docs: VM에 SSH로 연결"^]

--
구글 클라우드:: Google Cloud에서 에이전트를 생성할 때 인증 방법을 지정할 수 없습니다.  하지만 Google Cloud Console이나 Google Cloud CLI(gcloud)를 사용하여 Linux VM 인스턴스에 연결할 수 있습니다.
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs: Linux VM에 연결"^]

--




== 에이전트의 IP 주소 변경

필요한 경우 클라우드 공급자가 할당한 에이전트 인스턴스의 내부 및 공용 IP 주소를 변경할 수 있습니다.

.단계
. 클라우드 제공업체의 지침에 따라 에이전트 인스턴스의 로컬 IP 주소나 공용 IP 주소(또는 둘 다)를 변경하세요.
. 콘솔에 새로운 공용 IP 주소를 등록하려면 에이전트 인스턴스를 다시 시작합니다.
. 개인 IP 주소를 변경한 경우 Cloud Volumes ONTAP 구성 파일의 백업 위치를 업데이트하여 백업이 에이전트의 새 개인 IP 주소로 전송되도록 합니다.
+
각 Cloud Volumes ONTAP 시스템의 백업 위치를 업데이트합니다.

+
.. Cloud Volumes ONTAP CLI에서 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
.. 다음 명령을 실행하여 현재 백업 대상을 표시합니다.
+
[source, cli]
----
system configuration backup settings show
----
.. 다음 명령을 실행하여 백업 대상의 IP 주소를 업데이트합니다.
+
[source, cli]
----
system configuration backup settings modify -destination <target-location>
----






== 에이전트의 URI 편집

에이전트에 대한 URI(Uniform Resource Identifier)를 추가하거나 제거할 수 있습니다.

.단계
. *관리 > 에이전트*를 선택하세요.
. *개요* 페이지에서 콘솔 에이전트의 작업 메뉴를 선택하고 *에이전트 편집*을 선택합니다.
+
편집하려면 콘솔 에이전트가 활성화되어 있어야 합니다.

. *에이전트 URI* 막대를 확장하여 에이전트 URI를 확인하세요.
. URI를 추가하고 제거한 다음 *적용*을 선택합니다.

