---
sidebar: sidebar 
permalink: task-uninstall-agent.html 
keywords: uninstall, remove connector, uninstall connector, uninstall agent, remove agent 
summary: Console 에이전트를 제거하여 문제를 해결하거나 호스트에서 영구적으로 제거할 수 있습니다. 필요한 단계는 사용 중인 배포 모드에 따라 다릅니다. 환경에서 Console 에이전트를 제거한 후에는 Console에서도 해당 에이전트를 제거할 수 있습니다. 
---
= NetApp Console 에이전트 제거 및 삭제
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Console 에이전트를 제거하여 문제를 해결하거나 호스트에서 영구적으로 제거할 수 있습니다. 필요한 단계는 사용 중인 배포 모드에 따라 다릅니다. 환경에서 Console 에이전트를 제거한 후에는 Console에서도 해당 에이전트를 제거할 수 있습니다.



[[uninstall-the-agent-when-it-has-outbound-connectivity]]
== 아웃바운드 연결이 있는 경우 에이전트를 제거합니다

표준 모드나 제한 모드(즉, 에이전트 호스트에 아웃바운드 연결이 있는 경우)를 사용하는 경우 아래 단계에 따라 에이전트를 제거해야 합니다.

.단계
. 에이전트의 Linux VM에 연결합니다.
. Linux 호스트에서 제거 스크립트를 실행합니다.
+
`/opt/application/netapp/service-manager-2/uninstall.sh [silent]`

+
_silent_는 확인을 묻지 않고 스크립트를 실행합니다.





[[uninstall-the-agent-when-it-has-no-outbound-connectivity]]
== 아웃바운드 연결이 없을 때 에이전트를 제거합니다

에이전트에 아웃바운드 연결이 없는 경우(예: 프라이빗 모드) 호스트에서 에이전트 소프트웨어를 수동으로 제거해야 합니다.

.단계
. 콘솔 에이전트를 위해 Linux VM에 연결합니다.
. Linux 호스트에서 다음 명령을 실행합니다.
+
[source, cli]
----
/opt/application/netapp/ds/cleanup.sh
rm -rf /opt/application/netapp/
----
. Linux 호스트에서 사용하지 않는 이전 컨테이너 이미지 파일을 삭제하여 /var 디렉토리의 재설치 공간을 확보하십시오.
+
[role="tabbed-block"]
====
.포드만
--
[source, cli]
----
podman system prune --all
----
--
.Docker
--
[source, cli]
----
docker system prune -a
----
--
====




[[remove-console-agents-from-the-console]]
== 콘솔에서 콘솔 에이전트 제거

에이전트 VM을 삭제하거나 에이전트를 설치 해제한 경우 콘솔의 에이전트 목록에서 해당 에이전트를 제거해야 합니다. 에이전트 VM을 삭제하거나 에이전트 소프트웨어를 제거한 후 에이전트는 콘솔에서 *연결 끊김* 상태로 표시됩니다.

콘솔 에이전트를 제거하는 방법에 대한 자세한 내용은 다음과 같습니다.

* 이 작업을 수행해도 가상 머신은 삭제되지 않습니다.
* 이 작업은 되돌릴 수 없습니다. 콘솔 에이전트를 제거하면 다시 추가할 수 없습니다.


.단계
. *관리 > 에이전트*를 선택하세요.
. *개요* 페이지에서 연결이 끊긴 에이전트의 작업 메뉴를 선택하고 *에이전트 제거*를 선택합니다.
. 확인하려면 에이전트 이름을 입력한 후 *제거*를 선택하세요.

