= BlueXP ID 및 액세스 관리
:allow-uri-read: 




=== BlueXP ID 및 액세스 관리

BlueXP ID 및 액세스 관리(IAM)는 BlueXP 표준 모드로 사용할 때 BlueXP 계정에서 제공하던 기존 기능을 대체하고 향상시키는 새로운 리소스 및 액세스 관리 모델입니다.

BlueXP IAM은 리소스와 권한을 보다 세부적으로 관리합니다.

* 최상위 _조직_을 사용하면 다양한 _프로젝트_에 대한 액세스를 관리할 수 있습니다.
* _폴더_를 사용하면 관련 프로젝트를 함께 그룹화할 수 있습니다.
* 향상된 리소스 관리를 통해 리소스를 하나 이상의 폴더나 프로젝트와 연결할 수 있습니다.
+
예를 들어, Cloud Volumes ONTAP 시스템을 여러 프로젝트와 연결할 수 있습니다.

* 향상된 액세스 관리를 통해 조직 계층의 다양한 수준에 있는 구성원에게 역할을 할당할 수 있습니다.


이러한 향상된 기능을 통해 사용자가 수행할 수 있는 작업과 액세스할 수 있는 리소스를 더 효과적으로 제어할 수 있습니다.

.BlueXP IAM이 기존 계정에 미치는 영향
BlueXP 에 로그인하면 다음과 같은 변경 사항을 확인할 수 있습니다.

* 귀하의 _계정_은 이제 _조직_이라고 합니다.
* 이제 _작업공간_을 _프로젝트_라고 합니다.
* 사용자 역할의 이름이 변경되었습니다.
+
** _계정 관리자_는 이제 _조직 관리자_입니다.
** _작업 공간 관리자_는 이제 _폴더 또는 프로젝트 관리자_입니다.
** _규정 준수 뷰어_가 이제 _분류 뷰어_로 변경되었습니다.


* 설정에서 BlueXP ID 및 액세스 관리에 액세스하여 이러한 향상된 기능을 활용할 수 있습니다.


다음 사항에 유의하세요.

* 기존 사용자나 작업 환경에는 변경 사항이 없습니다.
* 역할의 이름은 변경되었지만 권한 관점에서는 차이가 없습니다.  사용자는 이전과 동일한 작업 환경에 계속 액세스할 수 있습니다.
* BlueXP 에 로그인하는 방법에는 변경 사항이 없습니다.  BlueXP IAM은 BlueXP 계정과 마찬가지로 NetApp 클라우드 로그인, NetApp 지원 사이트 자격 증명 및 페더레이션 연결과 함께 작동합니다.
* 여러 개의 BlueXP 계정이 있었다면 이제 여러 개의 BlueXP 조직이 있게 됩니다.


.BlueXP IAM용 API
이 변경으로 BlueXP IAM에 대한 새로운 API가 도입되었지만 이전 테넌시 API와 하위 호환됩니다. https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["BlueXP IAM API에 대해 알아보세요"^]

.지원되는 배포 모드
BlueXP IAM은 BlueXP 표준 모드로 사용할 때 지원됩니다.  제한 모드나 비공개 모드에서 BlueXP 사용하는 경우 BlueXP 계정을 사용하여 작업 공간, 사용자 및 리소스를 계속 관리하게 됩니다.

.다음에 어디로 가야 할까
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-identity-and-access-management.html["BlueXP IAM에 대해 알아보세요"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-get-started.html["BlueXP IAM 시작하기"]




=== 커넥터 3.9.45

이 릴리스에는 확장된 운영 체제 지원과 버그 수정이 포함되어 있습니다.

3.9.45 릴리스는 표준 모드와 제한 모드에서 사용할 수 있습니다.

.Ubuntu 24.04 LTS 지원
BlueXP 3.9.45 릴리스부터 표준 모드 또는 제한 모드에서 BlueXP 사용할 때 Ubuntu 24.04 LTS 호스트에 커넥터를 새로 설치할 수 있도록 지원합니다.

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html#step-1-review-host-requirements["커넥터 호스트 요구 사항 보기"] .



=== RHEL 호스트를 사용한 SELinux 지원

BlueXP 이제 SELinux가 강제 모드 또는 허용 모드로 활성화된 Red Hat Enterprise Linux 호스트와의 커넥터를 지원합니다.

SELinux에 대한 지원은 표준 모드와 제한 모드의 경우 3.9.40 릴리스부터 시작되고, 개인 모드의 경우 3.9.42 릴리스부터 시작됩니다.

다음 제한 사항을 참고하세요.

* BlueXP Ubuntu 호스트에서 SELinux를 지원하지 않습니다.
* SELinux가 운영 체제에서 활성화된 커넥터에서는 Cloud Volumes ONTAP 시스템 관리가 지원되지 않습니다.


https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/using_selinux/getting-started-with-selinux_using-selinux["SELinux에 대해 자세히 알아보세요"^]
