= 커넥터 이미지를 얻기 위한 새로운 보안 엔드포인트
:allow-uri-read: 




=== 커넥터 이미지를 얻기 위한 새로운 보안 엔드포인트

커넥터를 설치하거나 자동 업그레이드가 발생하면 커넥터는 저장소에 접속하여 설치 또는 업그레이드를 위한 이미지를 다운로드합니다.  기본적으로 커넥터는 항상 다음 엔드포인트에 접속했습니다.

* \https://*.blob.core.windows.net
* \ https://cloudmanagerinfraprod.azurecr.io


첫 번째 종착점에는 정확한 위치를 제공할 수 없기 때문에 와일드 카드가 포함되어 있습니다.  저장소의 부하 분산은 서비스 제공자가 관리하는데, 이는 다운로드가 여러 엔드포인트에서 발생할 수 있음을 의미합니다.

보안을 강화하기 위해 커넥터는 이제 전용 엔드포인트에서 설치 및 업그레이드 이미지를 다운로드할 수 있습니다.

* \ https://bluexpinfraprod.eastus2.data.azurecr.io
* \ https://bluexpinfraprod.azurecr.io


방화벽 규칙에서 기존 엔드포인트를 제거하고 새 엔드포인트를 허용하여 새 엔드포인트를 사용하는 것이 좋습니다.

이러한 새로운 엔드포인트는 Connector 3.9.47 릴리스부터 지원됩니다.  Connector의 이전 릴리스와는 하위 호환성이 없습니다.

다음 사항에 유의하세요.

* 기존 엔드포인트는 계속 지원됩니다.  새로운 엔드포인트를 사용하지 않으려면 아무런 변경도 필요하지 않습니다.
* 커넥터는 먼저 기존 엔드포인트에 접속합니다.  해당 엔드포인트에 접근할 수 없는 경우 커넥터는 자동으로 새 엔드포인트에 연결합니다.
* 다음 시나리오에서는 새로운 엔드포인트가 지원되지 않습니다.
+
** 커넥터가 정부 지역에 설치된 경우.
** BlueXP backup and recovery 또는 BlueXP ransomware protection 과 함께 Connector를 사용하는 경우.


+
두 시나리오 모두 기존 엔드포인트를 계속 사용할 수 있습니다.


