= 커넥터 3.9.52
:allow-uri-read: 




=== 커넥터 3.9.52

BlueXP 커넥터의 이번 릴리스에는 사소한 보안 개선 사항과 버그 수정, 그리고 몇 가지 추가 업데이트가 포함되어 있습니다.

현재 3.9.52 릴리스는 표준 모드와 제한 모드에서 사용할 수 있습니다.



==== Docker 27 및 Docker 28 지원

Docker 27 및 Docker 28이 이제 커넥터에서 지원됩니다.



==== Cloud Volumes ONTAP

커넥터가 규정을 준수하지 않거나 14일 이상 다운되더라도 Cloud Volumes ONTAP 노드가 더 이상 종료되지 않습니다.  Cloud Volumes ONTAP 커넥터에 대한 액세스 권한을 잃어도 이벤트 관리 메시지를 계속 보냅니다.  이러한 변경 사항은 커넥터가 장기간 중단되더라도 Cloud Volumes ONTAP 계속 작동할 수 있도록 보장하기 위한 것입니다.  이는 커넥터에 대한 규정 준수 요구 사항을 변경하지 않습니다.



=== BlueXP 에서 Keystone 관리 사용 가능

BlueXP 의 NetApp Keystone 베타 버전에는 Keystone 관리에 대한 액세스가 추가되었습니다.  BlueXP 의 왼쪽 탐색 모음에서 NetApp Keystone 베타에 대한 등록 페이지에 액세스할 수 있습니다.



=== BlueXP ID 및 액세스 관리(IAM)



==== 새로운 스토리지 관리 역할

스토리지 관리자, 시스템 상태 전문가, 스토리지 뷰어 역할을 사용할 수 있으며 사용자에게 할당할 수 있습니다.

이러한 역할을 통해 조직 내에서 누가 스토리지 리소스를 검색하고 관리할 수 있는지, 스토리지 상태 정보를 보고 소프트웨어 업데이트를 수행할 수 있는지 관리할 수 있습니다.

이러한 역할은 다음 스토리지 리소스에 대한 액세스를 제어하는 데 지원됩니다.

* E-시리즈 시스템
* StorageGRID 시스템
* 온프레미스 ONTAP 시스템


이러한 역할을 사용하여 다음 BlueXP 서비스에 대한 액세스를 제어할 수도 있습니다.

* 소프트웨어 업데이트
* 디지털 어드바이저
* 운영 회복력
* 경제적 효율성
* 지속 가능성


다음 역할이 추가되었습니다.

* *저장소 관리자*
+
조직의 스토리지 리소스에 대한 스토리지 상태, 거버넌스 및 검색을 관리합니다.  이 역할은 스토리지 리소스에 대한 소프트웨어 업데이트도 수행할 수 있습니다.

* *시스템 건강 전문가*
+
조직의 스토리지 리소스에 대한 스토리지 상태와 거버넌스를 관리합니다.  이 역할은 스토리지 리소스에 대한 소프트웨어 업데이트도 수행할 수 있습니다.  이 역할은 작업 환경을 수정하거나 삭제할 수 없습니다.

* *저장소 뷰어*
+
저장소 상태 정보와 거버넌스 데이터를 확인하세요.

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["액세스 역할에 대해 알아보세요."^]


