= 
:allow-uri-read: 


운영 체제에 따라 에이전트를 설치하기 전에 Podman 또는 Docker Engine이 필요합니다.

* Red Hat Enterprise Linux 8 및 9에는 Podman이 필요합니다.
+
<<podman-versions,지원되는 Podman 버전 보기>> .

* Ubuntu에는 Docker 엔진이 필요합니다.
+
<<podman-versions,지원되는 Docker Engine 버전 보기>> .



.단계
[role="tabbed-block"]
====
.포드만
--
Podman 설치 및 구성:

* podman.socket 서비스를 활성화하고 시작합니다.
* python3 설치
* 해당 podman-compose 패키지를 설치하세요
* PATH 환경 변수에 podman-compose를 추가합니다.
* Podman 버전이 CNI 대신 Netavark Aardvark DNS를 사용하고 있는지 확인하세요.



NOTE: DNS 포트 충돌을 피하기 위해 에이전트를 설치한 후 aardvark-dns 포트(기본값: 53)를 조정하세요.  지침에 따라 포트를 구성하세요.

.단계
. 호스트에 podman-docker 패키지가 설치되어 있다면 제거합니다.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Podman을 설치하세요.
+
Red Hat Enterprise Linux 저장소에서 Podman을 가져옵니다.

+
Red Hat Enterprise Linux 9의 경우:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
여기서 <버전>은 설치하려는 Podman의 지원되는 버전입니다. <<podman-versions,지원되는 Podman 버전 보기>> .

+
Red Hat Enterprise Linux 8의 경우:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
여기서 <버전>은 설치하려는 Podman의 지원되는 버전입니다. <<podman-versions,지원되는 Podman 버전 보기>> .

. podman.socket 서비스를 활성화하고 시작합니다.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. python3를 설치합니다.
+
[source, cli]
----
sudo dnf install python3
----
. podman-compose를 얻으려면 EPEL을 설치하세요.
+
.. Red Hat Enterprise 9.1~9.6을 사용하는 경우:
+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----


. podman-compose 패키지 1.5.0을 설치합니다.
+
[source, cli]
----
sudo dnf install podman-compose-1.5.0
----
+
.. Red Hat Enterprise Linux 8을 사용하는 경우:
+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----


. podman-compose 패키지 1.0.6을 설치합니다.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: 를 사용하여 `dnf install` 명령은 PATH 환경 변수에 podman-compose를 추가하는 요구 사항을 충족합니다.  설치 명령은 이미 포함되어 있는 /usr/bin에 podman-compose를 추가합니다. `secure_path` 호스트의 옵션.

. Red Hat Enterprise Linux 8을 사용하는 경우 Podman 버전이 CNI 대신 Aardvark DNS와 함께 NetAvark를 사용하는지 확인하세요.
+
.. 다음 명령을 실행하여 networkBackend가 CNI로 설정되어 있는지 확인하세요.




[listing]
----
podman info | grep networkBackend
----
. networkBackend가 설정된 경우 `CNI` , 당신은 그것을 변경해야 합니다 `netavark` .
. 설치하다 `netavark` 그리고 `aardvark-dns` 다음 명령을 사용합니다.


[listing]
----
dnf install aardvark-dns netavark
----
. 열기 `/etc/containers/containers.conf` 파일을 열고 network_backend 옵션을 "cni" 대신 "netavark"를 사용하도록 수정합니다.
+
만약에 `/etc/containers/containers.conf` 존재하지 않습니다. 구성을 변경하세요. `/usr/share/containers/containers.conf` .

+
.. Podman을 다시 시작하세요.




[listing]
----
systemctl restart podman
----
. 다음 명령을 사용하여 networkBackend가 이제 "netavark"로 변경되었는지 확인하세요.


[listing]
----
podman info | grep networkBackend
----
--
.도커 엔진
--
Docker Engine을 설치하려면 Docker 설명서를 따르세요.

.단계
. https://docs.docker.com/engine/install/["Docker에서 설치 지침 보기"^]
+
다음 단계에 따라 지원되는 Docker Engine 버전을 설치하세요. 콘솔에서 최신 버전을 지원하지 않으므로 최신 버전을 설치하지 마세요.

. Docker가 활성화되어 실행 중인지 확인하세요.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====